### ISSUE TITLE
How to backup and transfer to other server

### ISSUE THREAD

**Issue by alvares** [canove/whaticket#101]
Hi. I need to transfer to another server, but i would like to know how to backup users and conversations (tickets). 
The files exchanged already identified in backend/public.

Can anyone tell me how to proceed with the backup and transfer to another server?

**Comment by canove** [comment]
Hi @alvares. All system information is stored in database, you just need to back-up your mariadb database and restore it after reinstalling. You can find more information about in[ mariadb's docker hub page](https://hub.docker.com/_/mariadb): 

Backup:
`docker exec some-mariadb sh -c 'exec mysqldump --all-databases -uroot -p"$MYSQL_ROOT_PASSWORD"' > /some/path/on/your/host/all-databases.sql`

Restore: 
`docker exec -i some-mariadb sh -c 'exec mysql -uroot -p"$MYSQL_ROOT_PASSWORD"' < /some/path/on/your/host/all-databases.sql`
