### ISSUE TITLE
Sequlize error

### ISSUE THREAD

**Issue by VISWESWARAN1998** [canove/whaticket#105]
While running this Sequelize command I am getting this error

```
ERROR: Error reading "dist/config/database.js". Error: SyntaxError: Unexpected token :
The command '/bin/sh -c npx sequelize db:migrate' returned a non-zero code: 1
```

Can somebody please explain how to solve this. Thank you!

**Comment by canove** [comment]
Hi, @VISWESWARAN1998.
What version of node are u using? `node -v`

The backend/src/dist folder exists?

**Comment by VISWESWARAN1998** [comment]
I just installed nodejs with apt-get update (v10.19.0).

Actually I am not experienced with nodejs and things. I am trying to port this to docker image so that I can easily deploy it on my server. Currently only MySQL is used as docker.

**Comment by VISWESWARAN1998** [comment]
Here what I have tried

```
# Install nodejs and npm
RUN apt-get install nodejs -y
RUN apt-get install npm -y
RUN node -v
COPY . /whatsapp
WORKDIR /whatsapp
RUN git clone https://github.com/canove/whaticket/ src
WORKDIR /whatsapp/src
RUN cp ../.env backend/.env
RUN cd backend && ls -a
WORKDIR /whatsapp/src/backend
RUN pwd
RUN npm install
RUN npm build
RUN npx sequelize init
RUN cat dist/config/database.js
RUN sleep 10
RUN npx sequelize db:migrate
RUN npx sequelize db:seed:all

```
