### ISSUE TITLE
error npm install backend

### ISSUE THREAD

**Issue by realedwilson** [canove/whaticket#107]
src/utils/logger.ts:1:18 - error TS2307: Cannot find module 'pino' or its corresponding type declarations.

1 import pino from "pino";
                   ~~~~~~


Found 1 error.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! backend@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the backend@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

What should I do? Suggestions?

**Comment by canove** [comment]
Hi, @realedwilson. 

What node / npm versions are you running? 

You can try deleting `node_modules` folder on backend and, after that,  run `npm install` and `npm run build`

**Comment by realedwilson** [comment]
Funcionou perfeitamente obrigado!
