### ISSUE TITLE
Cadastro desabilitado com bug

### ISSUE THREAD

**Issue by nuevox** [canove/whaticket#114]
Bom dia,

Mesmo estando desabilitado o cadastro de usuários, o sistema está permitindo o registro de novos usuários.

**Comment by canove** [comment]
Bom dia. Tentei reproduzir na versão [demo](https://whaticket.economicros.com.br/) e ele bloqueou corretamente. 

Sua instalação está atualizada?

**Comment by dmonteirosouza** [comment]
O meu também, atualizei hoje de manhã, e quando tento fazer um cadastro, aparece uma mensagem de erro dizendo que não é permitido e quando atualizo a página, aparece eu logado no usuário admin

**Comment by dmonteirosouza** [comment]
> Bom dia. Tentei reproduzir na versão [demo](https://whaticket.economicros.com.br/) e ele bloqueou corretamente.
> 
> Sua instalação está atualizada?

cliquei no link acima, e já entrei logado como cassio, sem fazer o login.

**Comment by canove** [comment]
Consegui reproduzir. Vou verificar

**Comment by canove** [comment]
Pode esta relacionado com essa https://github.com/canove/whaticket/issues/106https://github.com/canove/whaticket/issues/106
Se positivo, deve estar resolvido. 

Podem testar, por favor?

**Comment by nuevox** [comment]
> 
> 
> Pode esta relacionado com essa #106
> Se positivo, deve estar resolvido.
> 
> Podem testar, por favor?

Pra mim funcionou. Agora aparece SESSÃO EXPIRADA. Seria legal futuramente quando desabilitar a função de cadastro de usuário sumir o link de cadastre-se lá no login.
