### ISSUE TITLE
Reply of the contact in message with image

### ISSUE THREAD

**Issue by wagnerfillio** [canove/whaticket#117]
If a contact responds to the message itself containing an image, the new message must be as a reply, but the application exists as a new message.

**Smartphone:**
![image](https://user-images.githubusercontent.com/22008303/104760662-6e995c80-5740-11eb-821b-3de89c4ec5e7.png)

**Application**
![image](https://user-images.githubusercontent.com/22008303/104760675-8375f000-5740-11eb-8385-3fa3cf6eb9a6.png)

**Comment by canove** [comment]
Oi @wagnerfillio.

A mensagem original que foi respondida está no Whaticket? Se não estiver, ele não consegue mostrar como resposta no frontend.

**Comment by wagnerfillio** [comment]
Realmente, a mensagem original não estava no Whaticket e eu não sabia que precisaria esta.

Obrigado!!
