### ISSUE TITLE
not showing the menu option with the queues

### ISSUE THREAD

**Issue by srgoogle23** [canove/whaticket#118]
test in the demo of https://whaticket.economicros.com.br and see it, it isnt like the tuto

**Comment by canove** [comment]
You need to assign queues to user first:
![image](https://user-images.githubusercontent.com/24817866/104768476-82e35680-574c-11eb-869b-e9839904a8e2.png)

**Comment by srgoogle23** [comment]
i did that
its the same error of https://github.com/canove/whaticket/issues/125
so its valid

**Comment by canove** [comment]
@srgoogle23 , see my answer on https://github.com/canove/whaticket/issues/125, it should work. If don't, feel free to reopen this.
