### ISSUE TITLE
bot not delivered to recipient

### ISSUE THREAD

**Issue by swalayan-hasbuna** [canove/whaticket#125]
why the automatic queue message/ bot not delivered to recipient? how to activate that? thanks...

**Comment by swalayan-hasbuna** [comment]
https://user-images.githubusercontent.com/74512439/105092846-5e80d480-5ad4-11eb-9bd5-bef1df5797fd.mp4

**Comment by canove** [comment]
By design, the auto reply will only work on connections that have 2 or more queues attached to it and only on tickets that **doesn't** have a queue yet. Once a ticket is already on queue (as your case), the system will not send automatic messages anymore.
