### ISSUE TITLE
user.queues is undefined e aplicação não permite sair do sistema

### ISSUE THREAD

**Issue by wagnerfillio** [canove/whaticket#127]
Não sei por qual motivo, embora funcione bem, hora ou outra recebo o erro abaixo:

![image](https://user-images.githubusercontent.com/22008303/105406736-98a0c200-5c0b-11eb-9164-8289dcd6926a.png)

Outro problema é que, quando clico em sair, recebo o erro abaixo:

![image](https://user-images.githubusercontent.com/22008303/105406898-cf76d800-5c0b-11eb-8550-e72df8a5eb0f.png)

**Comment by wagnerfillio** [comment]
Pode me ajudar ?

**Comment by srgoogle23** [comment]
limpa o cache do seu navegador ou tentar entrar novamente na guia anonima e simular o erro novamente
aguardo seu retorno
