### ISSUE TITLE
Hospedagem com HTTPS ( Apache ) 

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [canove/whaticket#128]
Apache Reverse Proxy and localhost - “Mixed content, the content must be served over HTTPS”

Toda essa configuração funciona em HTTP , mas se ativo o HTTPS trocando BACKEND_URL e FRONTEND_URL para https, recebo a seguinte mensagem de Erro no Console do Navegador : 

![image](https://user-images.githubusercontent.com/1152426/106522039-de884080-64bd-11eb-9200-989a2a3da142.png)

Configuração do Backend ( .env ) : 

NODE_ENV=
BACKEND_URL=http://suporte.XXX.com.br
FRONTEND_URL=http://suporte.XXX.com.br
PROXY_PORT=8080
PORT=8080

DB_DIALECT=mysql
DB_HOST=localhost
DB_USER=suporte
DB_PASS=suporte
DB_NAME=suporte

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756

Configuração do Proxy no Apache : 

<VirtualHost *:80>
    ServerName suporte.XXX.com.br
    ProxyPreserveHost on
    ProxyPass / http://localhost:3000/
#RewriteEngine on
#RewriteCond %{SERVER_NAME} =suporte.XXX.com.br
#RewriteRule ^ https://%{SERVER_NAME}%{REQUEST_URI} [END,NE,R=permanent]
</VirtualHost>

**Comment by srgoogle23** [comment]
nao usa via apache, usa pelo nginx mesmo, é top
porque dai, por exemplo, voce aponta os dois subdominios para o ip da vps na cloudflare, instala o nginx e redireciona ele para as portas
ele ja vai passar com https 443 automatico

**Comment by canove** [comment]
Acho que se você trocar o BACKEND_URL e FRONTEND_URL para usar HTTPS, deve funcionar normalmente. Caso contrário, vai de nginx mesmo :)
