### ISSUE TITLE
Tickets

### ISSUE THREAD

**Issue by eserjpeg** [canove/whaticket#129]
Hello, how can i disable to ticket-system.
And, how can i enable to chat-system.

I want to disable the ticket system and only chat.
For example:
If my customer writes again after meeting with my customers and closing the conversation, I want to open them so that I can see the old messages over the same chat.

**Comment by srgoogle23** [comment]
its not possible yet, we havent this feature for now, but thx for the ideia

**Comment by canove** [comment]
Hi @eserjpeg. By default, the old ticket is open if it was close within 2 hours. You can change it on `backend/src/services/TicketServices/FindOrCreateTicketService.tsbackend/src/services/TicketServices/FindOrCreateTicketService.ts`
line  47

**Comment by eserjpeg** [comment]
this setting did not work
Note: I did 2000 instead of 2

**Comment by esteves67** [comment]
@eserjpeg Lol it works for me. Just comment out the 50 to 52 and it will always retrieve the same conversation, so it will not open a new ticket instead it will pick always the same ticket.

```js
  } else {
    ticket = await Ticket.findOne({
      where: {
        // updatedAt: {
        //   [Op.between]: [+subHours(new Date(), 2), +new Date()]
        // },
        contactId: contact.id
      },
      order: [["updatedAt", "DESC"]],
      include: ["contact"]
    });
    ```

**Comment by esteves67** [comment]
@eserjpeg Lol it works for me. Just comment out the line 50 to 52 and it will always retrieve the same conversation, so it will not open a new ticket instead it will pick always the same ticket.

```js
  } else {
    ticket = await Ticket.findOne({
      where: {
        // updatedAt: {
        //   [Op.between]: [+subHours(new Date(), 2), +new Date()]
        // },
        contactId: contact.id
      },
      order: [["updatedAt", "DESC"]],
      include: ["contact"]
    });

**Comment by eserjpeg** [comment]
It didn't work, why won't it work I'll go crazy!

> @eserjpeg Lol it works for me. Just comment out the line 50 to 52 and it will always retrieve the same conversation, so it will not open a new ticket instead it will pick always the same ticket.
> 
> ```js
>   } else {
>     ticket = await Ticket.findOne({
>       where: {
>         // updatedAt: {
>         //   [Op.between]: [+subHours(new Date(), 2), +new Date()]
>         // },
>         contactId: contact.id
>       },
>       order: [["updatedAt", "DESC"]],
>       include: ["contact"]
>     });
> ```

**Comment by canove** [comment]
@eserjpeg. Did you deleted "dist" folder and rebuild the app after doing this changes?

**Comment by eserjpeg** [comment]
I am sorry this is my mistake. i don't rebuild.


Thanks for all!

**Comment by Jolu54** [comment]
How do I rebuild ?
