### ISSUE TITLE
Erro preview image

### ISSUE THREAD

**Issue by marlon33** [canove/whaticket#13]
I have this erro in preview theimg whem i send or recive, the link is that:
undefined:undefined/public/1599703840204.jpg
the link that right : IP or DOMAIN:PORT/public/1599703840204.jpg

![image](https://user-images.githubusercontent.com/41172965/92743380-df75d580-f356-11ea-9917-13fa3d133798.png)

**Comment by canove** [comment]
Hi Marlon! This is defined in a .env file on yours backend folder. In newer version, this .env changed a little. If you are running development version (without nginx reserve proxy configuration) it must look like this: 
```
NODE_ENV=DEVELOPMENT
BACKEND_URL=http://localhost   
PROXY_PORT=8080       
PORT=8080

DB_HOST=localhost
DB_USER=
DB_PASS=
DB_NAME=
```

**Comment by esteves67** [comment]
> I have this erro in preview theimg whem i send or recive, the link is that:
> undefined:undefined/public/1599703840204.jpg
> the link that right : IP or DOMAIN:PORT/public/1599703840204.jpg
> 
> ![image](https://user-images.githubusercontent.com/41172965/92743380-df75d580-f356-11ea-9917-13fa3d133798.png)

If, @canove tip/answer didn't solve your issue, try to set both backend and frontend .env as the real ip (public ip), example http://111.11.11.11, instead of http://localhost.

**Comment by esteves67** [comment]
@marlon33 
If the above tip/answer didn't solve your issue, 
try to set both backend and frontend .env as the real ip (public ip), example http://111.11.11.11, instead of http://localhost.

**Comment by esteves67** [comment]
@marlon33 
If the above tip/answer didn't solve your issue, 
try to set both backend and frontend .env url as the real ip (public ip), example http://111.11.11.11, instead of http://localhost.
And tell us what solved your issue, so others can see this issue and get the answer too.

**Comment by esteves67** [comment]
@marlon33 How is it going so far? Did you solved your error? :+1:

**Comment by esteves67** [comment]
@marlon33 How is it going so far? Did you solved your error? Update us with how are you going with the error, so people can help you :smile:

**Comment by somyoshi** [comment]
> @marlon33 How is it going so far? Did you solved your error? Update us with how are you going with the error, so people can help you 😄

just write this line: 
PROXY_PORT=8181

remember you need to have SSL.
