### ISSUE TITLE
Importação de conversas

### ISSUE THREAD

**Issue by nuevox** [canove/whaticket#133]
Seria interessante a importação das conversas do telefone. Alguém conseguiu fazer essa importação por meio de algum script?

**Comment by gabrielromanosec** [comment]
Eu peguei o whatsapp-web.js fiz um fetch message lá baseada na conversa e injetei no sql do whaticket.

**Comment by KatiaSishost** [comment]
> Eu peguei o whatsapp-web.js fiz um fetch message lá baseada na conversa e injetei no sql do whaticket.

u have the code?
