### ISSUE TITLE
Erro Login

### ISSUE THREAD

**Issue by NickSilva38** [canove/whaticket#135]
Srs desculpe! Eu segui o tutorial de instalação e aparentemente foi tudo ok, porem não consigo fazer cadastro ou login, recebo mensagem ocorreu um erro
![image](https://user-images.githubusercontent.com/78949188/107736750-91884380-6ce1-11eb-9b58-6f0806ccbb7e.png)

**Comment by srgoogle23** [comment]
mostra o log de error do console do seu navegador

**Comment by NickSilva38** [comment]
Opa amigo, obrigado por responder, envio os logs

![image](https://user-images.githubusercontent.com/78949188/107999629-9f321780-6fc6-11eb-942a-f64193a0cf44.png)

**Comment by NickSilva38** [comment]
Opa amigo, obrigado por responder, segue os logs

![image](https://user-images.githubusercontent.com/78949188/108000061-cb01cd00-6fc7-11eb-9e84-d5b697d3be36.png)

**Comment by gabrielromanosec** [comment]
Aparentemente seu servidor backend está sem certificado ssl.

**Comment by canove** [comment]
@NickSilva38, remove o comentário do seu arquivo .env, acho que pode ser isso!

**Comment by NickSilva38** [comment]
Opa pessoal muito obrigado, vou executar e retorno!

**Comment by NickSilva38** [comment]
Retirei os comentários e agora esta funcionando perfeitamente! Muito Obrigado!
