### ISSUE TITLE
Hospedagem

### ISSUE THREAD

**Issue by wagnerfillio** [canove/whaticket#139]
É possivel hospedar o backend em algum serviço de hospedagem?
Pergunto por causa do puppeteer.

A Umbler por exemplo, não tem suporte ao puppeteer.

Sendo assim, oque se pode fazer para que eu consiga acessar o backend por fora ou via subdominio ?

**Comment by esteves67** [comment]
@wagnerfillio Acho muito difícil algum serviço de hospedagem aceitar o whaticket ou sequer o whatsapp-web.js, principalmente hospedagens brasileiras que são super restritas e limitadas, o mais fácil seria uma VPS devido à necessidade do acesso root.

**Comment by wagnerfillio** [comment]
@esteves67 Obrigado por retornar. Suponhamos que eu hospede o frontend em um serviço de hospedagem qualquer, eu conseguiria apontar as rotas do frontend para as rotas do backend nesta VPS?

Eu tenho um domínio na minha empresa e não queria deixar a aplicação em localhost.

**Comment by esteves67** [comment]
@wagnerfillio O que eu faço atualmente (não sei se é o correto) é da seguinte forma, tenho uma hospedagem compartilhada que só roda meu site (não tenho acesso root nela), e tenho uma vps que roda meu whaticket (tenho acesso root total nela), portanto são 2 IP's diferentes, eu vou no meu site e crio um sub-domínio (do tipo CNAME ou A)(exemplo: atendimento.meusite.com.br) e aponto esse sub-domínio para meu VPS onde está rodando tanto a frontend quanto backend, aí quando eu entro no endereço atendimento.meusite.com.br que é da minha hospedagem compartilhada ele acessa o Whaticket (backend e frontend) que está no VPS.

![img-5---como-criar-um-subdominio-1600714147422_764x316](https://user-images.githubusercontent.com/18627611/108613612-7056df80-73d2-11eb-8fe3-91857d5b348c.png)
![img-6---como-criar-um-subdominio-1600714185565_764x312](https://user-images.githubusercontent.com/18627611/108613617-7351d000-73d2-11eb-9df7-62da7dd704de.png)

**Comment by wagnerfillio** [comment]
@esteves67 , pode me chamar? Vou tentar fazer, mas se não conseguir gostaria da sua ajuda, posso lhe pagar por isso!
31 9 9688-3193 whats
