### ISSUE TITLE
Falha ao adicionar/editar contato se houver mais de uma conexão e uma delas estiver desconectada

### ISSUE THREAD

**Issue by wagnerfillio** [canove/whaticket#140]
Olá,
Percebi uma falha ao adicionar/editar contato ou fazer qualquer outra coisa se houver mais de uma conexão e uma delas estiver desconectada.

Pois recebo uma mensagem para verificar a conexão, mesmo que o contato editado, faça parte de uma fila, cuja conexão esteja ativa.

Agora, se todas as conexões estiverem ligadas, consigo alterar normalmente!

**Comment by canove** [comment]
Olá, @wagnerfillio. A função de importar / adicionar contatos usa a conexão que estiver marcada como padrão. Pode ser por isso que você está recebendo o erro.

Caso não seja, fique a vontade para reabrir a issue.

Abreço

**Comment by wagnerfillio** [comment]
Olá @canove percebi isso hoje, a conexão marcada como padrão precisa estar ativa!

Obrigado pelo retorno!

**Comment by Gelson34** [comment]
esse problema aqui ainda continua, mesmo com as informações a cima

**Comment by Afigreja71** [comment]
Olá pessoal,
minha instancia não recebe as mensagens na caixa de entrada. Percebi que o cadastro de novos contatos está dando mensagem de erro na barra de atenção "internal server error".
Penso que o fato de não entrar a chamada possa estar ligado ao erro na criação do contato.
Alguem já passou por isto?

Obrigado.
