### ISSUE TITLE
QR code error

### ISSUE THREAD

**Issue by Cyrizx** [canove/whaticket#141]
a dependency on whatsapp web was updated so it does not allow whaticket to connect the phone 
![imagen](https://user-images.githubusercontent.com/30956595/109158171-c8cf0980-7751-11eb-9bc5-44f16a8c516d.png)

**Comment by nestordavalos** [comment]
update to the latest version of whatsapp-web.js to 1.12.5 and run npm update, and then run your ./updateWhaticket, ready everything normal again

**Comment by eduamaral23** [comment]
Updated both puppeteer & @pedrolopez

**Comment by canove** [comment]
It should work with last version. In case you want just update the lib, just run `npm install whatsapp-web.js@latest` on backend folder.

After that, delete dist folder and build it again.
