### ISSUE TITLE
Tickets em conflito

### ISSUE THREAD

**Issue by luancyrne** [canove/whaticket#142]
Atualmente tenho 4 números de WhatsApp vinculados ao sistema, sendo 1 especificamente ao setor suporte e 2 sendo para o setor financeiro, e 1 único numero para todos os setores para que sejam encaminhados. O problema que me deparei e que quando algum ticket é aberto em um destes setores por exemplo, caso o mesmo número entre em contato com outro setor, ao invés de gerar um novo ticket o sistema utiliza o mesmo, independente se ainda esta ou não fechado o ticket. Teria alguma maneira que eu possa alterar nos códigos para gerar tickets individuais caso 1 mesmo numero entre em contato com setor individualmente (Setores diferentes ao mesmo tempo)?.   Obs:(Não sei se ficou claro)

**Comment by eserjpeg** [comment]
Sim, você pode usar 4 sistemas diferentes para isso, temos 2 números e usamos 2 sistemas diferentes.

**Comment by luancyrne** [comment]
> Sim, você pode usar 4 sistemas diferentes para isso, temos 2 números e usamos 2 sistemas diferentes.

Neste caso, para manter interligados os setores com outro sistema como esta sendo feito?
No caso de alguém chamar em um numero principal por exemplo, como ira transmitir as mensagens para um sistema ou servidor diferente?
