### ISSUE TITLE
how to install via centos 8 ? 

### ISSUE THREAD

**Issue by mzayn** [canove/whaticket#144]
can help how to full installation this package via centos ? 

cause i already have MySQL 10.4.12-MariaDB, apache. 

so can i run this code for that already installed ?

**Comment by swalayan-hasbuna** [comment]
is the way to install it different from ubuntu? I think the same ..

**Comment by mzayn** [comment]
> is the way to install it different from ubuntu? I think the same ..

im getting error when installing Create Mysql Database using docker .. 

effect with mysql ? 

---

and when install sudo apt-get install -y libgbm-dev wget unzip fontconfig locales gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils

getting error to. 

also i can't install ngix cause apache was been installed. 
-

have other option.

**Comment by mzayn** [comment]
i found this error again 

`npm install
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.

added 1613 packages, removed 735 packages, changed 251 packages, and audited 1884 packages in 2m

81 packages are looking for funding
  run `npm fund` for details`

that be ok or need to be audit fix  ?
