### ISSUE TITLE
Error sending video

### ISSUE THREAD

**Issue by alanflorencio** [canove/whaticket#145]
I installed Whaticket in 2 different environments. Audio, photos, documents ... It's working smoothly. More when we send video we received error 400 (Bad Request)

Tthe api is updated, everything is ok. Has anyone caught this error?

**Comment by swalayan-hasbuna** [comment]
yes same... how to update api?

**Comment by canove** [comment]
Hello! 

By default, this project install chromium to connect to whatsappweb. To be able to send videos, you need to install Chrome manually and add an additional ENV variable to on backend's .env file, containing the path to chrome binary.

`CHROME_BIN=/usr/bin/google-chrome`

**Comment by swalayan-hasbuna** [comment]
ok.. let i try it


Pada tanggal Sel, 2 Mar 2021 pukul 18.58 Cassio Santos <
notifications@github.com> menulis:
