### ISSUE TITLE
Não carrega imagens e audios

### ISSUE THREAD

**Issue by warquia** [canove/whaticket#149]
Bom dia, o Whaticket não está conseguindo carregar as imagens e audios recebidos, tem alguma cofiguação que devo fazer?
observei que no servidor está aparecendo a mensagem "message: "Invalid token. We'll try to assign a new one on next request"
    statusCode: 403" tem alguma referencia a isso?

**Comment by crvroberto** [comment]
Olá, passei por isso um tempo atrás, se não me engano é nas configurações no .env
Poderia postar elas aqui?

**Comment by warquia** [comment]
> Olá, passei por isso um tempo atrás, se não me engano é nas configurações no .env
> Poderia postar elas aqui?

Bom dia obrigado pela ajuda!
**Backend:**
`NODE_ENV=
BACKEND_URL=http://111.4.223.57
FRONTEND_URL=http://111.4.223.57:3000
PROXY_PORT=
PORT=8080
DB_DIALECT=
DB_HOST=localhost
DB_USER=root
DB_PASS=
DB_NAME=whatsappnew
JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756
IO_REDIS_SERVER=
IO_REDIS_PORT=
`
**Frontend**
`REACT_APP_BACKEND_URL = http://111.4.223.57:8080/
`

Alguma coisa estranha nessa configuração?

**Comment by crvroberto** [comment]
está correta as configurações, então o que pode estar ocasionando isso poderá ser os terminais de sem a função administrador ativada.
fiz um teste aqui executando o npm start no back e front pelo cmd normal, e dá esse mesmo problema de não carregar os arquivos, já quando executo pelo vs code que está como administrador funciona.
Talvez seja isso!

**Comment by warquia** [comment]
Observei que no PROXY_PORT= estava vazio. então coloquei 8080 e reiniciei o servidor e tudo voltou a funcionar,, obrigado pela força

**Comment by warquia** [comment]
Obrigado pela força
