### ISSUE TITLE
running backend and frontend at local ip only

### ISSUE THREAD

**Issue by the-jojo-jj** [canove/whaticket#150]
Hi, 
Somebody manage to run backend and frontend at the ip local only?

thanks.

**Comment by esteves67** [comment]
> Hi,
> Somebody manage to run backend and frontend at the ip local only?
> 
> thanks.

Yes you can run Whaticket locally (i run both frontend and backend in the same machine), i have mine set as:

```
backend
NODE_ENV=DEVELOPMENT
BACKEND_URL=http://192.168.100.50
FRONTEND_URL=http://192.168.100.50:5555
PROXY_PORT=8085
PORT=8085

frontend
REACT_APP_BACKEND_URL = http://192.168.100.50:8085/
```

**Comment by the-jojo-jj** [comment]
Hi @esteves67, 
thanks for your reply.

I mean, can we bind spesific ip address? 
i have local and public ip in the vps, and i just want to bind to ip local.

thanks.
