### ISSUE TITLE
Change port 3000

### ISSUE THREAD

**Issue by Soberano0** [canove/whaticket#153]
I'm trying in several ways to change port 3000, but to no avail, does anyone know how to do this?

**Comment by Soberano0** [comment]
Resolvi, só adicionar na frente do start a porta no meu caso 3010:
  "scripts": {
    "start": "PORT=3010 react-scripts start",

**Comment by esteves67** [comment]
If your problem is solved, please close the ticket, thank you :pray:

**Comment by esteves67** [comment]
If your problem is solved, please close the issue, thank you :pray:
