### ISSUE TITLE
Tickets não estão sendo encerrados

### ISSUE THREAD

**Issue by luancyrne** [canove/whaticket#154]
Assim que um usuário entra em contato, por mais que seja encerrado o ticket, caso o usuário retorne contato o mesmo ticket esta sendo reaberto, esta falha causa conflito entre múltiplos setores e números, deixando um atendimento perdido entre as conversas e muita das vezes por mais que o usuário entre em contato novamente não e recebido

**Comment by ricardojlrufino** [comment]
Pelo que vi existe uma regra de 2h, ele associa para o mesmo ticket.

**Comment by esteves67** [comment]
@luancyrne Como o @ricardojlrufino tem essa regra de 2h mesmo.
Para alterar é só editar o arquivo `backend/src/services/TicketServices/FindOrCreateTicketService.ts`,
nas linhas:

```js
  if (!ticket && !groupContact) {
    ticket = await Ticket.findOne({
      where: {
        updatedAt: {
          [Op.between]: [+subHours(new Date(), 2), +new Date()]
        },
        contactId: contact.id
      },
      order: [["updatedAt", "DESC"]]
    });
  ```

**Comment by luancyrne** [comment]
@ricardojlrufino @esteves67, agradeço a ambos pela dica e pelo auxílio, fico grato pela ajuda.
