### ISSUE TITLE
Adicionar Mensagem: Finalização do atendimento, Mensagem de ausência e Repostas rápidas.

### ISSUE THREAD

**Issue by patriciosilvadev** [canove/whaticket#155]
Olá Pessoal, alguém já conseguir implementar as mensagens de finalização do atendimento com protocolo, mensagem de ausência definida pelo usuário e aquelas repostas rápidas do dia-a-dia?

**Exemplos:**

**Mensagem de Atendimento Inicial:** Saudação: (**Olá, Bom dia, Boa tarde ou Boa noite**) **'$contact.name'**, você está no auto atendimento do ***Whaticket***, seu protocolo de atendimento é **'$datadoatendimento+ticket.id'**.
Escolha uns dos menus ou setores abaixo para ser atendido!

**ou**

Olá!, aguarde um momento, logo você será atendido.

O tempo médio de espera por meio do Wattsapp é de 30 minutos. Em caso de urgência ligue para um de nossos telefones de contato.

(00) 00000-0000 ou (11) 11111-1111

Protocolo: 20210311221901.

Em qualquer momento, digite #sair para sair do atendimento.

**Mensagem de Ausência:** Saudação: (**Olá, Bom dia, Boa tarde ou Boa noite**) **'$contact.name'**,  no momento não estamos disponível, nosso horário de atendimento é de seg. a sex. das 8h as 18h.

**Mensagem de Finalização do Atendimento:** Atendimento finalizado com sucesso. Segue seu protocolo: **20210311221901**.

**Mensagem de Repostas Rápidas:** adicionar um botão para cadastrar as repostas rápidas exemplo: **Olá, em que posso ajudar?**,

**seu atendimento será finalizado por tempo de inatividade**.

Seu alguém já conseguiu fazer e puder compartilhar, pq estou apanhando para aprender essa nova linguagem de programação.

**Comment by rodrigojunes** [comment]
Ola Patricio me chama no email rodrigo_junes@hotmail.com para que possamos trocar ideias sobre esse assunto desde ja obrigado

**Comment by maxivane** [comment]
Seria interessante...

**Comment by renatofb** [comment]
Muito importante na verdade
