### ISSUE TITLE
Multiple Socket.io connections for same user 

### ISSUE THREAD

**Issue by ricardojlrufino** [canove/whaticket#156]
Watching in chrome network, i see multiple open websocket connections, this is intentional (by design ?), or is a bug ?!

![image](https://user-images.githubusercontent.com/515675/111044028-de685280-8424-11eb-8db3-c53c9396ef5e.png)

![image](https://user-images.githubusercontent.com/515675/111044031-e0caac80-8424-11eb-8870-ac8f5b2081f7.png)

**Comment by luancyrne** [comment]
> Watching in chrome network, i see multiple open websocket connections, this is intentional (by design ?), or is a bug ?!
> 
> ![image](https://user-images.githubusercontent.com/515675/111044028-de685280-8424-11eb-8db3-c53c9396ef5e.png)
> 
> ![image](https://user-images.githubusercontent.com/515675/111044031-e0caac80-8424-11eb-8870-ac8f5b2081f7.png)


By default, the socket will always look for connections between the frontend and the backend, usually it opens from 4 to 5 connections and after it re-establishes, takes the necessary information and closes the connection, the same process is repeated for each tab, be it users, tickets or other information, all of them are going to the backend as well as the frontend itself through the socket, so if you analyze yourself in the last connection made, you will receive information objects that were sent through the server side socket, so don't worry

**Comment by ricardojlrufino** [comment]
ok thanks
