### ISSUE TITLE
É possível alterar o título das páginas?

### ISSUE THREAD

**Issue by guiqis** [canove/whaticket#158]
Tem como alterar o nome 'WhaTicket' no título das páginas e na barra de menu para algum personalizado?

**Comment by bootsoftware** [comment]
Boa noite, e sim, só pesquisar por  'WhaTicket'  e mudar nos 2 arquivos.   :)

**Comment by guiqis** [comment]
> Boa noite, e sim, só pesquisar por 'WhaTicket' e mudar nos 2 arquivos. :)

Então, eu pesquisei e mudei o nome dentro de /frontend/public (ndex.html e manifest.json), porém continua com o nome antigo. É em algum outro arquivo, ou preciso reiniciar algo?

**Comment by bootsoftware** [comment]
reiniciou servidor e front?

**Comment by guiqis** [comment]
> reiniciou servidor e front?

Reiniciei o servidor apenas. Como faço no front?

**Comment by luancyrne** [comment]
> > reiniciou servidor e front?
> 
> Reiniciei o servidor apenas. Como faço no front?

Depois de alterar quaisquer modificações no front você deve recompilar usando npm run build, assim ele ira gerar uma nova compilação com alterações e arquivos modificados.

**Comment by guiqis** [comment]
> > > reiniciou servidor e front?
> > 
> > 
> > Reiniciei o servidor apenas. Como faço no front?
> 
> Depois de alterar quaisquer modificações no front você deve recompilar usando npm run build, assim ele ira gerar uma nova compilação com alterações e arquivos modificados.

Sucesso!! Muito obrigado

**Comment by esteves67** [comment]
Depois quando tiver um tempo encerra o issue por favor só pra não ficar aberto porque já foi resolvido. :fist_right: :fist_left:
