### ISSUE TITLE
AUTHENTICATION FAILURE! ERROR: Error starting whatsapp session. Backend

### ISSUE THREAD

**Issue by xmariodiaz** [canove/whaticket#159]
hi,
has anyone know how to solve this issue?
this happens when the cellphone for some reason gets disconnected from Internet for few seconds or the phone goes in the sleep mode.
is there anyway to re-start the whatsapp service  automatically again?? because usually I have to stop the backend and start it again and that's enough, but when it is running in the server is kinda annoying the whole process. it's not very often but happens once in a while.
![Capture](https://user-images.githubusercontent.com/46854726/111837801-6b4c5980-88c6-11eb-8edd-22680009d8ee.PNG)

**Comment by esteves67** [comment]
@xmariodiaz From what i can see by your timestamp 1616174431334, you were using whatsapp by the time their servers went down at 03.19.2021 `theverge.com/2021/3/19/22340405/instagram-whatsapp-facebook-messenger-down-outage`

**Comment by xmariodiaz** [comment]
> @xmariodiaz From what i can see by your timestamp 1616174431334, you were using whatsapp by the time their servers went down at 03.19.2021 `theverge.com/2021/3/19/22340405/instagram-whatsapp-facebook-messenger-down-outage`

yes I know but it didnt re-connect when the service came back, whaticket just turned off with an error and stayed there up to I restarted the backend

**Comment by xmariodiaz** [comment]
so is there any way to re-try to connect without doing that manually?? I'm running a chat-bot in a modified version of Ticket, therefore I don't want it to stop where in the code I should to check?

**Comment by luancyrne** [comment]
> so is there any way to re-try to connect without doing that manually?? I'm running a chat-bot in a modified version of Ticket, therefore I don't want it to stop where in the code I should to check?


As esteves67 mentioned, possibly the reason for its disconnection was the fact that there was really a failure or drop in whatsapp services on the day in question, I currently use a server that is constantly connected and I have several connection problems with the device connected to it , however much he loses the constant connection the server remains connected to him
