### ISSUE TITLE
No QR code?

### ISSUE THREAD

**Issue by deepesh-agarwal** [canove/whaticket#16]
Added a new user but it's neither asking for QR code nor showing any option to trigger one?

![Screenshot at Sep 11 11-28-52](https://user-images.githubusercontent.com/3198004/92871040-2250af80-f422-11ea-86a9-de68cf3218d0.png)

**Comment by deepesh-agarwal** [comment]
Using `sudo sysctl -w kernel.unprivileged_userns_clone=1` fixes the issue.

**Comment by inforeis** [comment]
Hello, I ran the eating and it still didn't work. :(

**Comment by inforeis** [comment]
I didn't understand where for this configuration @deepesh-agarwal

**Comment by deepesh-agarwal** [comment]
@inforeis Execute this `sudo sysctl -w kernel.unprivileged_userns_clone=1` in command-line on the server.

**Comment by inforeis** [comment]
I ran and it didn't work.
Then, I checked the https://github.com/pedroslopez/whatsapp-web.js/issues/344 link and saw that you need to add the code snippet below as well. But, I didn't understand where to put it.

**Comment by inforeis** [comment]
<img width="648" alt="Captura de Tela 2020-09-12 às 10 28 11" src="https://user-images.githubusercontent.com/39631830/92996527-b5e9b500-f4e2-11ea-84c6-ab96715bf6b3.png">

**Comment by deepesh-agarwal** [comment]
@inforeis Try this then - https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md#alternative-setup-setuid-sandbox

**Comment by canove** [comment]
Take a look at

> I ran and it didn't work.
> Then, I checked the [pedroslopez/whatsapp-web.js#344](https://github.com/pedroslopez/whatsapp-web.js/issues/344) link and saw that you need to add the code snippet below as well. But, I didn't understand where to put it.

Take a look at: https://github.com/canove/whaticket/issues/6

**Comment by esteves67** [comment]
> I didn't understand where for this configuration @deepesh-agarwal

@inforeis 

Put this code bellow in the `backend/src/libs/wbot.js`:

Before the `wbot.initialize();`, you add:

`wbot = new Client({ puppeteer: {headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox']}, session: sessionCfg });`

So the final result will be:

```
		wbot = new Client({ puppeteer: {headless: true, args: ['--no-sandbox', '--disable-setuid-sandbox']}, session: sessionCfg });
		wbot.initialize();
```
