### ISSUE TITLE
[ERROR] Cadastro do primeiro login

### ISSUE THREAD

**Issue by renat473** [canove/whaticket#166]
Olá,

se encontra com erro na hora de cadastrar o primeiro login, nos arquivos .env coloquei os ip da minha máquina e mesmo assim o erro continua.

`[HMR] Waiting for update signal from WDS... 2xhr.js:177 `

**Comment by canove** [comment]
Bom dia!

Posta seus arquivos .env pra gente dar uma olhada ;)

**Comment by renat473** [comment]
Olá

O único .env que deve ser criado e o do backend ou o frontend também precisa 

NODE_ENV=DEVELOPMENT      
BACKEND_URL=http://192.168.1.11/
FRONTEND_URL=https://192.168.11:3000
PROXY_PORT=8080
PORT=8080

DB_HOST= 172.17.0.2
DB_DIALECT=
DB_USER=whaticket
DB_PASS=whaticket
DB_NAME=whaticket

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756

**Comment by renat473** [comment]
REACT_APP_BACKEND_URL = http://192.168.1.11:3000

**Comment by inaciomsn2015** [comment]
Conseguiu resolver seu Problema? aqui também estou com erro no cadastro do primeiro login!

**Comment by srgoogle23** [comment]
fala mano, seu frontend ip ta errado, é com certeza erro do .env

**Comment by renat473** [comment]
@srgoogle23 , ele deveria apontar para qual IP ?

**Comment by renat473** [comment]
situação resolvida após correção dos IP nos arquivos .env e consegui realizar o cadastro do usuário.
