### ISSUE TITLE
Arquivo recebido pelo contato com o mesmo nome.

### ISSUE THREAD

**Issue by ertprs** [canove/whaticket#167]
Oie pessoal, estou tendo um problema com os arquivos em pdf, quando o contato me envia vários arquivos com o mesmo nome ele abre apenas o primeiro, exemplo abaixo:
O Contato João me enviada três Boletos para imprimir, só que os três estão com o mesmo nome ex: boleto, boleto e boleto.
Ele ignora os demais e abre apenas o primeiro que o João me enviou, não importa o dia e hora, ele abre apenas o primeiro desse contato.

Alguém já passou por esse problema?

Existe uma forma de está adicionando alguma coisa no backend para ele salvar os arquivos recebidos como o exemplo boleto-20210401.pdf igual ao exemplo do upload que foi sugerido pelo @esteves67 ?

**Segue o  exemplo da minha dúvida, essa é a tela do celular**:
![WhatsApp Image 2021-03-15 at 13 22 07](https://user-images.githubusercontent.com/62783690/113633338-2a34a300-9643-11eb-861e-6950bd5dddb2.jpeg)

**Esse é a tela pelo WhaTicket**:
![WhatsApp Image 2021-03-15 at 13 22 17](https://user-images.githubusercontent.com/62783690/113633341-2acd3980-9643-11eb-9a69-9ced3fe9992e.jpeg)

**Um vídeo de exemplo explicando minha duvida**:
https://user-images.githubusercontent.com/62783690/113633344-2b65d000-9643-11eb-8033-657e1ec6c635.mp4

**Comment by patriciosilvadev** [comment]
Pessoal alguém já passou por essa situação?

**Comment by patriciosilvadev** [comment]
@canove, Boa noite existe a possibilidade de está adicionando alguma regra no nome dos documento recebidos em pdf ou txt?

Tipo recebi um documento com o nome boleto.pdf gostaria de fazer um tratamento nesse recebimento, colocar alguma coisa a mais na frente do nome exemplo boleto-989327372.pdf alguma coisa para não duplicar o nome no recebimento.

Entendeu?

Me dar um help ai, quem tiver alguma ideia de fazer isso, por favor.

Desde já agradeço a todos.

**Comment by jjsquady** [comment]
Se ajudar eu fiz uma alteração no arquivo `wbotMessageListener` que segue para "resolver" esse problema de duplicidade de nomes.

```
/* Check if media not have a filename
  if (!media.filename) {
    const ext = media.mimetype.split("/")[1].split(";")[0];
    media.filename = `${new Date().getTime()}.${ext}`;
  }
*/
let originalFilename = media.filename ? `-${media.filename}` : ''
// Always write a random filename
const ext = media.mimetype.split("/")[1].split(";")[0];
media.filename = `${new Date().getTime()}${originalFilename}.${ext}`;
```

O que ocorre aqui é verificar se a `media` contem um `filename`, se sim `originalFilename` recebe o nome do arquivo prefixado com um hifen. Não havendo um `filename` o comportamento é o mesmo que o bloco **if** acima.

O resultado de `media.filename` agora é um **{timestamp}-{NOME_DO_ARQUIVO}.{extensão}**

A mudança ocorre da linha 76 até a linha 85.
;)

**Comment by patriciosilvadev** [comment]
> Se ajudar eu fiz uma alteração no arquivo `wbotMessageListener` que segue para "resolver" esse problema de duplicidade de nomes.
> 
> ```
> /* Check if media not have a filename
>   if (!media.filename) {
>     const ext = media.mimetype.split("/")[1].split(";")[0];
>     media.filename = `${new Date().getTime()}.${ext}`;
>   }
> */
> let originalFilename = media.filename ? `-${media.filename}` : ''
> // Always write a random filename
> const ext = media.mimetype.split("/")[1].split(";")[0];
> media.filename = `${new Date().getTime()}${originalFilename}.${ext}`;
> ```
> 
> O que ocorre aqui é verificar se a `media` contem um `filename`, se sim `originalFilename` recebe o nome do arquivo prefixado com um hifen. Não havendo um `filename` o comportamento é o mesmo que o bloco **if** acima.
> 
> O resultado de `media.filename` agora é um **{timestamp}-{NOME_DO_ARQUIVO}.{extensão}**
> 
> A mudança ocorre da linha 76 até a linha 85.
> ;)
Deu certo, obrigado pela dica, fiz as alterações conforme sua dica e resolveu meu problema aqui. Vlw

**Comment by ram0ng1** [comment]
Arquivos no formato .docx ou .xls ficam com uma extensão semelhante à ".docx.vnd.openxmlformats-officedocument.wordprocessingml.document" impossibilitando a abertura do arquivo.
