### ISSUE TITLE
Send msg like api

### ISSUE THREAD

**Issue by KatiaSishost** [canove/whaticket#169]
it's possible to send a message like api?

for example send message with html form containing numer and message

to domain.com:5000/sendmsj&num=5491122334455&msg=hello

how to? it's for send notifications.

**Comment by esteves67** [comment]
@KatiaSishost Yes it is possible since Whaticket uses Whatsapp-Web.JS and Express.

To send message's via an http post request to an url like your example, you just need to copy the code in that project https://github.com/gusfahmi/Whatsapp-API and paste it in Whaticket, like an integration.

I do use myself like that.

**Comment by KatiaSishost** [comment]
Ey Steves! hello! I was thinking of doing it that way, but I wasn't sure if the function was already implemented

Thanks you so much!

**Comment by ThunderBRZ** [comment]
I need this too...  i try copy to a backend folder, start a npm app but nothing...

any help?

**Comment by cesarra** [comment]
@KatiaSishost,

I've added the following lines at the end of file **backend/dist/libs/wbot.js** 

```
var http = require('http');
var url = require('url');

http.createServer(function (req, res) {
  //Parse do url para pegar o pathname e a querystring
  var q = url.parse(req.url, true);
  var query = q.query;
  //Utilizando a primeira sessao (sessions[0]) de cliente whatsapp ativa
  var wclient = sessions[0];
  if(q.pathname=="/send"){
	wclient.sendMessage(query.number, query.message);
	res.write('Mensagem Enviada!');
        res.end();
  }
}).listen(8081);

```

and now I can send messages with a GET request to the following address
domain.com:8081/send?number=XXXXXXXXXX&message=MYMESSAGE


I'm sure that is not the best/safe way to do that, but it is working

**Comment by Gecko2087** [comment]
> var http = require('http');
> var url = require('url');
> 
> http.createServer(function (req, res) {
>   //Parse do url para pegar o pathname e a querystring
>   var q = url.parse(req.url, true);
>   var query = q.query;
>   //Utilizando a primeira sessao (sessions[0]) de cliente whatsapp ativa
>   var wclient = sessions[0];
>   if(q.pathname=="/send"){
> 	wclient.sendMessage(query.number, query.message);
> 	res.write('Mensagem Enviada!');
>         res.end();
>   }
> }).listen(8081);

Thanks for the input.
Does it still work that way?
I did it as directed, but the test message never reaches me

**Comment by cesarra** [comment]
Hi,

Still working, but I dont have access to my code right now..
I've probably mistyped the code.. Try changing to:

`var http = require('http');
var url = require('url');

http.createServer(function (req, res) {
  //Parse do url para pegar o pathname e a querystring
  var q = url.parse(req.url, true);
  var query = q.query;
  //Utilizando a primeira sessao (sessions[0]) de cliente whatsapp ativa
  var wclient = sessions[0];
  if(q.pathname=="/send"){
	wclient.sendMessage(query.number+**'@c.us'**, query.message);
	res.write('Mensagem Enviada!');
        res.end();
  }
}).listen(8081);
`

Or use  wclient**.getNumberId(query.number)** to retrieve the correct Number
[](https://pedroslopez.me/whatsapp-web.js/Client.html#getNumberId)

**Comment by Gecko2087** [comment]
@esteves67 It would help me a lot if you could tell me how you implemented the api to whaticket.  Thank you

**Comment by esteves67** [comment]
> @esteves67 It would help me a lot if you could tell me how you implemented the api to whaticket. Thank you

Sorry for the late reply :disappointed: 

In the middle of:
```
  wbot.on("message_ack", async (msg, ack) => {
    handleMsgAck(msg, ack);
  });
```

And: 
```
};

export { wbotMessageListener, handleMessage };
```

You put that code bellow:
```
/* API WEBHOOK */
function makeid(length) {
   var result           = '';
   var characters       = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
   var charactersLength = characters.length;
   for ( var i = 0; i < length; i++ ) {
      result += characters.charAt(Math.floor(Math.random() * charactersLength));
   }
   return result;
}

app.post('/send', async (req, res)=>{

  let num = req.body.num;
  let msg = req.body.message;

  let numbers = Array();
  num.split(',').map((number)=>{ 
    numbers.push(number.trim()) 
  });  

  
  try{

      const success = Array();
      for(let i=0; i<numbers.length; i++){

        // let number = numbers[i]+'@c.us'; 
        let number = numbers[i]; 
        const data = await wbot.sendMessage(number, msg);

        if(data.ack === 0){
          success.push({success: true, number: numbers[i], detail: numbers[i] + ", Message status success"});
        }else{
          success.push({success: false, number: numbers[i], detail: numbers[i] + ", Message status failed"});
        }

      } 
    
      res.json({status: success})


  }catch(err){

    res.json({status: "error", detail: "Failed to send message, Please authenticate or scan generated barcode"});
 
  }
   
})

app.post('/sendMedia', async (req, res)=>{

  let fileUrl = req.body.file;
  let caption = req.body.message;
  let num = req.body.num; 

  let numbers = Array();
  num.split(',').map((number)=>{ 
    numbers.push(number.trim()) 
  }); 


 
  try{

    let request = await axios.get(fileUrl, {responseType: 'stream'});

    let cType = request.headers['content-type'];
    const fileExt = mime.extension(cType);

    let code = makeid(10).toUpperCase();
    const dirLoc = './public/'+code
    fs.mkdirSync(dirLoc);
    const fname = makeid(10).toUpperCase()+"."+fileExt;


    const dataUpload = request.data.pipe(fs.createWriteStream(dirLoc+'/'+fname));
    dataUpload.on('finish', async ()=>{
     
      const media = MessageMedia.fromFilePath(dirLoc+"/"+fname); 
      const success = Array();

      for(let i=0; i<numbers.length; i++){
        const data = await wbot.sendMessage(numbers[i]+'@c.us', media, {caption: caption}); 
        if(data.ack === 0){
          success.push({success: true, number: numbers[i], detail: numbers[i] + ", Message status success"});
        }else{
          success.push({success: false, number: numbers[i], detail: numbers[i] + ", Message status failed"});
        }
      }


      fs.unlinkSync(dirLoc+"/"+fname);
      fs.rmdirSync(dirLoc);

      res.json({status: success});
      res.end();

    })

  }catch(err){

    res.json({status: "error", details: "failed to check the URL!"});

  }

  
});


app.listen('3030');
/* API WEBHOOK */
```

And at the top of all your code you should have:

```
/* API WEBHOOK */
const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors'); 
const axios = require('axios');
const mime = require('mime-types');
const app = express();
app.use(cors());
app.use(bodyParser.json());
/* API WEBHOOK */
```

**Comment by bonanati** [comment]
Olá, alguém conseguiu fazer funcionar essa integração? copiei o codigo conforme @esteves67 informou e deu erro

**Comment by lisboadouglas** [comment]
> Olá, alguém conseguiu fazer funcionar essa integração? copiei o codigo conforme @esteves67 informou e deu erro

Você buildou o backend novamente e restartou os serviços.
Caso não funcione. 

Faça os procedimentos abaixo:

1. Abra o arquivo **wbot.js** localizado em backend/dist/libs/
2. Adicione o código abaixo no final do arquivo (após a Linha exports.removeWbot = removeWbot

> var http = require('http');
> var url = require('url');
> 
> http.createServer(function (req, res) {
>     //Parse do url para pegar o pathname e a querystring
>     var q = url.parse(req.url, true);
>     var query = q.query;
>     //Utilizando a primeira sessao (sessions[0]) de cliente whatsapp ativa
>     var wclient = sessions[0];
>     if(q.pathname=="/send"){
>         wclient.sendMessage(query.number+'@c.us', query.message);
>         res.write('Mensagem Enviada!');
>         res.end();
>     }
> }).listen(PortaDesejada);

Salve e reinicie o serviço backend.

Para enviar a mensagem:
http://ipoudomínio:porta/send?number=55DDNUMERO&message=Escreva a mensagem aqui

**Comment by bonanati** [comment]
Então.. não sei se estou certo, colo o código, após rodo o comando (npm run build) em backend, (pm2 restart 0 e 1) ...e quando entro no arquivo o código é removido. e não abre a porta que adicionei no codigo.

**Comment by lisboadouglas** [comment]
> Então.. não sei se estou certo, colo o código, após rodo o comando (npm run build) em backend, (pm2 restart 0 e 1) ...e quando entro no arquivo o código é removido. e não abre a porta que adicionei no codigo.

Se você estiver seguindo a minha dica, não roda o comando npm run build pois irá remover. Cola o código e da o restart.

**Comment by bonanati** [comment]
Top Parceiro, deu certo. vc é 10.. Obrigado pela ajuda

**Comment by bonanati** [comment]
Saberia me dizer se tem como enviar e abrir um ticket no whaticket? com essa mensagem

**Comment by lisboadouglas** [comment]
> Saberia me dizer se tem como enviar e abrir um ticket no whaticket? com essa mensagem

Assim que envia o whaticket já reconhece a mensagem e abre o ticket

**Comment by bonanati** [comment]
Realmente.. Show de bola.. Valeuuuu

**Comment by KatiaSishost** [comment]
Hello guys!! This work in only 1 whatsapp number.... but if i have 2 or 3 numbers?

**Comment by rodrigofsantos** [comment]
selecione a sessão !
