### ISSUE TITLE
How to predefine the port the frontend is going to use

### ISSUE THREAD

**Issue by ricco-douro** [canove/whaticket#170]
Hello, 

the front end opens the cliente on port 3000 by default (eg: http://localhost:3000), , unless that port is being used and he moves to the next available port.

Is there a way to predefine/configure the port to be used? 
This is specially important because the server has it port dinamically assigned but the NGINX proxy (or Apache in my case) is hardcoded

Thank you

**Comment by wirys** [comment]
A quick way for you to set the front end port and write this in the package.json file
```
 "scripts": {
    "start": "set PORT=3005 && react-scripts start",
```

**Comment by ricco-douro** [comment]
Thats really it, @wirys .

Thank you!!!!
