### ISSUE TITLE
How to send a msg from backend ??

### ISSUE THREAD

**Issue by xmariodiaz** [canove/whaticket#173]
Hi guys, I'm trying to send a notification msg to my personal number every time when the ticket meets some characteristics .
I used this function in older versions but now it's no longer available.
` const xsentMessage = await wbot.sendMessage('1234567890@c.us',"My message");`

Now I tried to send it through the API using the ticket number like this:
`
headers: { Authorization: 'Bearer XXXXXXXXX'};
 const xsentMessage = await axios.post('http://10.50.50.90:8080/messages/7',"my message body",config);
`
and it works but as soon as the token expires, it stops working.

How can I send my message in a easiest way??

**Comment by xmariodiaz** [comment]
I partially figured out , hard coded but...
in the module services/wbotservices/SendWhatsAppMessage.ts, I added this function:
```
...
...
/**
 * This function send a message to an specific WPnumber from the backend
 * @param num  whatsapp number
 * @param body message
 * @param tick  current ticket, it could be whatever
 */
async function sentMessagexxx (num:string,body:string, tick:Ticket){
  const wbot = await GetTicketWbot(tick); //just to let me use the function
  await wbot.sendMessage(num,body)
}

export { SendWhatsAppMessage, sentMessagexxx};
```

This is  to get the notification in my personal WhatsApp when someone text me to another number with Whaticket
```
// In the module wbotMessageListener.ts add
await sentMessagexxx("1234567890","New Ticket, check Whaticket !",ticket);
```

**Comment by KatiaSishost** [comment]
can post the file complete? i added the code in some position, and it no compile

**Comment by cesarra** [comment]
Hi!

Same problem here..

@xmariodiaz , can you please share the files?
