### ISSUE TITLE
Chatbot

### ISSUE THREAD

**Issue by Fleettelematicssystem** [canove/whaticket#179]
É possivel melhorar o chatbot?

Exemplo: quando a pessoa manda mensagem pela primeira vez, antes dela cair no menu para escolher a opção de atendimento... o robo fazer pergutas antes...

Recolher Nome da pessoa e gerar um protocolo?

**Comment by brenofebronio** [comment]
Amigo, você conseguiu algo ?

**Comment by Fleettelematicssystem** [comment]
Ainda não...

**Comment by mairaeloisa** [comment]
nada ainda?

**Comment by zieloribeiro** [comment]
nada ainda ...
