### ISSUE TITLE
[Bug] Mysterious chat?

### ISSUE THREAD

**Issue by deepesh-agarwal** [canove/whaticket#18]
Not sure how this chat (notice no messages) found its way in there, it's not on phone and web.whatsapp.com

![Screenshot at Sep 11 21-23-19](https://user-images.githubusercontent.com/3198004/92947088-2bb73780-f475-11ea-999c-83233da5c89f.png)

**Comment by esteves67** [comment]
@deepesh-agarwal I realized that this happens when the person turns his account from a personal account to a business account or vice versa, enter the chat of the 61479055390 number and you will see that this number has just turned his whatsapp account into a business account.

**Comment by esteves67** [comment]
@deepesh-agarwal I realized that this happens when the person (in this case **61479055390**)  turns his account from a personal account to a business account or vice versa. 
Please enter the chat of the **61479055390** number and check if that number has just turned his whatsapp account into a business account.

@canove We need to check in the backend console which event is generated when someone turn his account into a business account and ignore it in the `wbotMessageListener.js` file, in the section bellow:

```javascript
		if (
			msg.from === "status@broadcast" ||
			msg.type === "location" ||
			msg.type === "call_log" ||
			msg.author != null // Ignore Group Messages
		) {
			return;
```

**Comment by deepesh-agarwal** [comment]
That number is not in my chats or contacts? How a random number will trigger this on my whatsapp setup!!

**Comment by esteves67** [comment]
> That number is not in my chats or contacts? How a random number will trigger this on my whatsapp setup!!

Different than my problem then :confused: 
Weird how it triggered your Whaticket setup if you dont have that number in contact list :open_mouth:

**Comment by esteves67** [comment]
I just tested on my whatsapp and saw that there is a type of notification like 'status@broadcast', 'call_log', where it comes with message empty.

That empty balloon is some notification, i can't tell which notification it is, cuz there is plenty of notification types, like the one where it says in a Green Balloon "You are talking to a business account [...]", there is the one in a Yellow Balloon where it says "Messages and calls are end-to-end encrypted [...]".

For the yellow balloon where it says `Messages and calls are end-to-end encrypted. No one outside of this chat [...]` 
the type of it is `e2e_notification`.

The types are:
```
Array Filter messages by chat type
"text" "notification" "notification_template" "group_notification" "gp2" "broadcast_notification" "e2e_notification" "call_log" "protocol" "chat" "location" "payment" "vcard" "ciphertext" "multi_vcard" "revoked" "image" "video" "audio" "ptt" "sticker" "document" "unknown"
```
Source: console.wassenger.com/docs/#operation/getDeviceMessages


Here it is what is recognized by the backend by that Yellow Balloon.
```
2020.09.12, 22:03:24.0641 UTC -> 
From: cellphonenumber@c.us
Type: e2e_notification
Message: 
```

The Message in the Android Phone:
![empty-balloon-wp-2](https://user-images.githubusercontent.com/18627611/93005999-67153d00-f52d-11ea-9bf5-2a4e1bd2b3d9.jpeg)

The Message in the Whaticket Frontend Client:
![empty-balloon-wp-1](https://user-images.githubusercontent.com/18627611/93006011-76948600-f52d-11ea-88ae-fa6f1d015589.jpg)

**Comment by esteves67** [comment]
> That number is not in my chats or contacts? How a random number will trigger this on my whatsapp setup!!

I think since you added this number to your ticket list you are listening for all his messages, even if hes not in your contact list.

**Comment by esteves67** [comment]
@canove I identified the real issue in @deepesh-agarwal case.

Just because the ticket chat he's talking to doesn't have a properly name like **John Doe** and it is identified just by **61479055390**, doesn't mean he doesn't have this number in his contacts list like he said. It does mean that he doesn't synced his phone contacts to whaticket contacts tab.
Thats why he thinks he doesn't have this **61479055390** number in his contact list while he does have this number in his contact list.

Let me explain.
I have a number in my phone contact list, but i don't have that number in my whaticket contact list tab, because i didn't synced my contact list, so that number appears like **551999509xxxx**, and it doesn't appear the name of the contact, because i haven't synced this contact in my whaticket contact list tab.

So today that number turned into a business account, and it popped up two empty messages like @deepesh-agarwal issue.

**The solution is to ignore message type equals `e2e_notification`.**

**Backend Log:**
The message is a `fromMe` message type, and it is type `e2e_notification`.
```
2020.09.14, 22:03:07.0407 UTC -> (22:03 UTC equals 19:03 GMT-3 Brazil)
From: my-bot-cellphone-number@c.us
Type: e2e_notification
Message: 
```

**Whaticket Frontend Screenshots:**

`![whaticket-frontend](https://user-images.githubusercontent.com/18627611/93159954-ba31f000-f6e5-11ea-8499-64bfa9d277a3.jpg)`

**Comment by deepesh-agarwal** [comment]
> @canove I identified the real issue in @deepesh-agarwal case.
> 
> First of all, just because the ticket chat he's talking-to doesn't have a properly name like **John Doe** and it is identified just by **61479055390**, doesn't mean he doesn't have this number in his phone contacts list like he said. It does mean that he doesn't synced his phone contacts to whaticket contacts tab.
> Thats why he thinks he doesn't have this **61479055390** number in his contact list while he does have this number in his contact list.
> 
> Let me explain.
> I have a number in my phone contact list, but i don't have that number in my whaticket contact list tab, because i didn't synced my contact list, so that number appears like **551999509xxxx**, and it doesn't appear the name of the contact, because i haven't synced this contact in my whaticket contact list tab.
> 
> So today that number turned into a business account, and it popped up two empty messages like @deepesh-agarwal issue.
> How i know it turned into a business account? I opened a chat in my phone with this person and saw a balloon saying that today that person turned his account into a business account.
> This empty message is not on my phone and also not on wpp.web. Like @deepesh-agarwal.
> 
> **The solution is to ignore message type equals `e2e_notification`.**
> The two empty messages are `fromMe` message, and it is type `e2e_notification` and `notification_template`.
> 
> **Backend Log:**
> 
> ```
> 2020.09.14, 22:03:07.0407 UTC -> (22:03 UTC equals 19:03 GMT-3 Brazil)
> From: my-bot-cellphone-number@c.us
> Type: e2e_notification
> Message: 
> 
> 2020.09.14, 22:03:07.0426 UTC -> 
> From: 551933045004@c.us
> Type: notification_template
> Message: 
> ```
> 
> **Whaticket Frontend Screenshot:**
> 
> ![whaticket-frontend](https://user-images.githubusercontent.com/18627611/93159954-ba31f000-f6e5-11ea-8499-64bfa9d277a3.jpg)

I did a search for the name on the phone.

**Comment by esteves67** [comment]
> > @canove I identified the real issue in @deepesh-agarwal case.
> > First of all, just because the ticket chat he's talking-to doesn't have a properly name like **John Doe** and it is identified just by **61479055390**, doesn't mean he doesn't have this number in his phone contacts list like he said. It does mean that he doesn't synced his phone contacts to whaticket contacts tab.
> > Thats why he thinks he doesn't have this **61479055390** number in his contact list while he does have this number in his contact list.
> > Let me explain.
> > I have a number in my phone contact list, but i don't have that number in my whaticket contact list tab, because i didn't synced my contact list, so that number appears like **551999509xxxx**, and it doesn't appear the name of the contact, because i haven't synced this contact in my whaticket contact list tab.
> > So today that number turned into a business account, and it popped up two empty messages like @deepesh-agarwal issue.
> > How i know it turned into a business account? I opened a chat in my phone with this person and saw a balloon saying that today that person turned his account into a business account.
> > This empty message is not on my phone and also not on wpp.web. Like @deepesh-agarwal.
> > **The solution is to ignore message type equals `e2e_notification`.**
> > The two empty messages are `fromMe` message, and it is type `e2e_notification` and `notification_template`.
> > **Backend Log:**
> > ```
> > 2020.09.14, 22:03:07.0407 UTC -> (22:03 UTC equals 19:03 GMT-3 Brazil)
> > From: my-bot-cellphone-number@c.us
> > Type: e2e_notification
> > Message: 
> > 
> > 2020.09.14, 22:03:07.0426 UTC -> 
> > From: 551933045004@c.us
> > Type: notification_template
> > Message: 
> > ```
> > 
> > 
> > **Whaticket Frontend Screenshot:**
> > ![whaticket-frontend](https://user-images.githubusercontent.com/18627611/93159954-ba31f000-f6e5-11ea-8499-64bfa9d277a3.jpg)
> 
> I did a search for the name on the phone.

My bad for affirming it @deepesh-agarwal :cry:

**Comment by esteves67** [comment]
@deepesh-agarwal Do you have discord?

**Comment by deepesh-agarwal** [comment]
> My bad for affirming it @deepesh-agarwal 😢

No issues, I guess the empty message fix should be fixing it.

> @deepesh-agarwal Do you have discord?

Sorry :(

**Comment by esteves67** [comment]
> > My bad for affirming it @deepesh-agarwal cry
> 
> No issues, I guess the empty message fix should be fixing it.
> 
> > @deepesh-agarwal Do you have discord?
> 
> Sorry :(

Sorry,  i edited my post, and removed what i said that you have that number in your contact list, cuz it was rude affirming it without knowing it.
:+1:

**Comment by esteves67** [comment]
> > @canove I identified the real issue in @deepesh-agarwal case.
> > First of all, just because the ticket chat he's talking-to doesn't have a properly name like **John Doe** and it is identified just by **61479055390**, doesn't mean he doesn't have this number in his phone contacts list like he said. It does mean that he doesn't synced his phone contacts to whaticket contacts tab.
> > Thats why he thinks he doesn't have this **61479055390** number in his contact list while he does have this number in his contact list.
> > Let me explain.
> > I have a number in my phone contact list, but i don't have that number in my whaticket contact list tab, because i didn't synced my contact list, so that number appears like **551999509xxxx**, and it doesn't appear the name of the contact, because i haven't synced this contact in my whaticket contact list tab.
> > So today that number turned into a business account, and it popped up two empty messages like @deepesh-agarwal issue.
> > How i know it turned into a business account? I opened a chat in my phone with this person and saw a balloon saying that today that person turned his account into a business account.
> > This empty message is not on my phone and also not on wpp.web. Like @deepesh-agarwal.
> > **The solution is to ignore message type equals `e2e_notification`.**
> > The two empty messages are `fromMe` message, and it is type `e2e_notification` and `notification_template`.
> > **Backend Log:**
> > ```
> > 2020.09.14, 22:03:07.0407 UTC -> (22:03 UTC equals 19:03 GMT-3 Brazil)
> > From: my-bot-cellphone-number@c.us
> > Type: e2e_notification
> > Message: 
> > 
> > 2020.09.14, 22:03:07.0426 UTC -> 
> > From: 551933045004@c.us
> > Type: notification_template
> > Message: 
> > ```
> > 
> > 
> > **Whaticket Frontend Screenshot:**
> > ![whaticket-frontend](https://user-images.githubusercontent.com/18627611/93159954-ba31f000-f6e5-11ea-8499-64bfa9d277a3.jpg)
> 
> I did a search for the name on the phone.

Dang my bot number is appearing in your reply, can you edit that reply and remove the quote please? Im afraid people will spam my bot :sob:

**Comment by esteves67** [comment]
> > My bad for affirming it @deepesh-agarwal cry
> 
> No issues, I guess the empty message fix should be fixing it.
> 
> > @deepesh-agarwal Do you have discord?
> 
> Sorry :(

I hope it does fixes, let's wait for @canove to see what he thinks about.

**Comment by esteves67** [comment]
> > @canove I identified the real issue in @deepesh-agarwal case.
> > First of all, just because the ticket chat he's talking-to doesn't have a properly name like **John Doe** and it is identified just by **61479055390**, doesn't mean he doesn't have this number in his phone contacts list like he said. It does mean that he doesn't synced his phone contacts to whaticket contacts tab.
> > Thats why he thinks he doesn't have this **61479055390** number in his contact list while he does have this number in his contact list.
> > Let me explain.
> > I have a number in my phone contact list, but i don't have that number in my whaticket contact list tab, because i didn't synced my contact list, so that number appears like **551999509xxxx**, and it doesn't appear the name of the contact, because i haven't synced this contact in my whaticket contact list tab.
> > So today that number turned into a business account, and it popped up two empty messages like @deepesh-agarwal issue.
> > How i know it turned into a business account? I opened a chat in my phone with this person and saw a balloon saying that today that person turned his account into a business account.
> > This empty message is not on my phone and also not on wpp.web. Like @deepesh-agarwal.
> > **The solution is to ignore message type equals `e2e_notification`.**
> > The two empty messages are `fromMe` message, and it is type `e2e_notification` and `notification_template`.
> > **Backend Log:**
> > ```
> > 2020.09.14, 22:03:07.0407 UTC -> (22:03 UTC equals 19:03 GMT-3 Brazil)
> > From: my-bot-cellphone-number@c.us
> > Type: e2e_notification
> > Message: 
> > 
> > 2020.09.14, 22:03:07.0426 UTC -> 
> > From: 551933045004@c.us
> > Type: notification_template
> > Message: 
> > ```
> > 
> > 
> > **Whaticket Frontend Screenshot:**
> > ![whaticket-frontend](https://user-images.githubusercontent.com/18627611/93159954-ba31f000-f6e5-11ea-8499-64bfa9d277a3.jpg)
> 
> I did a search for the name on the phone.

@deepesh-agarwal
Dang my bot number is appearing in your reply, can you edit that reply and remove the quote please? Im afraid people will spam my bot like they do with those weird characters :sob:

**Comment by esteves67** [comment]
@deepesh-agarwal Im gonna delete some of my messages where we had conversation/talked, so it don't polute your ticket OK?

**Comment by esteves67** [comment]
> > Type: notification_template
> > Message:
> 
> I did a search for the name on the phone.

Might be a different issue you are having then, different than mine, but you helped sculpt the code by opening this issue, if you didn't we won't notice that empty messages thing. 
I did the pull request, but if you want to do a pull request yourself since you found this bug, i can delete my pull request and you do the pull request yourself. 
Tell me what you think of it.

**Comment by esteves67** [comment]
> > Type: notification_template
> > Message:
> 
> I did a search for the name on the phone.

Could be a different issue you are having then, different than mine, because there's alot of empty message types i think since i found two `e2e_notification` and `notification_template`, but there might be other ones.

You helped sculpt the code by opening this issue, if you didn't we won't notice that empty messages thing.

@deepesh-agarwal
I did the pull request, but if you want to do a pull request yourself since you found this bug, i can delete my pull request and you do the pull request yourself. 

Tell me what you think of it.
