### ISSUE TITLE
problema com perda de conexao

### ISSUE THREAD

**Issue by inforeis** [canove/whaticket#181]
Pessoal, com muuuita frequencia a conexao como whatsapp cai e em algumas vezes preciso reiniciar o servidor para que funcione. Alguém passando por isso?

**Comment by JoaoAngelo** [comment]
Já aconteceu comigo o servidor estava rodando normal, e do nada parar de receber mensagens. Quando reiniciei voltou ao normal.

**Comment by inforeis** [comment]
No meu caso, estou tendo que reiniciar diariamente. :(

**Comment by nestordavalos** [comment]
update whatsapp-web.js

**Comment by inforeis** [comment]
@nestordavalos , está atualizado. :(

Me parece ser um caso de memory leak.

Acontecia com mais frequência... eu fiz um upgrade no servidor e melhorou. mas, mesmo assim continua. Reinicio o servidor e volta a funcionar. Porém, tem horas que não volta.

**Comment by brenofebronio** [comment]
Já verificou se não é seu WhatsApp que está com esse problema de conexão? Deixe o WhatsApp aberto em primeiro plano e fique utilizando para ver se vai perder a conexão.

**Comment by rodrigofsantos** [comment]
Muda seu whatsapp para um VM como NOX fica muito mais estável !!!!

**Comment by brenofebronio** [comment]
> VM como NOX fica muito mais estável

Como faria a leitura do QRCODE ?

**Comment by rodrigofsantos** [comment]
manycam

**Comment by brenofebronio** [comment]
> manycam ele transforma seu mouse em uma webcam

Teria o link explicando como faz ?

**Comment by rodrigofsantos** [comment]
Neste video voce vai ver mais ou menos como fazer apesar de que neste video trava muito mas quando voce faz em uma maquina boa funciona rapidinho, aqui em leio o QRcode uma vez a cada 4 meses e olhe la !!!

https://www.youtube.com/watch?v=jw25fV-r4GY
