### ISSUE TITLE
Criação de Multi-Sessões

### ISSUE THREAD

**Issue by brenofebronio** [canove/whaticket#187]
Alguém conseguiu automatizar a criação de mais sessões no mesmo ambiente?

**Comment by inforeis** [comment]
Como assim?

**Comment by rodrigofsantos** [comment]
O sistema ja aceita mais de uma sessão de whatsapp basta ir la em conexões e cadastrar todos os whatsapp que precisa e direcionar ele para a fila que cada usuário pertence importante criar as filas primeiro depois os usuários e setar a fila de cada um depois cadastrar os whatsapp e vincular a fila ou as filas que ela vai se reportar !!!!

**Comment by ericdesaoficial** [comment]
Ele não esta querendo dizer isso. Ele quer escalar o serviço e no modelo atual para cada empresa que ele oferece o serviço tem que fazer uma instalação. E com multi tenancy ele consegue ter varias empresas diferentes utilizando com sem precisar ficar fazendo instalação
Teria que ter uma instancia acima para gerenciar os usuários e os planos e uma forma de não sobrecarregar o servidor

**Comment by rodrigofsantos** [comment]
Entendi @ericdesaoficial !

**Comment by KatiaSishost** [comment]
like a SaaS? i trying it too... im trying to change .env with domain / subdomain but ir change all sessions inclusive the other users after new user enter in diferent subdomain

**Comment by Vojoo** [comment]
sim, ja funcionando, chame no zap 27 992633735

**Comment by Vojoo** [comment]
inclusive ja possui chatboot

**Comment by rodrigobg** [comment]
Pessoal não entendi, eu consigo com apenas uma instalação usar o whatticker como um sistema SAAS? Existe algum tutorial ensinando como fazer isso?

**Comment by botusist** [comment]
Olá Pessoal, alguem conhece instalação do whaticket saas free?
