### ISSUE TITLE
Cant get whaticket running

### ISSUE THREAD

**Issue by soporte-islanetworks** [canove/whaticket#189]
I tried installing whaticket for over 2 days, the panel (frontend) installs and shows up, the backend installs and says it is running, but once i navigate to the web panel, and try to register , doesnt works,

Things i tried:
using a bunch of combination of ips, (localhost, 127.0.0.1, ip of machine,  all mentioned early with port on the right)
reinstalling a couple of times (with variations)
removing the database container that comes as default and changing it to a newer version of mariadb, (in the last case the database is created)

im running ubuntu server 20.04 (x86)

**Comment by redealpha** [comment]
Hi, were you able to solve this problem? I'm also having the same problem

**Comment by gabrielromanosec** [comment]
Tente no ubuntu 18.04. aqui está ok

**Comment by soporte-islanetworks** [comment]
> Hi, were you able to solve this problem? I'm also having the same problem

not yet, im gonna try the gabrielromanosec methode , of using 18.04, to see if it works there, and create then a vm in that version for production

**Comment by rodrigofsantos** [comment]
Amigo eu tive o mesmo problema e são dois fatores que impedem a autenticação primeiro você precisa seta o banco de dados no mysql para o formato indicado no codigo :
module.exports = {
  define: {
    charset: "utf8mb4",
    collate: "utf8mb4_bin"
  },
Ai Rode o migrations e o seeds ...

Depois você preciso colocar o serviço tanto do backend quanto do frontend para rodar no mesmo ip use o ip da sua maquina se confira se as portas estão livres se não estiverem muda as portas no meu caso eu usei a 8181 para o backend e a 3000 para o frontend mas você pode usar qualquer uma desde que esteja livre.

Lembrando que se sua maquina precisa estar com ip fixo assim voce tera um garantia de funcionamento ...

**Comment by redealpha** [comment]
> > Hi, were you able to solve this problem? I'm also having the same problem
> 
> not yet, im gonna try the gabrielromanosec methode , of using 18.04, to see if it works there, and create then a vm in that version for production


Hi, I followed the suggestion given by the @rodrigofsantos  and it worked. It works on Ubuntu 20.4

**Comment by redealpha** [comment]
> Amigo eu tive o mesmo problema e são dois fatores que impedem a autenticação primeiro você precisa seta o banco de dados no mysql para o formato indicado no codigo :
> module.exports = {
> define: {
> charset: "utf8mb4",
> collate: "utf8mb4_bin"
> },
> Ai Rode o migrations e o seeds ...
> 
> Depois você preciso colocar o serviço tanto do backend quanto do frontend para rodar no mesmo ip use o ip da sua maquina se confira se as portas estão livres se não estiverem muda as portas no meu caso eu usei a 8181 para o backend e a 3000 para o frontend mas você pode usar qualquer uma desde que esteja livre.
> 
> Lembrando que se sua maquina precisa estar com ip fixo assim voce tera um garantia de funcionamento ...

Muito obrigado. Após modificar o banco para utf8mb4 funcionou

**Comment by soporte-islanetworks** [comment]
> Amigo eu tive o mesmo problema e são dois fatores que impedem a autenticação primeiro você precisa seta o banco de dados no mysql para o formato indicado no codigo :
> module.exports = {
> define: {
> charset: "utf8mb4",
> collate: "utf8mb4_bin"
> },
> Ai Rode o migrations e o seeds ...
> 
> Depois você preciso colocar o serviço tanto do backend quanto do frontend para rodar no mesmo ip use o ip da sua maquina se confira se as portas estão livres se não estiverem muda as portas no meu caso eu usei a 8181 para o backend e a 3000 para o frontend mas você pode usar qualquer uma desde que esteja livre.
> 
> Lembrando que se sua maquina precisa estar com ip fixo assim voce tera um garantia de funcionamento ...

hey, i already have that configuration int the file backend/dist/config/database.js

![image](https://user-images.githubusercontent.com/84085768/119152855-faa1f480-ba50-11eb-8e3c-39a2d176c2bf.png)

**Comment by rodrigofsantos** [comment]
Sim e esta correto, você precisa criar o banco de dados com essa mesma configuração !! Isso no momento da criação do banco de dados !

Aqui eu uso o DBeaver :
![image](https://user-images.githubusercontent.com/3025912/119153912-ac283200-ba1f-11eb-86bb-5677a0f635ae.png)

**Comment by redealpha** [comment]
> > Amigo eu tivo o mesmo problema e são dois fatores que impedem a autenticação primeiro você precisa seta o banco de dados no mysql para o formato indicado no codigo: 
> > module.exports = { 
> > definir: { 
> > charset: "utf8mb4", 
> > agrupar: "utf8mb4_bin" 
> > }, 
> > Ai Rode o migrações e sementes ...
> > Depois que você preciso colocar o serviço tanto do backend quanto do frontend para rodar no mesmo ip use o ip da sua maquina se confira se as portas estão livres se não passar muda como portas no meu caso eu usei a 8181 para o backend e 3000 para o frontend mas você pode usar qualquer uma desde que esteja livre.
> > Lembrando que se sua maquina precisa estar com ip fixo assim voce tera um garantia de funcionamento ...
> 
> Ei, eu já tenho essa configuração no arquivo backend / dist / config / database.js
> 
> ![imagem](https://user-images.githubusercontent.com/84085768/119152855-faa1f480-ba50-11eb-8e3c-39a2d176c2bf.png)


No. You need to change your database to and the utf8mb4 collation

**Comment by Kouthk** [comment]
@soporte-islanetworks você conseguiu roda-lo na versão 20.04 server?
