### ISSUE TITLE
Mensagens Deletadas não são deletadas

### ISSUE THREAD

**Issue by PauloBettin** [canove/whaticket#191]
Mensagens deletadas no whatsapp não são deletadas no frontend.

**Comment by rodrigofsantos** [comment]
Sim o banco de dados são separados isso traz mais segurança pois no sistema vai ficar um historico das conversas !

**Comment by PauloBettin** [comment]
Eu entendo, por um lado é bom e por outro lado ruim.

Exp um cliente manda um pedido ou algo do tipo mas ele exclui porque mandou
o incorreto.

Ficaria ali o pedido incorreto no histórico possibilitando o erro humano.

Mas muito obrigado pelo feedback.

Atenciosamente.

Paulo Bettin


Em qui., 27 de mai. de 2021 às 09:34, rodrigofsantos <
***@***.***> escreveu:

**Comment by rodrigofsantos** [comment]
Seria melhor que fosse marcado como deletada assim como no whatsappGB !!!
