### ISSUE TITLE
O chatbot não responde mais, alguém pode dar suporte?

### ISSUE THREAD

**Issue by seven7app** [canove/whaticket#192]
Fiz a configuração correta no dia que instalei e usei e testei mas no dia seguinte agente envia uma mensagem ele recebe mas não responde nada através do bot., se alguém teve esse experiência me fale por favor

**Comment by janjrr** [comment]
Estou com o mesmo problema, alguém conseguiu resolver?

**Comment by redealpha** [comment]
@seven7app e @janjrr  O serviços estão sendo executados, ao tentar a acessar a URL de backend (sem rotas) apresenta a seguinte mensagem: **Cannot GET /** ?

**Comment by PauloBettin** [comment]
Ola, tive esse mesmo problema quando usando mais de 1x numero de conexão e não tendo 1x deles definido como padrão, verifica na sua guia de conexões se você tem um número definido de rota padrão.

**Comment by rodrigofsantos** [comment]
Vocês conseguiram resolver, so para contar se voce tiver dois numeros  sendo o primeiro o padrão e segundo não, ao ser atendido por um não padrão o bot não vai enviar responsta automatica do segundo numero, depois não vai fazer mais mesmo que seu atendimento inicie pelo primeiro numero so vai voltar a fazer isso se deletar todas as mesagens ou seja vai em atendidos e clica no historico do atendimento e deleta ai ele vai voltar a responder !! Isso acontece por que se voce foi transferido ou entrar em contato primeiro por um numero que não e o padrão ele não vai retornar para você pelo bot padrão !!

**Comment by rodrigofsantos** [comment]
Ola estou com mesmo problema hoje e descobri o por que quando você entra pela primeira vez o sistema de cadastra sem nenhuma fila apos isso se vocês colher alguma fila ele vai na tebela tickets e seta voce na coluna queueid com o id da fila que voce escolheu dai por diante ele não te mais opções por você ja ter uma fila pois ele se baseia na fila que voce esta no momento para te dar um resposta automatica o correto seria ver se o ticket esta aberto ou fechado  :
se fechado enviar mensagem 

para contornar esse problema basta voce reabir o ticket e transferir para seu proprio usuario e depois fechar ele ai o sistema vai te permitir ter acesso a resposta automática novamente !!!!

@canove  precisamos de sua ajuda neste tema !!!!

**Comment by canove** [comment]
Boa tarde, amigos!

Estou trabalhando em outros projetos e, ultimamente, não tenho tido tempo de acompanhar o repositório. Fico feliz que vcs estejam conseguindo se ajudar.

Sobre a questão das respostas automáticas, o critério utilizado para responder ou não está no arquivo `backend/src/services/WbotServices/wbotMessageListener.ts`, nas linhas 264-270

Mas, basicamente, ele só vai responder caso tudo isso seja verdadeiro:
- O ticket não tenha fila.
- O ticket não tenha atendente.
- O ticket não seja um grupo.
- A mensagem não seja "minha".
- O whatsapp ao qual o ticket pertence tenha 2 ou mais filas associadas.

Quando você recebe uma nova mensagem em um ticket fechado, caso ele tenha sido fechado em menos 2 horas, o emsmo ticket é reaberto e, por isso, o bot não responde.

Vocês podem contornar conforme a instrução do @rodrigofsantos, ou alterar esse tempo de 2h na linha 47 do arquivo `FindOrCreateTicketService`

Espero ter ajudado.

**Comment by rodrigofsantos** [comment]
Obrigado @canove deu certo diminui o tempo e assim quando o client entra em contato aparece as opções novamente ficou otimo obrigado se possivel veja se consegue ver o ticket #195 por favor !!!

**Comment by lisboadouglas** [comment]
> Mesmo alterando o tempo, não surtiu efeito para mim Como era ` where: { updatedAt: { [Op.between]: [+subHours(new Date(), 2), +new Date()] }, contactId: contact.id }`
> 
> Como ficou: ` where: { updatedAt: { [Op.between]: [+subSeconds(new Date(), 2), +new Date()] }, contactId: contact.id }` e mesmo assim, ele não manda mensagem para alterar de fila após a conversa ser marcada como resolvida.
> 
> @rodrigofsantos @canove poderiam me dar uma luz? Quero que seja possivel, receber aquelas mensagens automaticas e trocar de fila logo após finalizar o ticket

Para mim, funcionou da seguinte forma:
Modifiquei o arquivo backend/src/services/TicketServices/FindOrCreateTicketService.ts

1. Na Linha 1 alterei para  `import { subMinutes } from "date-fns";` 
2. Na linha 47 alterei para ` [Op.between]: [+subMinutes(new Date(), 1), +new Date()]`

**Comment by Kouthk** [comment]
Funcionou! Tinha me esquecido desse detalhe... Muito obrigado!

**Comment by TorresSantos** [comment]
Estou com este mesmo problema de vocês ? Como resolveram ?
