### ISSUE TITLE
Error wss and emojis Nginx.

### ISSUE THREAD

**Issue by viapratica** [canove/whaticket#193]
Hi everyone, 

has anyone managed to get the chat to run on https using nginx? Mine runs but always displays an error message:

WebSocket connection to 'wss://domain.com/socket.io/?EIO=4&transport=websocket&sid=wUhJ7zGyEy7fXWhqAAPu' failed:

I don't know if that's why, but emojis sent from cell phone to chat are not displayed, and emojis sent from chat to cell appear on cell phone but not in chat conversation. 

my Nginx 

 server {
     listen 443 ssl http2;
     server_name domain.com;
     ssl on;

    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem; # managed by Certbot

     ssl_session_timeout 5m;
     ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
     ssl_prefer_server_ciphers on;
     ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';

     location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:8586;
        proxy_ssl_session_reuse off;
        proxy_set_header Host $http_host;
        proxy_cache_bypass $http_upgrade;
        proxy_redirect off;
     }

}

**Comment by brenofebronio001** [comment]
Hi friend, did you find the problem?
