### ISSUE TITLE
Varios whatsapp mas as mensagens so saem por um

### ISSUE THREAD

**Issue by rodrigofsantos** [canove/whaticket#194]
Senhores estou com servidor ativo e ativeis dois whatsapp e percebi que ao receber uma mensagem nos dois whatsapp o sistema so responde pelo padrão e mesmo desmarcando ele a mensagem sempre a respondida pelo primeiro .
Exemplo estou com uma conta Comercial da empresa e outra do setor de cobrança ao receber uma mensagem no whats da cobrança o sistema responde pela Comercial como podemos fazer para que cada mensagem saia pelo seu respectivo receptor ????

**Comment by PauloBettin** [comment]
Adiciona filas de atendimentos específicas para cada número que ele responde no número que a mensagem chegou.

Exp: Para o comercial cria fila comercial e atrela ela apenas ao numero comercial na tela de conexão, faça o mesmo no caso do Cobrança e verifica se funciona desta maneira a saida das mensagens corretamente.

**Comment by rodrigofsantos** [comment]
Obrigado resolvido era isso mesmo !!!
