### ISSUE TITLE
Função de preenchimento automatico de mensagem

### ISSUE THREAD

**Issue by rodrigofsantos** [canove/whaticket#195]
Ola Canove seria possivel criar um cadastra de respostas rapidas para inserir no campo send da mensagem tipo um select e criar um form para cadastramos as respostas rapidas para inserir no campo seria o seguinte exemplo :
[Select com auto inset em campo input](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_text_value_dropdown)

Ai se possivel criar uma tela de cadstro das respostas rapidas que ficaria disponivel para todos os usuarios  !!!

**Comment by developerdevice** [comment]
Vou fazer um fork e adicionar essa funcionalidade, vou enviar um PR também, caso o Canove decida aceitar.

**Comment by rodrigofsantos** [comment]
Consegiu fazer @developerdevice ?
