### ISSUE TITLE
Erro pós Instalação

### ISSUE THREAD

**Issue by bonanati** [canove/whaticket#197]
Olá pessoal, fiz a instalação conforme o readme e quando vou cadastrar o usuário está dando o erro An error occurred!.
O que posso estar fazendo de errado?
![erro whaticket](https://user-images.githubusercontent.com/4721323/123027913-f735bc00-d3b4-11eb-8cd7-846bdace0e31.png)

**Comment by redealpha** [comment]
Olá. bom dia.

Você chegou a verificar se:

1.Os endereços de BACKEND E FRONTEND estão com os IP's ou domínio correto, bem como as portas corretas. Se estiver instalando o serviço em LAN, não utilize https://localhost, utilize o IP da máquina. OBS.: Ao alterar as informações do .ENV, execute npm build para buildar com as novas informações.

2. Verifique se o backend está acessível.

**Comment by gardyson** [comment]
Bom dia! Conforme o @redealpha comentou, possivelmente há configuração errada ao apontar para o backend. Posta pra gente como está o .env do front, e o .env do backend. Dá uma olhada no console do navegador tbm, pra ver o erro.

**Comment by bonanati** [comment]
Deu certo meus amigos.. obrigado pela dica, era configuração de IP mesmo no arquivo .env agradeço

**Comment by bonanati** [comment]
Deu certo meus amigos.. obrigado pela dica, era configuração de IP mesmo no arquivo .env agradeço

**Comment by gabrielwjesus** [comment]
estou reabrindo esse ticket pq eu estou com o mesmo erro agora e não consigo encontrar a solução.
tinha uma instalação de um whaticket saas free rodando 100% no meu servidor vps
removi toda instalação e banco de dados
baixei essa versao basica e inicial e agora na tela de login da esse erro An error occurred. 
vendo os logs nada aparece, 
quando eu erro a senha ele da o alerta que a senha esta incorreta, e nos logs mostra a mensagem com erro 401. 

mas o que pode ser ? 
tambem nao é possivel criar um usuário novo pois nao tem nada no menu company,

**Comment by alanddos** [comment]
> estou reabrindo esse ticket pq eu estou com o mesmo erro agora e não consigo encontrar a solução. tinha uma instalação de um whaticket saas free rodando 100% no meu servidor vps removi toda instalação e banco de dados baixei essa versao basica e inicial e agora na tela de login da esse erro An error occurred. vendo os logs nada aparece, quando eu erro a senha ele da o alerta que a senha esta incorreta, e nos logs mostra a mensagem com erro 401.
> 
> mas o que pode ser ? tambem nao é possivel criar um usuário novo pois nao tem nada no menu company,

401 é acesso negado, o usuário que está usando não tem acesso para criar pegue o seu usuário principal e coloque acesso admin nele, não lembro se a senha tem opção de se recuperar mas se não vc pode criar um novo usuário coloca uma senha e depois vai no banco de dados e copia a senha do usuário que criou em cima do que está errado e então os dois vão ter a mesma senha

**Comment by gabrielwjesus** [comment]
> > estou reabrindo esse ticket pq eu estou com o mesmo erro agora e não consigo encontrar a solução. tinha uma instalação de um whaticket saas free rodando 100% no meu servidor vps removi toda instalação e banco de dados baixei essa versao basica e inicial e agora na tela de login da esse erro An error occurred. vendo os logs nada aparece, quando eu erro a senha ele da o alerta que a senha esta incorreta, e nos logs mostra a mensagem com erro 401.
> > mas o que pode ser ? tambem nao é possivel criar um usuário novo pois nao tem nada no menu company,
> 
> 401 é acesso negado, o usuário que está usando não tem acesso para criar pegue o seu usuário principal e coloque acesso admin nele, não lembro se a senha tem opção de se recuperar mas se não vc pode criar um novo usuário coloca uma senha e depois vai no banco de dados e copia a senha do usuário que criou em cima do que está errado e então os dois vão ter a mesma senha, se na tela inicial não aparecer a opção de cadastro no banco de dados tem uma opção para permitir cadastro tem que ativar lá que vai permitir

Quando coloca a senha certa ele aparece o erro na tela "an error occurred". Mas nos logs ele nao mostra nenhum erro.
E quando coloca a senha errada ele mostra o erro 401 nos logs e na tela mostra que a senha esta errada. 

eu vou tentar refazer toda a instalação limpa.
