### ISSUE TITLE
Não consigo escutar o audio

### ISSUE THREAD

**Issue by bonanati** [canove/whaticket#198]
Pessoal o audio recebe no whaticket mais não consigo escutar o que poderia ser?
![audio](https://user-images.githubusercontent.com/4721323/123129153-1cacdf00-d422-11eb-8f20-dffe92c5eeab.png)

**Comment by bonanati** [comment]
![api error](https://user-images.githubusercontent.com/4721323/123135470-38b37f00-d428-11eb-808c-ccf76ebba776.png)

**Comment by gardyson** [comment]
Boa tarde. Os audios estão entrando na sua pasta , no backend?

**Comment by gabrielromanosec** [comment]
Possivelmente os arquivos não estão entrando na pasta /backend/public
tente: sudo chmod +777 -R /backend/public

**Comment by bonanati** [comment]
Resolvido amigos, removi a porta 8080 do PROXY_PORT= no arquivo .env
