### ISSUE TITLE
Whaticket Backend + PHP FrontEnd

### ISSUE THREAD

**Issue by KatiaSishost** [canove/whaticket#199]
Oi Canove, você poderia me dar uma mão para usar o backend do whaticket e o frontend refazê-lo, mas com php?
Eu gostaria de fazer a interação da mesma forma que o sistema atual, mas feita em php

**Comment by rodrigofsantos** [comment]
Ola amigo oque precisa ?

**Comment by rodrigofsantos** [comment]
Ola oque precisa? voce vai usar PHP puro ou um framework ?

**Comment by MNCamargo** [comment]
PHP puro em princípio para testes e Laravel para acertar.

**Comment by KatiaSishost** [comment]
PHP puro em princípio para testes e Laravel para acertar.

**Comment by KatiaSishost** [comment]
any?

**Comment by NetLogin-Brasil** [comment]
Eu tambem tenho interesse em usar o laravel

**Comment by diogenesjup** [comment]
Essa iniciativa aqui morreu?
