### ISSUE TITLE
PM2 autostart como root

### ISSUE THREAD

**Issue by gardyson** [canove/whaticket#200]
Pessoal, bom dia.
Estou apanhando um monte para colocar meu ambiente pra rodar no startup.
consigo executar os serviços manualmente pelo pm2 e está ok, porém quando tento colocar pelo startup, usando pm2 startup, nao vai. Isso como root., depois do reboot nao sobe.
Porém quando faço com usuário local, ele gera o comando "env" , após reiniciar o serviço sobe mas não funciona. Alguém consegue me dar um help, ou passar aonde posso ver algum log?

**Comment by gardyson** [comment]
![image](https://user-images.githubusercontent.com/86362174/123647234-48530f00-d7fe-11eb-97e8-8b292971d958.png)

**Comment by gardyson** [comment]
> i'm using a cron at reboot.
> 
> ```
> crontab -e
> 
> @reboot pm2 start /dir/whaticket/backend/dist/server.js --name whaticket-backend
> ```

TKS!
i've tried it, but after reboot they don't appear in "pm2 list" and the application doesn't work. On ps-aux | grep pm2 i get this:
root         739  0.0  0.0   2608   608 ?        Ss   14:28   0:00 /bin/sh -c pm2 start /home/user/whaticket/backend/dist/server.js --name whaticketbackend
root         740  0.0  0.0   2608   536 ?        Ss   14:28   0:00 /bin/sh -c pm2 start /home/user/whaticket/frontend/node_modules/react-scripts/scripts/start.js --name whaticket-frontend
root         741  0.2  0.9 563200 40184 ?        Sl   14:28   0:00 node /usr/bin/pm2 start /home/user/whaticket/backend/dist/server.js --name whaticketbackend
root         742  0.2  0.9 563456 39320 ?        Sl   14:28   0:00 node /usr/bin/pm2 start /home/user/whaticket/frontend/node_modules/react-scripts/scripts/start.js

**Comment by gardyson** [comment]
Após várias tentativas, ainda não consegui colocar pra inicializar automático, apenas após subir o sistema, e colocando o npm pra rodar dentro da pasta. Alguem tem alguma sugestao?

**Comment by rodrigofsantos** [comment]
amigo eu tenho um script em shell que faz isso pois tive varios problema ao usar pm2 eu startava e ele não acessava nem na bala mas como voce esta usando o sistema esta usando em uma porta especifica ? ja tentou usar com ngix ?

**Comment by gardyson** [comment]
> amigo eu tenho um script em shell que faz isso pois tive varios problema ao usar pm2 eu startava e ele não acessava nem na bala mas como voce esta usando o sistema esta usando em uma porta especifica ? ja tentou usar com ngix ?

Opa @rodrigofsantos boa tarde
Estou usando direto na porta 3000 mesmo. Como vou usar só internamente, não implementei o ngix. O script vc tá startando ele como?

**Comment by rodrigofsantos** [comment]
manda um e-mail para rodrigofsantos@gmail.com que te mando como configurar ok fica tranquilo que não vou te cobrar nada kkkkkkkkk

**Comment by monteirosk** [comment]
usa: pm2 save

**Comment by gardyson** [comment]
Resolvi com um "ajuste técnico" colocando no cron @reboot pm2 resurrect
