### ISSUE TITLE
Dude, I'm with a trouble with my installation

### ISSUE THREAD

**Issue by Kodew1** [canove/whaticket#201]
Dude, I'm with a trouble with my installation, said there that I need use Node 12 but just working with node 16 and with 16 return an error as like this on printscreen, I sincerely haven't no ideal to fix it
![d67e60ce-1d4e-434e-af64-e2248ec91bec](https://user-images.githubusercontent.com/86810737/124204936-7f534a00-dab6-11eb-84b3-49e0ac0d93ed.png)

**Comment by KatiaSishost** [comment]
%20 is a blank space... see in config files if u have a space...  and run node install and npm run dev again

**Comment by 592srawlins** [comment]
Actually at the same place but myerror is a bit different....

![image](https://user-images.githubusercontent.com/87147606/124991784-1c126c00-e010-11eb-9feb-f9ba1c4c7de8.png)
