### ISSUE TITLE
Erro ao gravar audio para envio

### ISSUE THREAD

**Issue by dev-oneclick** [canove/whaticket#203]
Instalei o Whaticket numa vm com ubuntu 20.04 para teste esta funcionando normalmente quase tudo, o único problema que percebi é que na hora de gravar o  áudio  ele da erro " An error Ocurred!" quando a configuração dos arquivos .env estão com configurados com ip, realizei um teste instalando no meu próprio computador com windows e completei os endereços usando "localhost"  funciona normalmente alguém já passou por isso? 
fico grato pela ajuda.

**Comment by KatiaSishost** [comment]
to use audio need ssl

**Comment by dev-oneclick** [comment]
Ok thank you very much, i will implement ssl.

**Comment by wspolidoro** [comment]
> Instalei o Whaticket numa vm com ubuntu 20.04 para teste esta funcionando normalmente quase tudo, o único problema que percebi é que na hora de gravar o áudio ele da erro " An error Ocurred!" quando a configuração dos arquivos .env estão com configurados com ip, realizei um teste instalando no meu próprio computador com windows e completei os endereços usando "localhost" funciona normalmente alguém já passou por isso?
> fico grato pela ajuda.

Olá, eu estou com problema no whaticket e procurando alguém que me ajude a deixa-lo funcionando. você pode me ajudar? como faço para falar com você?

**Comment by dev-oneclick** [comment]
Então via rede local sem ssl nao funciona  o envio de audio e ainda estou tentando implantar o ssl em localhost mas até agora sem exito.

**Comment by wspolidoro** [comment]
Eu tenho instalado na digital ocean, comprei com um pessoal que vendia o "metodo" e entrei bem... eles pararam de responder. nao entendo nada de vps (agora até mais de tanto fuçar) mas o whaticket até funcionou e 24h dps parava. Audio eu nem tentei testar para chegar nesse problema. você conhece (ou até mesmo você, não sei) alguem que me ajude cobrando?

**Comment by dev-oneclick** [comment]
Então via vps o meu esta funcionando normalmente com uma vps com estrutura brasileira com 4gb ubuntu 20.04 usei o tutorial Basic production deployment (Ubuntu 18.04 VPS) do próprio Canove sem erros! , testei tambem na digital ocean mas não gostei pelo valor não compensou latência muito alta.

**Comment by wspolidoro** [comment]
Eu até procurei outro servidor VPS no Brasil, mas pelo manual, a configuração minima (que era até ubuntu 18) so digital ocean era pagável... aqui no BR tudo mais alto. VPS o seu funciona normalmente sem audio né. Consegue instalar pra mim? Quanto me cobraria? Aqui no BR quanto é o servidor que suporta?

**Comment by dev-oneclick** [comment]
Então a minha instalação na vps brasileira funciona normalmente com ubuntu 20.04 mas tambem testei na 18 com todas funções com audio, video, envio de arquivos e recebimentos sem erro. tem uns 20 dias que instalei pra valer e esta funcional até o momento esperando virar o mês pra pagar um café pro Canove!, me chama la no discord  Alex Inacio#1030

**Comment by rodrigofsantos** [comment]
Pessoal aqui eu uso normalmente e uso VPS da hostinger !

**Comment by rodrigofsantos** [comment]
@wspolidoro se precisa de suporte me avisa posso te ajudar !

**Comment by wspolidoro** [comment]
Preciso sim. Me manda um contato. Abs
Em 30 de jul. de 2021 18:23 -0300, rodrigofsantos ***@***.***> escreveu:

**Comment by rodrigofsantos** [comment]
65996657313 meu whtas !!!
