### ISSUE TITLE
QR code não está autenticando

### ISSUE THREAD

**Issue by gardyson** [canove/whaticket#205]
Galera, bom dia.
Ao fazer uns testes hoje de manhã, removi a conta e ao adicionar o QR code não está lendo mais. Alguém com o mesmo problema?

**Comment by redealpha** [comment]
Bom dia. 

Isso já aconteceu comigo algumas vezes, foi necessário eu reiniciar o backend para que a autenticação funcionasse.

**Comment by gardyson** [comment]
> Bom dia.
> 
> Isso já aconteceu comigo algumas vezes, foi necessário eu reiniciar o backend para que a autenticação funcionasse.

Então...eu reiniciei o backend, maquina, voltei snapshot, rodei atualização, fiz de tudo e nada infelizmente kk. Pelo web.whatsapp ta funcionando normal. Queria ver se mais alguem ta com esse problema pra ver se nao é algo generalizado, pq enquanto eu estava com a conta logada, tava tudo ok, foi tentar adicionar outra, que não funcionou mais

**Comment by gardyson** [comment]
Não sai dessa tela
![image](https://user-images.githubusercontent.com/86362174/125461381-c3860fca-6e26-48b0-9b13-a5d1d4cd33ce.png)

**Comment by nicolasjuan** [comment]
Hi. I had the same problem and solved it updating the whatsapp-web.js library version.
So, you have to go to the "backend" folder, on the "package.json" file, find the line on "dependencies" group where is whatsapp-web.js and change to the **version v1.13.2**
Then run "npm install" on terminal, and "npm run build" to be sure, and then run the server again.

**Comment by gardyson** [comment]
> Hi. I had the same problem and solved it updating the **whatsapp-web.js library version**.
> So, you have to go to the "backend" folder, on the "package.json" file, find the line on "dependencies" group where is whatsapp-web.js and change to the **version v1.13.2**
> Then run "npm install" on terminal, and "npm run build" to be sure, and then run the server again.

@nicolasjuan no words to describe how grateful i am
thanks a lot. It works!
