### ISSUE TITLE
Session JWT

### ISSUE THREAD

**Issue by KatiaSishost** [canove/whaticket#208]
Hello, im trying to start session from laravel and get token but in console have error:

$base_uri = 'http://localhost:8080/auth/login';

try {

    $client = new \GuzzleHttp\Client();
    $session = $client->post($base_uri, [
        'headers' => [
            'Accept' => 'application/json',
        ],
        'form_params' => [
            'email' => 'info@katia.com',
            'password' => 'test',
        ]
    ]);

backend error:

[1626701109867] ERROR: WHERE parameter "email" has invalid "undefined" value
    Error: WHERE parameter "email" has invalid "undefined" value
        at MySQLQueryGenerator.whereItemQuery (C:\Users\Usuario\Desktop\whaticket-master\backend\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2184:13)
        at C:\Users\Usuario\Desktop\whaticket-master\backend\node_modules\sequelize\lib\dialects\abstract\query-generator.js:2173:25
        at Array.forEach (<anonymous>)

**Comment by KatiaSishost** [comment]
solved, my bad!

**Comment by ramphy** [comment]
How did you solve it?
