### ISSUE TITLE
erro ao buildar o frontend [vps hostinger]

### ISSUE THREAD

**Issue by jefersonaguilar** [canove/whaticket#211]
### Quando eu vou utilizar o npm run build no frontend acontece o seguinte erro.

> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
> 2 info using npm@6.14.13
> 3 info using node@v14.17.2
> 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> 5 info lifecycle frontend@0.1.0~prebuild: frontend@0.1.0
> 6 info lifecycle frontend@0.1.0~build: frontend@0.1.0
> 7 verbose lifecycle frontend@0.1.0~build: unsafe-perm in lifecycle true
> 8 verbose lifecycle frontend@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/deploy/whaticket/frontend/node_module>9 verbose lifecycle frontend@0.1.0~build: CWD: /home/deploy/whaticket/frontend
> 10 silly lifecycle frontend@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
> 11 silly lifecycle frontend@0.1.0~build: Returned: code: 1  signal: null
> 12 info lifecycle frontend@0.1.0~build: Failed to exec build script
> 13 verbose stack Error: frontend@0.1.0 build: `react-scripts build`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:375:28)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:375:28)
> 13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> 14 verbose pkgid frontend@0.1.0
> 15 verbose cwd /home/deploy/whaticket/frontend
> 16 verbose Linux 5.4.0
> 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> 18 verbose node v14.17.2
> 19 verbose npm  v6.14.13
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error frontend@0.1.0 build: `react-scripts build`
> 22 error Exit status 1
> 23 error Failed at the frontend@0.1.0 build script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]

**Comment by dev-oneclick** [comment]
Quais as configurações da sua vps?

**Comment by ertprs** [comment]
> ### Quando eu vou utilizar o npm run build no frontend acontece o seguinte erro.
> > 0 info it worked if it ends with ok
> > 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
> > 2 info using npm@6.14.13
> > 3 info using node@v14.17.2
> > 4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
> > 5 info lifecycle frontend@0.1.0~prebuild: frontend@0.1.0
> > 6 info lifecycle frontend@0.1.0~build: frontend@0.1.0
> > 7 verbose lifecycle frontend@0.1.0~build: unsafe-perm in lifecycle true
> > 8 verbose lifecycle frontend@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/deploy/whaticket/frontend/node_module>9 verbose lifecycle frontend@0.1.0~build: CWD: /home/deploy/whaticket/frontend
> > 10 silly lifecycle frontend@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
> > 11 silly lifecycle frontend@0.1.0~build: Returned: code: 1  signal: null
> > 12 info lifecycle frontend@0.1.0~build: Failed to exec build script
> > 13 verbose stack Error: frontend@0.1.0 build: `react-scripts build`
> > 13 verbose stack Exit status 1
> > 13 verbose stack     at EventEmitter. (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> > 13 verbose stack     at EventEmitter.emit (events.js:375:28)
> > 13 verbose stack     at ChildProcess. (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> > 13 verbose stack     at ChildProcess.emit (events.js:375:28)
> > 13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
> > 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
> > 14 verbose pkgid frontend@0.1.0
> > 15 verbose cwd /home/deploy/whaticket/frontend
> > 16 verbose Linux 5.4.0
> > 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
> > 18 verbose node v14.17.2
> > 19 verbose npm  v6.14.13
> > 20 error code ELIFECYCLE
> > 21 error errno 1
> > 22 error frontend@0.1.0 build: `react-scripts build`
> > 22 error Exit status 1
> > 23 error Failed at the frontend@0.1.0 build script.
> > 23 error This is probably not a problem with npm. There is likely additional logging output above.
> > 24 verbose exit [ 1, true ]

Provavelmente é a a quantidade de memória da sua VPS, eu tive um problema desse no inicio, acabei pedindo o reembolso e contratei outra VPS na [ServeSP](https://central.serversp.com/aff.php?aff=528
), até o momento não estou tendo problemas com eles, tenho dois servidores contratados lá Windows e Linux e até o momento não tive nenhum problema.

Outro detalhe para que quiser contratar a VPS na [ServeSP](https://central.serversp.com/aff.php?aff=528
) Linux, eu estou instalando o painel [aapanel](https://www.aapanel.com/index.html) opensource, muito bom esse painel, tenho configurado tudo nele.
![image](https://user-images.githubusercontent.com/62783690/127715260-05bde785-06a2-4d5d-9f45-55810bf6a356.png)
Se precisar de qualquer ajuda na instalação do projeto [Whaticket ](https://github.com/canove/whaticket) e configuração da VPS com o painel, estou a disposição na parte da noite pode me chamar no discord só me adicionar patriciosilva#2113 ou [whats ](https://api.whatsapp.com/send?phone=+5512991372279&text=Olá,%20tudo bem?).

Outro detalhe estou utilizando o [cloudflare](https://www.cloudflare.com/pt-br/) para gerar os certificado SSL e redirecionar a VPS para o domínio.
