### ISSUE TITLE
Parou de conectar nas conexões, escaneia o código porém ele não conecta.

### ISSUE THREAD

**Issue by PauloBettin** [canove/whaticket#213]
Error: Evaluation failed: ReferenceError: webpackChunkbuild is not defined

**Comment by crashbr** [comment]
Estou com o mesmo problema aqui.

Tentei atualizar a versão do node para a mais recente e reiniciei tanto back como front porém sem sucesso.

**Comment by PauloBettin** [comment]
Tentei o mesmo procedimento e também atualizei o node para 16x mas sem sucesso em resolver o problema.

**Comment by KatiaSishost** [comment]
upgrade the whatsappweb.js
