### ISSUE TITLE
não está enviando áudio

### ISSUE THREAD

**Issue by samueldietrick** [canove/whaticket#215]
o sistema em si recebe áudio e da para escutar cada um deles, porém ao clicar no ícone de microfone para enviar áudio aparece no topo uma notificação vermelha escrito "An error occurred", tentei corrigir mas sem sucesso!
obs: se eu conseguir realizar a correção disponibilizarei aqui para todos.

**Comment by Queenzao** [comment]
Verifica se as permissões do navegador para Microfone estão habilitadas e conecta algum microfone na entrada ROSA do seu computador, caso contrário esse erro vai aparecer mesmo.

**Comment by rodrigofsantos** [comment]
O envio de audo so funciona com SSL ou seja voce precisa seguir o procedimento de instalação e ativar o SSL para envio audios !
