### ISSUE TITLE
Separar atendimento por departamento

### ISSUE THREAD

**Issue by arleylmotta** [canove/whaticket#220]
Bom dia!

Aqui fica complicado, porque todos podem ver todas as conversas.
Na aba configuração de usuário, conseguem inserir configuração para bloquear mensagens para alguns usuários? 

Editar Usuário > Adicionar Cargo > Operador nvl 1

Ai eu entro na configuração do Operador nlv 1 onde terá várias opções, entre elas:

![adsdqw](https://user-images.githubusercontent.com/89529693/130806451-1efb12f9-f0df-4071-a0d1-eb3a836735df.PNG)
Modelo do Digisac

Porque aqui trabalhamos separados por departamentos: compras, rh, financeiro...
É uma excelente aplicação, no entanto do jeito que está todos podem ver todas as conversas. Há a possibilidade de atualizar para o administrados definir essas configurações?

**Comment by lisboadouglas** [comment]
Olá, tudo bem?

O nível dos usuários está atribuído como **user**?
Caso o usuário esteja setado como admin, ele poderá visualizar todas as conversas, de todas as filas.

Você atribuiu as filas que o usuário poderá atender?
Atribua filas somente ao que o usuário poderá participar. Desta forma, ele não poderá visualizar as conversas de outros departamentos.

Segue alguns exemplos da configuração que estou utilizando:

![print-tela-usuairo](https://user-images.githubusercontent.com/57302857/130808704-796cc486-25c6-46d2-a04f-141401063a43.png)
![print-tela-usuairo2](https://user-images.githubusercontent.com/57302857/130808712-3c0ebb62-561e-4568-8abf-631f8c012c93.png)

**Comment by oliveiraViny22** [comment]
Fala @Emersonsanch , consegue compartilhar seu projeto?

**Comment by oliveiraViny22** [comment]
Percebi que no caso de fazer mais de uma conexão, ou seja, utilizar dois números de whatsapp, ele mistura as conversas e, em alguns casos, nem entrega na fila correta... mas exibe na notificação de nova conversa, permitindo que seja visualizado com o adm.
