### ISSUE TITLE
Abrir automaticamente

### ISSUE THREAD

**Issue by arleylmotta** [canove/whaticket#221]
Boa tarde!

Estou rodando o WhaTicket em uma máquina virtual no meu computador e os outros usuários conectam pela rede. No entanto sempre que inicio no início do dia tenho que abrir a máquina virtual, abrir o putty e rodaR o npm start dentro da pasta backend e abrir outro putty e rodar npm dentro da pasta frontend.

Tentei rodar o pm2 como cita na instalação, ele fica online, mas quando inicio a máquina nada acontece:

![01](https://user-images.githubusercontent.com/89529693/130845461-5bfc7c31-372e-4a39-a6f5-5f51e0d1da4c.PNG)

Existe alguma outra forma pra iniciar mais fácil do que o processo que estou usando de abrir 2 putty? Algo como node server.js por exemplo

**Comment by arleylmotta** [comment]
> Passei pelo mesmo problema ! teste todas as urls possíveis mas sem solução acabei por montar um script que inicia automaticamente e depois checa se esta online !

Compartilha por favor.

**Comment by renat473** [comment]
Você precisa editar o arquivo server.js nele tem a porta que sendo utilizada no start do pm2 que 3333, basta alterar ela.

> Testei e mesmo assim não funcionou. A máquina inicia, dou o comando pm2 list, o backend e o frontend aparecem online, mas quando vou no navegador acessar:
> 
> ![Capturar](https://user-images.githubusercontent.com/89529693/130889551-0ad190e7-fa57-4512-8928-822627288252.PNG)

**Comment by arleylmotta** [comment]
Essa é a pergunta que vale um milhão. Como faz isso?

**Comment by ertprs** [comment]
> Essa é a pergunta que vale um milhão. Como faz isso?

Olá, @arleylmotta!
Qual a versão do linux instalado nessa VM?

**Comment by arleylmotta** [comment]
> > Essa é a pergunta que vale um milhão. Como faz isso?
> 
> Olá, @arleylmotta!
> Qual a versão do linux instalado nessa VM?

ubuntu-20.04.2-live-server-amd64

**Comment by ertprs** [comment]
Você já experimentou usar o forever? 

Forever é um módulo NodeJs muito bom para fazer exatamente isso.

Você pode instalar para sempre usando o npm desta forma:
sudo npm install -g forever

Em seguida, use o seguinte comando para executar os scripts do backend e frontend.

no backend
 forever start dist/server.js 

no frontend
forever start server.js 

Você está pronto para ir. Além disso, você pode executar

para ver todos os scripts em execução. 
forever list

Você pode encerrar qualquer script específico digitando
forever stop [pid]
onde [pid]é o ID do processo do script que você obterá do listcomando. 

Para parar todos os scripts, você pode digitar
forever stop all

mais informações: https://stackoverflow.com/questions/12701259/how-to-make-a-node-js-application-run-permanently

**Comment by arleylmotta** [comment]
> Você já experimentou usar o forever?
> 
> Forever é um módulo NodeJs muito bom para fazer exatamente isso.
> 
> Você pode instalar para sempre usando o npm desta forma:
> sudo npm install -g forever
> 
> Em seguida, use o seguinte comando para executar os scripts do backend e frontend.
> 
> no backend
> forever start dist/server.js
> 
> no frontend
> forever start server.js
> 
> Você está pronto para ir. Além disso, você pode executar
> 
> para ver todos os scripts em execução.
> forever list
> 
> Você pode encerrar qualquer script específico digitando
> forever stop [pid]
> onde [pid]é o ID do processo do script que você obterá do listcomando.
> 
> Para parar todos os scripts, você pode digitar
> forever stop all
> 
> mais informações: https://stackoverflow.com/questions/12701259/how-to-make-a-node-js-application-run-permanently

![Capturar](https://user-images.githubusercontent.com/89529693/132150391-63b22056-3f96-495b-87d7-e999938a7167.PNG)

Não funcionou. Por mim aqui também é tranquilo sempre iniciar com o npm start. O problema é quando eu não estou, aí para outra pessoa iniciar fica complicado. Salvei até o comando num bloco de nota para a pessoa copiar e colar, mas ainda assim acham complicado. Preciso muito de um que eu só precise iniciar a máquina virtual e ele rode automaticamente. Vocês sabem quanto fica em R$ para deixar esse sistema rodando online no AWS no medium, pq no micro que da 1 ano grátis ele não roda.
