### ISSUE TITLE
npm run build

### ISSUE THREAD

**Issue by udee297** [canove/whaticket#222]
hi i got this error when im trying to npm run buid @ backend folder

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.14
3 info using node@v14.17.5
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle backend@1.0.0~prebuild: backend@1.0.0
6 info lifecycle backend@1.0.0~build: backend@1.0.0
7 verbose lifecycle backend@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle backend@1.0.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/b0lt3r/whaticket/backend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle backend@1.0.0~build: CWD: /home/b0lt3r/whaticket/backend
10 silly lifecycle backend@1.0.0~build: Args: [ '-c', 'tsc' ]
11 silly lifecycle backend@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle backend@1.0.0~build: Failed to exec build script
13 verbose stack Error: backend@1.0.0 build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid backend@1.0.0
15 verbose cwd /home/b0lt3r/whaticket/backend
16 verbose Linux 5.4.0-81-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 2
22 error backend@1.0.0 build: `tsc`
22 error Exit status 2
23 error Failed at the backend@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

im using node v14.17.5 and npm 6.14.14

**Comment by udee297** [comment]
is it because im using ubuntu 20?

**Comment by udee297** [comment]
i tried in 3 different fresh install vm, all got same error,, using both ubuntu 20 and 18

**Comment by ramphy** [comment]
Hi dude, can you send your history command? To check all previous

**Comment by udee297** [comment]
Hi,

It seems its working fine even though theres an error

**Comment by guilherme-assert** [comment]
deploy@whatsapp:~/whaticket/backend$ npm run build

> backend@1.0.0 build /home/deploy/whaticket/backend
> tsc

src/__tests__/unit/User/AuthUserService.spec.ts:46:14 - error TS2571: Object is of type 'unknown'.

46       expect(err.statusCode).toBe(401);
                ~~~

src/__tests__/unit/User/AuthUserService.spec.ts:47:14 - error TS2571: Object is of type 'unknown'.

47       expect(err.message).toBe("ERR_INVALID_CREDENTIALS");
                ~~~

src/__tests__/unit/User/AuthUserService.spec.ts:65:14 - error TS2571: Object is of type 'unknown'.

65       expect(err.statusCode).toBe(401);
                ~~~

src/__tests__/unit/User/AuthUserService.spec.ts:66:14 - error TS2571: Object is of type 'unknown'.

66       expect(err.message).toBe("ERR_INVALID_CREDENTIALS");
                ~~~

src/__tests__/unit/User/CreateUserService.spec.ts:44:14 - error TS2571: Object is of type 'unknown'.

44       expect(err.statusCode).toBe(400);
                ~~~

src/controllers/ContactController.ts:56:24 - error TS2571: Object is of type 'unknown'.

56     throw new AppError(err.message);
                          ~~~

src/controllers/ContactController.ts:102:24 - error TS2571: Object is of type 'unknown'.

102     throw new AppError(err.message);
                           ~~~

src/libs/wbot.ts:128:20 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

128       logger.error(err);
                       ~~~


src/libs/wbot.ts:150:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

150     logger.error(err);
                     ~~~


src/services/QueueService/CreateQueueService.ts:59:24 - error TS2571: Object is of type 'unknown'.

59     throw new AppError(err.message);
                          ~~~

src/services/QueueService/UpdateQueueService.ts:63:24 - error TS2571: Object is of type 'unknown'.

63     throw new AppError(err.message);
                          ~~~

src/services/UserServices/CreateUserService.ts:51:24 - error TS2571: Object is of type 'unknown'.

51     throw new AppError(err.message);
                          ~~~

src/services/UserServices/UpdateUserService.ts:44:24 - error TS2571: Object is of type 'unknown'.

44     throw new AppError(err.message);
                          ~~~

src/services/WbotServices/CheckIsValidContact.ts:16:9 - error TS2571: Object is of type 'unknown'.

16     if (err.message === "invalidNumber") {
           ~~~

src/services/WbotServices/StartWhatsAppSession.ts:24:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

24     logger.error(err);
                    ~~~


src/services/WbotServices/wbotMessageListener.ts:89:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

89     logger.error(err);
                    ~~~


src/services/WbotServices/wbotMonitor.ts:27:22 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

27         logger.error(err);
                        ~~~


src/services/WbotServices/wbotMonitor.ts:46:22 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

46         logger.error(err);
                        ~~~


src/services/WbotServices/wbotMonitor.ts:61:22 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

61         logger.error(err);
                        ~~~


src/services/WbotServices/wbotMonitor.ts:73:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

73     logger.error(err);
                    ~~~


src/services/WhatsappService/CreateWhatsAppService.ts:48:24 - error TS2571: Object is of type 'unknown'.

48     throw new AppError(err.message);
                          ~~~

src/services/WhatsappService/UpdateWhatsAppService.ts:50:24 - error TS2571: Object is of type 'unknown'.

50     throw new AppError(err.message);
                          ~~~


Found 22 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! backend@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the backend@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2021-08-30T11_54_16_415Z-debug.log

**Comment by guilherme-assert** [comment]
deploy@whatsapp:~/whaticket/backend$ tail /home/deploy/.npm/_logs/2021-08-30T11_54_16_415Z-debug.log
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v14.17.5
19 verbose npm  v6.14.14
20 error code ELIFECYCLE
21 error errno 2
22 error backend@1.0.0 build: `tsc`
22 error Exit status 2
23 error Failed at the backend@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by guilherme-assert** [comment]
deploy@whatsapp:~/whaticket/frontend$ npm run build

> frontend@0.1.0 build /home/deploy/whaticket/frontend
> react-scripts build

Creating an optimized production build...


<--- Last few GCs --->

[23579:0x50b5ad0]   316301 ms: Mark-sweep (reduce) 489.0 (495.4) -> 488.8 (497.1) MB, 2513.0 / 0.1 ms  (average mu = 0.108, current mu = 0.005) allocation failure scavenge might not succeed
[23579:0x50b5ad0]   318594 ms: Mark-sweep (reduce) 489.8 (499.1) -> 489.7 (499.9) MB, 2290.0 / 0.0 ms  (average mu = 0.059, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa25510 node::Abort() [node]
 2: 0x9664d3 node::FatalError(char const*, char const*) [node]
 3: 0xb9a8be v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xb9ac37 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd56ca5  [node]
 6: 0xd5782f  [node]
 7: 0xd6566b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd6922c v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 9: 0xd3790b v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
10: 0x107fbef v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
11: 0x1426919  [node]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2021-08-30T12_19_09_636Z-debug.log

**Comment by udee297** [comment]
I got mine working fine even though theres an error

**Comment by guilherme-assert** [comment]
Could you share how you made this happen?

**Comment by guilherme-assert** [comment]
What is the specification of the machine you are using?

**Comment by udee297** [comment]
i just do the steps and ignore this error

**Comment by guilherme-assert** [comment]
Yes, I even tried but it didn't open!
What is the specification of the machine you are using?
