### ISSUE TITLE
npm run build backend fail

### ISSUE THREAD

**Issue by KatiaSishost** [canove/whaticket#223]
npm run build

> backend@1.0.0 build
> tsc

src/__tests__/unit/User/AuthUserService.spec.ts:46:14 - error TS2571: Object is of type 'unknown'.

46       expect(err.statusCode).toBe(401);
                ~~~

src/__tests__/unit/User/AuthUserService.spec.ts:47:14 - error TS2571: Object is of type 'unknown'.

47       expect(err.message).toBe("ERR_INVALID_CREDENTIALS");
                ~~~

src/__tests__/unit/User/AuthUserService.spec.ts:65:14 - error TS2571: Object is of type 'unknown'.

65       expect(err.statusCode).toBe(401);
                ~~~

src/__tests__/unit/User/AuthUserService.spec.ts:66:14 - error TS2571: Object is of type 'unknown'.

66       expect(err.message).toBe("ERR_INVALID_CREDENTIALS");
                ~~~

src/__tests__/unit/User/CreateUserService.spec.ts:44:14 - error TS2571: Object is of type 'unknown'.

44       expect(err.statusCode).toBe(400);
                ~~~

src/controllers/ContactController.ts:56:24 - error TS2571: Object is of type 'unknown'.

56     throw new AppError(err.message);
                          ~~~

src/controllers/ContactController.ts:102:24 - error TS2571: Object is of type 'unknown'.

102     throw new AppError(err.message);
                           ~~~

src/libs/wbot.ts:128:20 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

128       logger.error(err);
                       ~~~

src/libs/wbot.ts:150:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

150     logger.error(err);
                     ~~~


src/services/QueueService/CreateQueueService.ts:59:24 - error TS2571: Object is of type 'unknown'.

59     throw new AppError(err.message);
                          ~~~

src/services/QueueService/UpdateQueueService.ts:63:24 - error TS2571: Object is of type 'unknown'.

63     throw new AppError(err.message);
                          ~~~

src/services/UserServices/CreateUserService.ts:51:24 - error TS2571: Object is of type 'unknown'.

51     throw new AppError(err.message);
                          ~~~

src/services/UserServices/UpdateUserService.ts:44:24 - error TS2571: Object is of type 'unknown'.

44     throw new AppError(err.message);
                          ~~~

src/services/WbotServices/CheckIsValidContact.ts:16:9 - error TS2571: Object is of type 'unknown'.

16     if (err.message === "invalidNumber") {
           ~~~

src/services/WbotServices/StartWhatsAppSession.ts:24:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

24     logger.error(err);
                    ~~~


src/services/WbotServices/wbotMessageListener.ts:89:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

89     logger.error(err);
                    ~~~

src/services/WbotServices/wbotMonitor.ts:27:22 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

27         logger.error(err);
                        ~~~


src/services/WbotServices/wbotMonitor.ts:46:22 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

46         logger.error(err);
                        ~~~

src/services/WbotServices/wbotMonitor.ts:61:22 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

61         logger.error(err);
                        ~~~


src/services/WbotServices/wbotMonitor.ts:73:18 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'object'.
  Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
    Argument of type 'unknown' is not assignable to parameter of type 'string'.

73     logger.error(err);
                    ~~~

src/services/WhatsappService/CreateWhatsAppService.ts:48:24 - error TS2571: Object is of type 'unknown'.

48     throw new AppError(err.message);
                          ~~~

src/services/WhatsappService/UpdateWhatsAppService.ts:50:24 - error TS2571: Object is of type 'unknown'.

50     throw new AppError(err.message);
                          ~~~

Found 22 errors.

**Comment by ertprs** [comment]
> npm run build
> 
> > backend@1.0.0 build
> > tsc
> 
> src/**tests**/unit/User/AuthUserService.spec.ts:46:14 - error TS2571: Object is of type 'unknown'.
> 
> 46 expect(err.statusCode).toBe(401);
> ~~~
> 
> src/**tests**/unit/User/AuthUserService.spec.ts:47:14 - error TS2571: Object is of type 'unknown'.
> 
> 47 expect(err.message).toBe("ERR_INVALID_CREDENTIALS");
> ~~~
> 
> src/**tests**/unit/User/AuthUserService.spec.ts:65:14 - error TS2571: Object is of type 'unknown'.
> 
> 65 expect(err.statusCode).toBe(401);
> ~~~
> 
> src/**tests**/unit/User/AuthUserService.spec.ts:66:14 - error TS2571: Object is of type 'unknown'.
> 
> 66 expect(err.message).toBe("ERR_INVALID_CREDENTIALS");
> ~~~
> 
> src/**tests**/unit/User/CreateUserService.spec.ts:44:14 - error TS2571: Object is of type 'unknown'.
> 
> 44 expect(err.statusCode).toBe(400);
> ~~~
> 
> src/controllers/ContactController.ts:56:24 - error TS2571: Object is of type 'unknown'.
> 
> 56 throw new AppError(err.message);
> ~~~
> 
> src/controllers/ContactController.ts:102:24 - error TS2571: Object is of type 'unknown'.
> 
> 102 throw new AppError(err.message);
> ~~~
> 
> src/libs/wbot.ts:128:20 - error TS2769: No overload matches this call.
> Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'object'.
> Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'string'.
> 
> 128 logger.error(err);
> ~~~
> 
> src/libs/wbot.ts:150:18 - error TS2769: No overload matches this call.
> Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'object'.
> Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'string'.
> 
> 150 logger.error(err);
> ~~~
> 
> src/services/QueueService/CreateQueueService.ts:59:24 - error TS2571: Object is of type 'unknown'.
> 
> 59 throw new AppError(err.message);
> ~~~
> 
> src/services/QueueService/UpdateQueueService.ts:63:24 - error TS2571: Object is of type 'unknown'.
> 
> 63 throw new AppError(err.message);
> ~~~
> 
> src/services/UserServices/CreateUserService.ts:51:24 - error TS2571: Object is of type 'unknown'.
> 
> 51 throw new AppError(err.message);
> ~~~
> 
> src/services/UserServices/UpdateUserService.ts:44:24 - error TS2571: Object is of type 'unknown'.
> 
> 44 throw new AppError(err.message);
> ~~~
> 
> src/services/WbotServices/CheckIsValidContact.ts:16:9 - error TS2571: Object is of type 'unknown'.
> 
> 16 if (err.message === "invalidNumber") {
> ~~~
> 
> src/services/WbotServices/StartWhatsAppSession.ts:24:18 - error TS2769: No overload matches this call.
> Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'object'.
> Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'string'.
> 
> 24 logger.error(err);
> ~~~
> 
> src/services/WbotServices/wbotMessageListener.ts:89:18 - error TS2769: No overload matches this call.
> Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'object'.
> Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'string'.
> 
> 89 logger.error(err);
> ~~~
> 
> src/services/WbotServices/wbotMonitor.ts:27:22 - error TS2769: No overload matches this call.
> Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'object'.
> Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'string'.
> 
> 27 logger.error(err);
> ~~~
> 
> src/services/WbotServices/wbotMonitor.ts:46:22 - error TS2769: No overload matches this call.
> Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'object'.
> Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'string'.
> 
> 46 logger.error(err);
> ~~~
> 
> src/services/WbotServices/wbotMonitor.ts:61:22 - error TS2769: No overload matches this call.
> Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'object'.
> Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'string'.
> 
> 61 logger.error(err);
> ~~~
> 
> src/services/WbotServices/wbotMonitor.ts:73:18 - error TS2769: No overload matches this call.
> Overload 1 of 2, '(obj: object, msg?: string | undefined, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'object'.
> Overload 2 of 2, '(msg: string, ...args: any[]): void', gave the following error.
> Argument of type 'unknown' is not assignable to parameter of type 'string'.
> 
> 73 logger.error(err);
> ~~~
> 
> src/services/WhatsappService/CreateWhatsAppService.ts:48:24 - error TS2571: Object is of type 'unknown'.
> 
> 48 throw new AppError(err.message);
> ~~~
> 
> src/services/WhatsappService/UpdateWhatsAppService.ts:50:24 - error TS2571: Object is of type 'unknown'.
> 
> 50 throw new AppError(err.message);
> ~~~
> 
> Found 22 errors.

______________________________________________________________________________________________________________________________________
comments above the line with // @ts-ignore on all reported errors, this allows the TypeScript compiler to ignore the line below it.

check if it works

_______________________________________________________________________________________________________________________________________
comenta acima da linha  com // @ ts-ignore em todos os erros informados, isso permite que o compilador TypeScript ignore a linha abaixo dele.

verifica se dar certo

**Comment by PauloBettin** [comment]
Mesmo comentando não funciona.

Este erro está dentro de um IF:

src/services/WbotServices/CheckIsValidContact.ts:16:9 - error TS2571: Object is of type 'unknown'.

16 if (err.message === "invalidNumber") {

**Comment by rodrigofsantos** [comment]
Esse erro ja aconteceu comigo e era cache removi e refiz o npm install depois o run build e funcinou pois eu comentei a linha e apareceu outra e outra e outra e acabou que ficou meio que um looping kkkk
