### ISSUE TITLE
sometimes new tickets grabb old closed tickets messages

### ISSUE THREAD

**Issue by soporte-islanetworks** [canove/whaticket#224]
hey, when a customer messages me and it creates a new ticket , sometimes it grabs the past conversation of that same customer, even if the past conversation its  already closed

**Comment by ricco-douro** [comment]
If the client calls within 2 hours of closing, the system reopens old ticket (as it assumes it is still the same conversation. After two hours it opens a new ticket

**Comment by cristovammartins** [comment]
No meu caso eu removi isso do código :+1 : )

**Comment by soporte-islanetworks** [comment]
Obrigado, posso saber onde está o código que define o cronômetro de 2 horas?
