### ISSUE TITLE
Backend dont sent video files.

### ISSUE THREAD

**Issue by PauloBettin** [canove/whaticket#225]
Backend stopped to sent video files.

"message: "ERR_SENDING_WAPP_MSG"
    statusCode: 400"

**Comment by ricco-douro** [comment]
Sometimes the connection goes stale. Restart the backend. 
Make sure you are using google chrome headless, because Chromium (Puppeteer default) does not have the required Ffmpeg library

**Comment by PauloBettin** [comment]
How to change the Puppeteer to use Chrome (Full) on whaticket @ricco-douro? Sorry for my ignorance.

**Comment by ricco-douro** [comment]
backend
.env

CHROME_BIN=C:\Program Files\Google\Chrome\Application\chrome.exe
or
CHROME_BIN=/usr/bin/google-chrome

If you dont know where Chrome is installed:

whereis google-chrome

**Comment by swalayan-hasbuna** [comment]
NODE_ENV=
BACKEND_URL=http://192.168.1.9			
FRONTEND_URL=http://192.168.1.9:3000	
PROXY_PORT=8080
PORT=8080

DB_DIALECT=
DB_HOST=localhost
DB_USER=root
DB_PASS=
DB_NAME=WA-HASBUNA					

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756

IO_REDIS_SERVER=
IO_REDIS_PORT=

CHROME_BIN = "C:\Program Files\Google\Chrome\Application\chrome.exe"

**Comment by PauloBettin** [comment]
Many thanks guys, i will test this soon!
