### ISSUE TITLE
How to reset whaticket via terminal putty (lost admin access)

### ISSUE THREAD

**Issue by rsrljardim** [canove/whaticket#227]
Hello, after rebooting the AWS VPS, the system start up automatically with success, but, the admin user/password doesnt work anymore. Also any user login dosent work.

My question is: how to reset the whaticket to start over?

**Comment by ramphy** [comment]
Hi dude, can you check if the mysql is working? When the mysql db is stopped, the admin access "doesnt work"

**Comment by JEFERSON-ASSIS** [comment]
how do I check if mysql is working

**Comment by ramphy** [comment]
I'm using docker: 
`sudo docker ps -al`

CONTAINER ID   IMAGE            COMMAND                  CREATED         STATUS       PORTS                                       NAMES
f1d7788a8fdd   mariadb:latest   "docker-entrypoint.s…"   12 months ago   Up 3 weeks   0.0.0.0:3306->3306/tcp, :::3306->3306/tcp   whaticketdb

**Comment by rsrljardim** [comment]
It looks like mine is up, see pic below:
![image](https://user-images.githubusercontent.com/50372232/131888786-adcb24ae-cdc5-47dc-a450-ab3ff862e724.png)

CONTAINER ID   IMAGE            COMMAND                  CREATED        STATUS                                                                                               PORTS                                       NAMES
dbab782f6c01   mariadb:latest   "docker-entrypoint.s…"   15 hours ago   Up 3 hours
0.0.0.0:3306->3306/tcp, :::3306->3306/tcp   whaticketdb

But still, no access to whatticket.

**Comment by rsrljardim** [comment]
Any ideia on how to solve this? I created a New VPs but the same error again...

**Comment by ramphy** [comment]
Verify my dear if the backend is running:

` pm2 status`

**Comment by rsrljardim** [comment]
So, i started all over again and man, for someone who doesnt have linux knowledge its complicated. Anyways, i started all over again, from scratch.

Build a new machine and followed all steps. 

I could reach the website with this "new" issue:

![image](https://user-images.githubusercontent.com/50372232/132120077-90bf948f-7ef4-41d8-88cb-bd7a232d4849.png)

What the hell... i need help!
