### ISSUE TITLE
Resposta Rápida

### ISSUE THREAD

**Issue by AlanMartines** [canove/whaticket#228]
Opa, tudo bom,

Seu sistema tem o recurso de resposta rápida?

**Comment by ertprs** [comment]
> Opa, tudo bom,
> 
> Seu sistema tem o recurso de resposta rápida?

@AlanMartines , blz.
 Ainda não tem nesse projeto original, mas está sendo implementada, eu fiz um fork desse projeto na minha conta,
esse é o link: https://github.com/ertprs/whaticket_mod do projeto esse já está com as respostas rápidas.

Deixei hospedado na vps os dois projetos para teste:

O WhaTicket projeto original: https://github.com/canove/whaticket nesse link: https://whaticket.cmawhats.online/login

e o projeto com algumas alterações já feitas nesse link: https://whaticketmod.cmawhats.online/login

Dados para entrar em qualquer um dos projetos acima: 

Usuário: admin@admin.com 
senha: admin

Se quiser testá-lo, sinta-se a vontade e lembre-se de sair da sessão e excluir todos os atendimentos e contatos após os testes.

**Comment by ramphy** [comment]
Nice mobile implementation!!!

How we can get it dude? Thank you!

**Comment by AlanMartines** [comment]
> > Opa, tudo bom,
> > Seu sistema tem o recurso de resposta rápida?
> 
> @AlanMartines , blz.
> Ainda não tem nesse projeto original, mas está sendo implementada, eu fiz um fork desse projeto na minha conta,
> esse é o link: https://github.com/ertprs/whaticket_mod do projeto esse já está com as respostas rápidas.
> 
> Deixei hospedado na vps os dois projetos para teste:
> 
> O WhaTicket projeto original: https://github.com/canove/whaticket nesse link: https://whaticket.cmawhats.online/login
> 
> e o projeto com algumas alterações já feitas nesse link: https://whaticketmod.cmawhats.online/login
> 
> Dados para entrar em qualquer um dos projetos acima:
> 
> Usuário: [admin@admin.com](mailto:admin@admin.com)
> senha: admin
> 
> Se quiser testá-lo, sinta-se a vontade e lembre-se de sair da sessão e excluir todos os atendimentos e contatos após os testes.

Vlw, obrigado...
