### ISSUE TITLE
Help with heroku please

### ISSUE THREAD

**Issue by Max2287** [canove/whaticket#23]
Hi!
First: I thank you very much for your project.
Second: Could you help me upload this project to heroku?
I am trying to upload it but heroku returns the error: Application not supported by 'heroku / nodejs' buildpack
I understand that it may be because the package.json is not found in the root. But in this case there are 2 package.json. One on frontend and one on backend.

**Comment by canove** [comment]
Hey man! Thanks for testing Whaticket and welcome. 

I'm not very familiar with Heroku, but maybe you'll need to create two Heroku instances, one for backend and another one for frontend, since they are two separated thinks.

**Comment by leobaldoneto** [comment]
You need need an mysql instance and 2 heroku instances, one for the backend and another for the frontend.
