### ISSUE TITLE
Direcionamento de mensagem para equipe

### ISSUE THREAD

**Issue by rsrljardim** [canove/whaticket#231]
Olá! Vocês tem em mente a ideia de implementar o direcionamento de mensagens para grupo, após uma seleção por números do cliente, como por exemplo: 
1 - Vendas
2 - Suporte
3 - Ouvidora

Parabéns pelo projeto, estou encantado com os testes que estou fazendo no site mod que disponibilizou.

**Comment by KatiaSishost** [comment]
Olá continuei fazendo testes pois a opção é e funciona perfeita como todo o resto do projeto <3 !
