### ISSUE TITLE
Erro em alguns usuários

### ISSUE THREAD

**Issue by arleylmotta** [canove/whaticket#232]
Boa tarde!

Hoje em alguns usuários começou apresentar um erro quando envia a mensagem.

![A572D572-5F44-4046-A660-77C0FC35DA4D](https://user-images.githubusercontent.com/89529693/132239996-1587a7be-6d2d-451a-9a58-9263a3d0b061.jpeg)

**Comment by ertprs** [comment]
@arleylmotta , corrigi no projeto, foi um erro meu mesmo.

**Comment by rsrljardim** [comment]
Como superou essa dificuldade ertprs? estou com essa mesma dificuldade!

**Comment by ricco-douro** [comment]
Também encontrei esse erro, esporadicamente.... Como se resolve?

**Comment by arleylmotta** [comment]
> @arleylmotta , corrigi no projeto, foi um erro meu mesmo.

Ok, obrigado!

No dia que abrir esse chamado, eu estava usando o Google Chrome, aí testei no Mozilla Firefox e até agora não apresentou o problema, mas irei atualizar pelo projeto.

**Comment by ricco-douro** [comment]
eu tive esse problema sempre que o usuário tinha o google translator ativado. Das vezes que desabilitei o tradutor google para essa página, o problema desapareceu (O mozilla Firefox não tem essa opção habilitada). Eu acredito que é porque o tradutor está a traduzir as rotas do app (ingressos em vez de tickets) mas estou curioso em saber o que o @ertprs entendeu que seria um erro que ele causou

**Comment by arleylmotta** [comment]
> eu tive esse problema sempre que o usuário tinha o google translator ativado. Das vezes que desabilitei o tradutor google para essa página, o problema desapareceu (O mozilla Firefox não tem essa opção habilitada). Eu acredito que é porque o tradutor está a traduzir as rotas do app (ingressos em vez de tickets) mas estou curioso em saber o que o @ertprs entendeu que seria um erro que ele causou

Se eu não entendi errado ele é um contribuidor e em algum momento causou esse erro dentro do projeto 

![E7F41149-F3D1-4C20-8E53-7F2DA8A358E7](https://user-images.githubusercontent.com/89529693/132591877-35159728-d7df-4b6a-8b3b-04fb3fcd06b3.jpeg)

Imagino que seja necessário rodar o código de atualização para corrigir o problema. Já que ele citou que já resolveu dentro do projeto 

![FB7CB8EA-A88F-4DEC-8FAD-CE1FEAB56DD3](https://user-images.githubusercontent.com/89529693/132591976-dde7fd77-48d5-46dd-92bc-2a780cbf85da.jpeg)

**Comment by swalayan-hasbuna** [comment]
![image](https://user-images.githubusercontent.com/74512439/133053381-71001ce9-cf83-4767-a4f8-6dcaac4d7f4b.png)

**Comment by swalayan-hasbuna** [comment]
how to add print module action?
can you help me ?
