### ISSUE TITLE
Erro ao enviar mensagens do Whatsapp. Verifique a página de conexões.

### ISSUE THREAD

**Issue by VictorHungria** [canove/whaticket#235]
Boa tarde,

o Whaticket não está conseguindo enviar mensagem, o que até então dava. Consta como problema que é erro de conexão, porém recebe mensagens normalmente. Alguém tem ideia de como resolve esse bug?

![sdfsdf](https://user-images.githubusercontent.com/89818055/132546951-bd0e6fa6-77f7-43c1-9878-a232280863a4.png)

**Comment by VictorHungria** [comment]
Erro do console: 
![image](https://user-images.githubusercontent.com/89818055/132547285-f324f1c3-8765-4c12-8460-daf66847ce13.png)

**Comment by ricco-douro** [comment]
Esse é o erro que eu falo no #234....

**Comment by VictorHungria** [comment]
Entendi. Vou dar uma olhada. Obrigado!

**Comment by VictorHungria** [comment]
Pelo que eu entendi, você está com erro ao iniciar uma conversa com alguém, não é? Se sim, não é o meu caso. Eu não estou conseguindo mandar mensagem de maneira nenhuma.

**Comment by ricco-douro** [comment]
sim @VictorHungria esse mesu erro só acontece quando wu quero iniciar uma conversa com quem nunca falei nem falou comigo. Depois de a pessoa dar um "oi" a conversa decorre normalmente mesmo que eu inicialize as tabelas de contacts, messages e tickets

**Comment by VictorHungria** [comment]
Meu caso tá sendo um pouco pior... Não estou conseguindo enviar mensagem para ninguém pelo Whaticket. Inclusive, nem mesmo o bot consegue enviar as mensagens automáticas.

**Comment by VictorHungria** [comment]
Eu reiniciei o backend e o frontend e voltou a funcionar. Bom, acho que deva ser prudente deixar o post aberto, por mais que meu problema tenha sido resolvido, para que tenham ciência do BUG.

**Comment by rsrljardim** [comment]
> Boa tarde,
> 
> o Whaticket não está conseguindo enviar mensagem, o que até então dava. Consta como problema que é erro de conexão, porém recebe mensagens normalmente. Alguém tem ideia de como resolve esse bug?
> 
> ![sdfsdf](https://user-images.githubusercontent.com/89818055/132546951-bd0e6fa6-77f7-43c1-9878-a232280863a4.png)

Eu tive essa dificuldade e resolvi deletando qualquer numero que esteja desconectado na pagina de conexões, deixando somente números conectados.

Eu havia cadastrado os nomes dos numeros para os usuários poderem identificar e scanear o QR correto (q esta vinculado a uma fila) porem ao testar ontem identifiquei isso.

Outrossim, é necessário pelo menos um número padrão, que é o nr pode onde serao enviados novas mensagens iniciadas pelo ticket (atendimento ativo, que vc entra em contato)

**Comment by rtenorioh** [comment]
Também já tive esse problema e resolvi alterando o arquivo `ListTicketsService.ts` na pasta `backend\src\services\TicketServices`

`129 const limit = 40;` 
`130 const offset = limit * (+pageNumber - 1);`

alterei esse valor de 40 para 4000, porém pode ser qualquer valor acima dos 40.

**Comment by wesleygyt** [comment]
Oque exatamente este codigo faz rtenorioh ?

129 const limit = 40;
130 const offset = limit * (+pageNumber - 1);
