### ISSUE TITLE
Create a New Ticket!

### ISSUE THREAD

**Issue by KatiaSishost** [canove/whaticket#240]
When a user create a new ticket, this send with default phone number... it's possible to select what number use to create a send the first message without change a default connection?

**Comment by rodrigofsantos** [comment]
Basicamente o sistema sempre vai responder pela numero que gerou o atendimento seu problema esta nas configurações das filas suas filas estão todas pela linha padrão voce precisa atribuir uma fila para a segunda linha e caso o cliente escolha essa fila ai ele sera respondido por ela ...

**Comment by KatiaSishost** [comment]
Não, quero dizer quando o tíquete é criado no painel, ou seja, quando um administrador CRIA o tíquete
