### ISSUE TITLE
Problemas em enviar imagem e audio 

### ISSUE THREAD

**Issue by Empireolld** [canove/whaticket#251]
Opa tudo bem? 

Aposta última atualização não envia mais fotos ou áudios pelo whaticket 

Alguém sabe como solucionar?

**Comment by Empireolld** [comment]
![whatickettt](https://user-images.githubusercontent.com/85648628/134538544-5d4ed90c-e037-4d63-9f38-d3109e07bc37.JPG)

**Comment by jccalbuquerque** [comment]
Verificou as permissões na pasta onde são salvos esses arquivos?

**Comment by mazzucatto** [comment]
Eu estou com esse problema, criei até uma nova publicação para ver se alguém consegue me ajudar, como resolveu meu caro @AlefMartins ?
