### ISSUE TITLE
An Error Ocorred!

### ISSUE THREAD

**Issue by mcliano** [canove/whaticket#252]
Instalei o sistema em 2 servidores diferentes e não consegui fazer funcionar, só aparece An Error Ocorred!. Alguem poderia ajudar?

**Comment by tiagogbarbosa** [comment]
Mesmo problema aqui

**Comment by jccalbuquerque** [comment]
Pode ser diversas coisas!
Sugiro analisar a console do desenvolvedor no navegador para tentar localizar onde está acontecendo;
Sugiro olhar os logs errors do pm2;
Verificar as portas utilizadas em backend e frontend se estão liberadas;
Quase sempre isso é devido a configuração nos .env do backend e frontend.

**Comment by rodrigofsantos** [comment]
Seu erro e na URL confere ela pois tem que esta com o mesmo endereço do acesso e caso voce não tenha configurado CA e docker preciso colocar tudo em http se tiver feito conforme o manual ou seja com certificado digital e tudo mais ai precisa colocar https em tudo.

Quando eu digo que sua URL precisa ser configurada eu digo que se voce por exemplo colocou seu servidor na rede interna mas esta acessando por un DNAT com ip valido da internet voce vai precisar setar o IP de acesso real ou seja o IP valido mesmo estando em um servidor com ip invalido ok 

qualquer duvida me chama que te explico melhor 65 99665 7313 meu whatsapp !!!

Abraço !!

**Comment by tiagogbarbosa** [comment]
No meu caso era isso mesmo.
O url do API deve ter acesso externo tb
Nao tem como deixar apenas o frontend acessivel?

**Comment by mcliano** [comment]
Boa tarde, deu certo aqui, era realmente na hora de setar os endereços do backend e frontend uma vez que eu não estou usando certificado ssl

**Comment by lodredica** [comment]
Colegas, estou com este problema: 
habilitei as portas 443 e 8080;
criei o url myapp.dominio e api.dominio no servidor e apontei para o ip da amazon;
ao rodar o script, ele informa que deu tudo certo com o certibot. mas não adianta.
acessei o backend . env e lá consta o endereço myapp.dominio .com.br
Quando tento dar o start no backend ele dá erro

**Comment by DanielTX-br** [comment]
Mesmo aqui, pelo que entendi não esta enviando os campos, "Failed to load resource: the server responded with a status of 404 (Not Found)", que esta relacionado a "    request.send(requestData);"
ja verifiquei todas as dicas anteriores inclusive resolvi um erro que tinha... 
Esse é meu ENV:

NODE_ENV=production
BACKEND_URL=https://api.****tecnologia.com.br
FRONTEND_URL=https://myapp.***tecnologia.com.br
PROXY_PORT=443
PORT=8080

DB_DIALECT=mariadb
DB_HOST=localhost
DB_USER=root
DB_PASS=********
DB_NAME=whaticket

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756

esses subdomínios apontam para meu ip local onde tem um DMZ para a maquina virtual com Ubuntu 18:04....

**Comment by Gustavo-Stein** [comment]
Verifique se adicionou o usuário e permissões de usuário no Mysql, pois seguindo o guia de instalação na página principal daqui do Repo, este passo não consta. 
Deve ser realizado logo após:

docker run --name whaticketdb -e MYSQL_ROOT_PASSWORD=strongpassword -e MYSQL_DATABASE=whaticket -e MYSQL_USER=whaticket -e MYSQL_PASSWORD=whaticket --restart always -p 3306:3306 -d mariadb:latest --character-set-server=utf8mb4 --collation-server=utf8mb4_bin

Através dos comandos: 

CREATE USER 'whaticket'@'172.17.0.1' IDENTIFIED BY 'strongpassword';
GRAN ALL PRIVILEGES ON *.* TO 'whaticket'@'172.17.0.1' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EXIT;

O ip é este mesmo 172.17.0.1
O restante deve utilizar os valores que colocou no momento da criação do DB no docker run
