### ISSUE TITLE
Sugestão de melhoria

### ISSUE THREAD

**Issue by hahndouglasf** [canove/whaticket#253]
Olá!

Tenho como sugestão de melhoria, deixar liberado o acesso as conexões somente para administradores, acredito que os usuários não deveriam ter acesso a esta.

**Comment by lisboadouglas** [comment]
> Olá!
> 
> Tenho como sugestão de melhoria, deixar liberado o acesso as conexões somente para administradores, acredito que os usuários não deveriam ter acesso a esta.

Olá, 

Se quiser realizar esta alteração, pode modificar o arquivo frontend/src/layout/MainListItems.js

E pegue o código:
<ListItemLink
							to="/connections"
							primary={i18n.t("mainDrawer.listItems.connections")}
							icon={
								<Badge badgeContent={connectionWarning ? "!" : 0} color="error">
									<SyncAltIcon />
								</Badge>
							}
						/>
						
E coloque dentro do <Can />

**Comment by lisboadouglas** [comment]
Exemplo:

<Can
				role={user.profile}
				perform="drawer-admin-items:view"
				yes={() => (
					<>
						<Divider />
						<ListSubheader inset>
							{i18n.t("mainDrawer.listItems.administration")}
						</ListSubheader>
						<ListItemLink
							to="/connections"
							primary={i18n.t("mainDrawer.listItems.connections")}
							icon={
								<Badge badgeContent={connectionWarning ? "!" : 0} color="error">
									<SyncAltIcon />
								</Badge>
							}
						/>
						<ListItemLink
							to="/users"
							primary={i18n.t("mainDrawer.listItems.users")}
							icon={<PeopleAltOutlinedIcon />}
						/>
						<ListItemLink
							to="/queues"
							primary={i18n.t("mainDrawer.listItems.queues")}
							icon={<AccountTreeOutlinedIcon />}
						/>
						<ListItemLink
							to="/settings"
							primary={i18n.t("mainDrawer.listItems.settings")}
							icon={<SettingsOutlinedIcon />}
						/>
					</>
				)}
			/>

**Comment by hahndouglasf** [comment]
Obrigado!
