### ISSUE TITLE
Envio de vídeo

### ISSUE THREAD

**Issue by rochac2lee** [canove/whaticket#256]
Tentei enviar vídeos mas de jeito nenhum o vídeo é enviado. Sempre vem a mensagem ERR_SENDING_WAPP_MSG com erro 400 no backend.

**Comment by maxivane** [comment]
Eu também não consigo... Pelo jeito é só vídeo... Mp4

**Comment by ricco-douro** [comment]
Gente, os video precisam de codecs que só estão disponiveis no Google Chrome e não estão disponiveis no Chromium. Se estão usando Chromium, instalem o Chrome na vossa plataforma (mesmo que seja um ubuntu server, sem gráficos ele instala) e depois, no arquivo .env adicionem uma linha com o seguinte efeito:

CHROME_BIN=C:\Program Files\Google\Chrome\Application\chrome.exe
ou
CHROME_BIN=/usr/bin/google-chrome

**Comment by maxivane** [comment]
> CHROME_BIN=C:\Program

Deu certo aqui comigo, obrigado...

**Comment by rochac2lee** [comment]
@ricco-douro obrigado pela dica. Deixo aqui o processo completo, para quem usa Linux, afim de solucionar esse problema:

Obtenha o chrome
`wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb`

Instale
`sudo apt install ./google-chrome-stable_current_amd64.deb`

No arquivo /whaticket/backend/.env insira:
`CHROME_BIN=/usr/bin/google-chrome-stable`

Crie uma nova build
`npm run build`

Inicie o serviço
`npm start`

------------------------------------------------------------------------------------------------------------------
"Nunca desista dos seus sonhos, mesmo que tentem lhe derrubar" - Cleber Lee
