### ISSUE TITLE
Atualizar para nova versão

### ISSUE THREAD

**Issue by bonanati** [canove/whaticket#258]
Olá, como faço para atualizar para versão onde tem a função de respostas rápida, pois com o comando ./updateWhaticket ele não atualiza com essa função.

**Comment by maxivane** [comment]
Baixa aqui no Github e instala em cima do seu aí... Roda o npm rum build de novo quando jogar os arquivos no seu servidor.

**Comment by bonanati** [comment]
Vou tentar aqui... Thanks

**Comment by maxivane** [comment]
Ok, se não conseguir avisa ai

**Comment by bonanati** [comment]
aviso sim..

**Comment by rodrigofsantos** [comment]
agora como usar essa função de resposta rápida ?

**Comment by bonanati** [comment]
Atalho: 
/exemplo

Resposta Rápida: 
Aqui está um exemplo de criação de respostas rápidas

No campo mensagens digite /exemplo
