### ISSUE TITLE
Desenvolvimento da versão open-source

### ISSUE THREAD

**Issue by tibehrius** [canove/whaticket#265]
Olá a todos.

Vi que uma empresa está comercializando o Whaticket, mas parece haver outras features, como: agendamento de mensagens, bot com menus e atendimento automático, dentre outras. A minha dúvida é: esta versão pública ainda está em desenvolvimento, ou após sair a premium deixou de ser atualizada?

**Comment by canove** [comment]
Boa tarde, amigos!

Desculpem a ausência. 

O [Whaticket](https://whaticket.com) é meu, é uma versão SaaS que lancei com base nesse projeto open source. 

No momento não estou atualizando esse repositório por falta de tempo, mas quero que ele continue aberto e evoluindo, dentro das minhas possibilidades. 

A versão SaaS não está à venda, está disponível somente por meio de assinatura para o usuário final.

Fiquem a vontade para fazer pull request aqui, estarei revisando e aprovando sempre que possível.

Cassio

**Comment by pgdigital** [comment]
> 
> 
> > Não existe versão oficial com mais funções, essas outras funções que estão vendo é que essas outras empresas implementaram.
> 
> O que busco são novas funcionalidades olhe esse canal
> 
> https://www.youtube.com/channel/UCmpUliqK6_4uep7ZhrMjL1g/videos

Pow que legal JEFERSON, obrigado por reportar.

Por acaso vc tem o contato deste canal ai?

Estou procurando mas nao vi nada no canal dele.

Obrigado

**Comment by w3nder** [comment]
> Vale também atentar que existe um grupo no discord com outras pessoas que querem efetuar melhorias no sistema. Junte-se ao grupo e com apoio de todos é possível chegar perto do que o @canove desenvolveu ao longo dos anos.
> 
> Abraços.

Você poderia informar o endereço desse grupo no discord? eu tenho interesse em contribuir.

**Comment by jeffersondrosa** [comment]
> > Vale também atentar que existe um grupo no discord com outras pessoas que querem efetuar melhorias no sistema. Junte-se ao grupo e com apoio de todos é possível chegar perto do que o @canove desenvolveu ao longo dos anos.
> > Abraços.
> 
> Você poderia informar o endereço desse grupo no discord? eu tenho interesse em contribuir.

Olá como encontrar este grupo

**Comment by pgdigital** [comment]
> 
> 
> Link do grupo no Discord https://discord.gg/daN8w2Fs

Muito obrigado, ja entrei la!

**Comment by Jatweb-com-br** [comment]
> 
> 
> Link do grupo no Discord https://discord.gg/daN8w2Fs

boa noite, seria possível me enviar um convite também no discord?

**Comment by srmaky** [comment]
> Link do grupo no Discord https://discord.gg/daN8w2Fs

Olá, poderia enviar o link do grupo? Eu gostaria de contribuir também

**Comment by srmaky** [comment]
> Link do grupo no Discord https://discord.gg/daN8w2Fs


Olá, o link expirou :( 
Poderia enviar o link novamente do grupo? Eu gostaria de contribuir também

**Comment by dev-oneclick** [comment]
Segue o link do Grupo:
https://discord.gg/NRdCQcKCHk

**Comment by contatodct** [comment]
@canove 
me chamo daniel, gostaria de tirar um a duvida simples contigo....seria possivel me chamar no whatsapp assim que posivel?? https://wa.me/5588999390973 -----Grato pela atenção!
