### ISSUE TITLE
Exclusão de contatos em massa

### ISSUE THREAD

**Issue by tibehrius** [canove/whaticket#266]
Loguei o meu whatsapp pessoal no Whaticket, e durante os testes, importei os contatos da minha agenda. Existe uma forma de excluir contatos em massa (via seleção), ou ao menos excluir todos de uma vez?

**Comment by Racass** [comment]
> 
> 
> Loguei o meu whatsapp pessoal no Whaticket, e durante os testes, importei os contatos da minha agenda. Existe uma forma de excluir contatos em massa (via seleção), ou ao menos excluir todos de uma vez?

Olá tibehrius! Tudo bem? O pessoal da [https://github.com/rcatechnology](RCA Technology) estava trabalhando em umas melhorias, incluindo exclusão de contatos em massa
