### ISSUE TITLE
QR is not received after add WA - Hosted at Digital Ocean 

### ISSUE THREAD

**Issue by QAingenieros** [canove/whaticket#267]
Hi Canace, first of all, it is a great Project!!
I tested on my local network and works perfectly but after deploy it to Digital Ocean, I created the WA connection, but I never receive the QR code

![no_qr](https://user-images.githubusercontent.com/61159851/136641817-d5f067c4-f7bb-4c00-958e-66933c981520.png)

**Comment by rodrigofsantos** [comment]
voce precisa ir no console do backend e digitar rs para resetar o backend !!!
