### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by lucaslc7s** [canove/whaticket#273]
Tenho o erro Cannot GET / tentando diretamente pelo ip. 
tenho o erro 403 pelo site myapp.
Alguem pode me ajudar? 
mesmo que eu tenha que pagar pela ajuda eu estou disposto pois estou a 5 dias refazendo todo passo a passo e nada

**Comment by lucaslc7s** [comment]
desculpe não responder rapido, não imaginei que alguem seria tão rapido

**Comment by lucaslc7s** [comment]
REACT_APP_BACKEND_URL = https://api.luxfilms.com.br/

**Comment by lucaslc7s** [comment]
Continuo com mesmo erro

**Comment by AlefMartins** [comment]
Usa o sudo npm run build

**Comment by AlefMartins** [comment]
> eita ja bateu aquela depre aqui

Reveja as alterações que vc fez do front e do back no /etc/

> ng back
> 
> ```
> server {
>   server_name api.luxfilms.com.br;
> 
>   location / {
>     proxy_pass http://127.0.0.1:3333;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection 'upgrade';
>     proxy_set_header Host $host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_cache_bypass $http_upgrade;
>   }
> ```
> 
> ```
>     ng front
> ```
> 
> ```
> 
>     `]server {
>   server_name myapp.luxfilms.com.br;
> 
>   location / {
>     proxy_pass http://127.0.0.1:8080;
>     proxy_http_version 1.1;
>     proxy_set_header Upgrade $http_upgrade;
>     proxy_set_header Connection 'upgrade';
>     proxy_set_header Host $host;
>     proxy_set_header X-Real-IP $remote_addr;
>     proxy_set_header X-Forwarded-Proto $scheme;
>     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_cache_bypass $http_upgrade;
>   }
> ```

Reveja esses arquivos

**Comment by Kouthk** [comment]
Entra no grupo do discord, posso tentar te ajudar em outro momento em uma call. =) 
( Eu ou algum dos outros membros) 
O Link é: https://discord.gg/QCyg39tWKV

**Comment by AlefMartins** [comment]
> Muiiito obrigadoo

ainda está com o problema? eu fiz um passo a passo mais detalhado de como vc deve fazer para funcionar, caso ainda esteja com o problema avisa ai que eu mando aqui mesmo
vlww..

**Comment by lucaslc7s** [comment]
Eu recomecei tudo de novo pelo 0, vamo ve

**Comment by lucaslc7s** [comment]
Certbot failed to authenticate some domains (authenticator: nginx). The Certificate Authority reported these problems:
  Domain: api.luxfilms.com.br
  Type:   connection
  Detail: Fetching http://api.luxfilms.com.br/.well-known/acme-challenge/1taJT1WOUywKbrNDw0lDRyQ0Gnv_k46zJ_qeN0uy6mo: Timeout during connect (likely firewall problem)

  Domain: myapp.luxfilms.com.br
  Type:   connection
  Detail: Fetching http://myapp.luxfilms.com.br/.well-known/acme-challenge/JpG31RXLnbagoMkViVkODaavMYsY9lkHqO8CVxEW6Tw: Timeout during connect (likely firewall problem)

Hint: The Certificate Authority failed to verify the temporary nginx configuration changes made by Certbot. Ensure the listed domains point to this nginx server and that it is accessible from the internet.

Some challenges have failed.
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by lucaslc7s** [comment]
é amigos no instalador estou tento problemas tbm.
The Certificate Authority failed to verify the temporary nginx configuration changes made by Certbot. Ensure the listed domains point to this nginx server and that it is accessible from the internet.

Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

**Comment by lucaslc7s** [comment]
To pra dar um colapso nervoso

**Comment by lucaslc7s** [comment]
tentei novamente com outro subdominio, mesmo resultado

**Comment by lucaslc7s** [comment]
Diretamente pelo ip tenho o erro cannot get novamente

**Comment by AlefMartins** [comment]
> Diretamente pelo ip tenho o erro cannot get novamente

Vc está instalado como? Linux com docker? Ou pm2?

**Comment by lucaslc7s** [comment]
Obrigado AlefMartins por ter me ajudado (fez tudo do inicio ao fim) vc é uma pessoa incrível, o mundo precisa de mais pessoas como vc, simplesmente incrível, me disponibilizou horas de seu tempo vc é 10

**Comment by suissa** [comment]
@AlefMartins estou com um problema na Signup consegue me ajudar?

https://github.com/canove/whaticket-community/issues/583
