### ISSUE TITLE
Múltiplos Aparelhos (Beta)

### ISSUE THREAD

**Issue by rsrljardim** [canove/whaticket#274]
Prezados, com a nova adição do WhatsApp da funcionalidade "**_Múltiplos Aparelhos (Beta)_**" em Aparelhos Conectados, que  depois do aparelho conectado, não precisa mais estar conectado à internet para usar o WhatsApp Web, não é reconhecido a sincronização com o Whaticket. 

Apesar de novo aparelho celular conseguirmos ler o QRCode com sucesso, e aparecer a mensagem de "Ativo", o Whaticket nao reconhece a conexão com essa função do WhatsApp ativo, sendo necessário sair do modo "beta" dessa funcionalidade tão aguardada do WhatsApp.

Essa possibilidade de usar isso será adicionada ao Whaticket?

Forte abraço.

**Comment by maxivane** [comment]
Percebe-se que no web.whatsapp.com se faz a leitura do qrcode 2x..
Acredito que se por o Whaticket para ler o segundo qrcode resolve

**Comment by rodrigofsantos** [comment]
Alguem conseguiu implementar @canove  da uma força ai !! o beta agora le por sistema de aquivo !

**Comment by Vojoo** [comment]
Ola, fica minha contribuição para o problema de Multplos aparelhos.

vai na pasta backend > node_modules > pasta whatsapp-web.js > arquivo exemple.js > comenta essa linha > client.on('change_battery', (batteryInfo) => {
    // Battery percentage for attached device has changed
    const { battery, plugged } = batteryInfo;
    console.log(`Battery: ${battery}% - Charging? ${plugged}`);
});
Depois restarta o backend e manda conectar
