### ISSUE TITLE
Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'

### ISSUE THREAD

**Issue by vchangcar** [canove/whaticket#275]
Verifique o endereço e ele não existe, porém não sei se é o endereço correto para ligar. ajuda por favor
![image](https://user-images.githubusercontent.com/64663328/137382410-008718e1-4312-4382-b1f6-3c3baa9d0f7c.png)

**Comment by riservato-thiagomelo** [comment]
Seu VPS tem pouca memória RAM, aparentemente.

Pelos meus testes, o processo de build do frontend exige VPS com 2GB (sem nada mais consumindo).

Para circuncidar isso, você pode tentar uma das duas opções:

- melhorar o VPS;
- fazer build no seu próprio PC e enviar a build para o VPS com rsync.

**Comment by dantaspaulo** [comment]
> 

Fiz exatamente isso, após aumentar a RAM para 4g e a tela de login apareceu, no entanto ele demora muito e não loga. Seria o caso de aumentar a RAM para 8?
