### ISSUE TITLE
Instalação do backend localhost - Windows 

### ISSUE THREAD

**Issue by petronioamaral** [canove/whaticket#276]
Olá pessoal,

estou tentando dar o npm run build, porém recebo uma mensagem de erro.
Alguem já passou por isso aí?

$ npm run build

> backend@1.0.0 build C:\Users\Usuario\whatsapp_ticket\web\backend
> tsc

src/database/migrations/20211014202304-CreateCompany.ts(3,24): error TS2304: Cannot find name 'QueryInterface'.
src/database/migrations/20211014202304-CreateCompany.ts(6,15): error TS2304: Cannot find name 'DataTypes'.
src/database/migrations/20211014202304-CreateCompany.ts(12,15): error TS2304: Cannot find name 'DataTypes'.
src/database/migrations/20211014202304-CreateCompany.ts(16,15): error TS2304: Cannot find name 'DataTypes'.
src/database/migrations/20211014202304-CreateCompany.ts(21,15): error TS2304: Cannot find name 'DataTypes'.
src/database/migrations/20211014202304-CreateCompany.ts(25,15): error TS2304: Cannot find name 'DataTypes'.
src/database/migrations/20211014202304-CreateCompany.ts(29,15): error TS2304: Cannot find name 'DataTypes'.
src/database/migrations/20211014202304-CreateCompany.ts(35,26): error TS2304: Cannot find name 'QueryInterface'.
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! backend@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the backend@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

![Ld22gnTjVy](https://user-images.githubusercontent.com/5113208/137418413-b60d2b3e-62b9-462d-ade7-ce88b102b816.png)

**Comment by rodrigofsantos** [comment]
voce esta usando WSL ?

**Comment by WotilaCarneiro** [comment]
Queria reabrir esse tópico, estou com o mesmo problema apresentado. Quando executo npm run build no backend, aparece o mesmo erro.
