### ISSUE TITLE
REMOVER GRUPOS DE WHATSAPP

### ISSUE THREAD

**Issue by Empireolld** [canove/whaticket#277]
Opa bom?

alguém sabe se e possível remover os grupos dos whatsapp?

**Comment by maxivane** [comment]
Vai em pull request aí em cima, coloquei uma opção lá..
Lembrando que vc mesmo tem que fazer aí as modificações no código do sistema por ser open source

**Comment by rodrigofsantos** [comment]
sim esta funcionando !!!
