### ISSUE TITLE
Filas não carrega

### ISSUE THREAD

**Issue by AlanMartines** [canove/whaticket#281]
Boa tarde,
 Primeiramente parabéns pelo projeto, top de mais.

Notei que as filas não estão sendo carregadas no filtro

![image](https://user-images.githubusercontent.com/10979090/137802738-36f4fe19-501a-4e2f-9c68-babb4c1510ba.png)

![image](https://user-images.githubusercontent.com/10979090/137802783-46c6734a-2fbf-4afc-bf81-0053c9ec62a4.png)

Será que estou errando em alguma configuração?

Se poderem me dar uma help, agradeço.

**Comment by dev-oneclick** [comment]
Verifica em usuários se este usuário que esta logado esta com acesso a fila, porque se ele não estiver atribuido a uma fila não vai aparecer mesmo.
