### ISSUE TITLE
Session

### ISSUE THREAD

**Issue by KatiaSishost** [canove/whaticket#29]
the session expire if u not send or update the web for 5 minuts aprox...

when reload the web... u can't login... u need delete cookies and more to can login again!

**Comment by canove** [comment]
Hi, Katia! How are u doing? 

I didn't notice this on my side. Bu I'm working on a better session handler using refresh tokens, you can give it a try if you clone the "refresh-tokens" branch.

**Comment by canove** [comment]
The new session handler is implemented now. Update your app with master and feel free to reopen this if problems persists. 
To make it work, you'll need a new .env file on your backend, see: https://github.com/canove/whaticket/commit/c1ed20a559d2b41267b853023aacefbd07c4f024

**Comment by Re1M0n** [comment]
Hello, tried this, session expires on reload.

> The new session handler is implemented now. Update your app with master and feel free to reopen this if problems persists. To make it work, you'll need a new .env file on your backend, see: [c1ed20a](https://github.com/canove/whaticket-community/commit/c1ed20a559d2b41267b853023aacefbd07c4f024)
