### ISSUE TITLE
Alteração de senha de usuario

### ISSUE THREAD

**Issue by Kouthk** [canove/whaticket#292]
Como dar permissão para que o usuario 'tipo user' altere a sua propria senha?

**Comment by rumeniquej** [comment]
Se não estou errado, qdo o user logar ele clica no perfil no canto esquerdo e pode trocar a senha.

**Comment by Kouthk** [comment]
Quando ele tenta fazer isso aparece a mensagem de permissão negada :/
Só funciona quando o usuario tem o perfil de administrador

**Comment by Kouthk** [comment]
@riservato-thiagomelo  você conseguiria me auxiliar com isso?
