### ISSUE TITLE
WhatsApp múltiplos aparelhos (final)

### ISSUE THREAD

**Issue by YuriKTM** [canove/whaticket#293]
Olá amigos, na data de ontem (05/11/2021) o WhatsApp oficializou a função de múltiplos aparelhos até quatro aparelhos simultâneos, o WhatsApp padrão já chegou a atualizar e não conecta mais no Whaticket, tentei por varias vezes mais esta acontecendo o mesmo quando eu tentava conectar com a versão beta, como não tem suporte não conectava.

Vai ter possibilidade disso ser adicionada ao Whaticket?

Abraços a todos.

**Comment by rodrigofsantos** [comment]
Acho que é algo inevitável para todos nos que estamos usando o sistema, na realidade a forma de autenticação do QR vai mudar de banco de dados para files !

**Comment by rodrigofsantos** [comment]
@canove vamos precisar de sua ajuda sei que na versão sua versão comercial já esta funcionando veja como pode nos ajudar !!!!

**Comment by rodrigofsantos** [comment]
@canove amigo vamos precisa de sua ajuda acredito que na sua versão comercial que usa o whatsappjs ja esta funcionando então veja se pode nos ajuda ou se tera algun custo assim não deixamos de usar o sistema !!!

**Comment by bonanati** [comment]
vc disse que whaticket não está mais funcionando ? o meu está conectado

**Comment by paulohsilvestre** [comment]
Bom dia, hoje fui verificar, e encontrei esse material aqui https://github.com/pedroslopez/whatsapp-web.js/pull/889.
ai fiz o seguinte processo esse processo dentro do módulo backend:

- removi a pasta node_modules
- entrei no package.json e removi essa linha "whatsapp-web.js": "^1.14.1",
- rodei um npm install
- atualizei com "npm update -f"
- ai instalei o "npm i github:pedroslopez/whatsapp-web.js#multidevice"
- depois editei o wbot.ts na const initWbot
      

      const io = getIO();
      const sessionName = whatsapp.name;
      const SESSION_FILE_PATH = './session.json';
      let sessionCfg;
      if (fs.existsSync(SESSION_FILE_PATH)) {
        sessionCfg = require(SESSION_FILE_PATH);
      }
      const wbot: Session = new Client({ puppeteer: { headless: false }, clientId: 'bd_'+whatsapp.id });

Depois desse processo feito, foi necessário ler 2X o qrCode, outro detalhe que na tabela whatsapp o session não fica mais pois agora é em arquivo, mas o status fica como conectado.

Está funcionando os recursos padrões receber e enviar mensagens, as outras funcionalidades não testei ainda.

Essa branch ainda vai sofrer mudanças, então essa é a forma para funcionar momentaneamente se necessário.

Abraço

**Comment by w3nder** [comment]
> @canove amigo vamos precisa de sua ajuda acredito que na sua versão comercial que usa o whatsappjs ja esta funcionando então veja se pode nos ajuda ou se tera algun custo assim não deixamos de usar o sistema !!!

Talvez você esteja exigindo um pouco, é um projeto aberto, você pode fazer um fork é fazer essa atualização.
O @canove  já fez muito por nos, talvez seja a hora de nos fazer por ele também...

**Comment by diazzaid** [comment]
> Bom dia, hoje fui verificar, e encontrei esse material aqui [pedroslopez/whatsapp-web.js#889](https://github.com/pedroslopez/whatsapp-web.js/pull/889). ai fiz o seguinte processo esse processo dentro do módulo backend:
> 
> * removi a pasta node_modules
> * entrei no package.json e removi essa linha "whatsapp-web.js": "^1.14.1",
> * rodei um npm install
> * atualizei com "npm update -f"
> * ai instalei o "npm i github:pedroslopez/whatsapp-web.js#multidevice"
> * depois editei o wbot.ts na const initWbot
>   ```
>   const io = getIO();
>   const sessionName = whatsapp.name;
>   const SESSION_FILE_PATH = './session.json';
>   let sessionCfg;
>   if (fs.existsSync(SESSION_FILE_PATH)) {
>     sessionCfg = require(SESSION_FILE_PATH);
>   }
>   const wbot: Session = new Client({ puppeteer: { headless: false }, clientId: 'bd_'+whatsapp.id });
>   ```
> 
> Depois desse processo feito, foi necessário ler 2X o qrCode, outro detalhe que na tabela whatsapp o session não fica mais pois agora é em arquivo, mas o status fica como conectado.
> 
> Está funcionando os recursos padrões receber e enviar mensagens, as outras funcionalidades não testei ainda.
> 
> Essa branch ainda vai sofrer mudanças, então essa é a forma para funcionar momentaneamente se necessário.
> 
> Abraço

after scanning qr 2 x the browser immediately closes and reopens but asks for a qr scan again
session files are stored in the WWebJS folder
![image](https://user-images.githubusercontent.com/25816482/141677255-86c5ae7a-eacd-411b-9b7a-abbef0737752.png)

**Comment by diazzaid** [comment]
![image](https://user-images.githubusercontent.com/25816482/141677439-a1060867-d25c-4bcd-8b64-b63306358503.png)

**Comment by ertprs** [comment]
Fui fazer a atualização aqui e estou com esse mesmo problema, está fazendo restart da sessão do whatsaap, não consigo nem receber e enviar mensagem, procurando uma solução para esse problema, pq meu whatsapp não tem mais a possibilidade de desabilitar a opção de multisessão beta como tinha anteriormente.

**Comment by w3nder** [comment]
> Fui fazer a atualização aqui e estou com esse mesmo problema, está fazendo restart da sessão do whatsaap, não consigo nem receber e enviar mensagem, procurando uma solução para esse problema, pq meu whatsapp não tem mais a possibilidade de desabilitar a opção de multisessão beta como tinha anteriormente.

Usa um apk que ainda tem a opção... eu fiz isso aqui...

Até deixar de ser beta essa opção.

**Comment by paulohsilvestre** [comment]
> * entrei no package.json e removi essa linha "whatsapp-web.js": "^1.14.1",

Did you remove the package-lock.json file? before making the changes, as it can sometimes use this file to perform the cached installation.

**Comment by paulohsilvestre** [comment]
> > Bom dia, hoje fui verificar, e encontrei esse material aqui [pedroslopez/whatsapp-web.js#889](https://github.com/pedroslopez/whatsapp-web.js/pull/889). ai fiz o seguinte processo esse processo dentro do módulo backend:
> > 
> > * removi a pasta node_modules
> > * entrei no package.json e removi essa linha "whatsapp-web.js": "^1.14.1",
> > * rodei um npm install
> > * atualizei com "npm update -f"
> > * ai instalei o "npm i github:pedroslopez/whatsapp-web.js#multidevice"
> > * depois editei o wbot.ts na const initWbot
> >   ```
> >   const io = getIO();
> >   const sessionName = whatsapp.name;
> >   const SESSION_FILE_PATH = './session.json';
> >   let sessionCfg;
> >   if (fs.existsSync(SESSION_FILE_PATH)) {
> >     sessionCfg = require(SESSION_FILE_PATH);
> >   }
> >   const wbot: Session = new Client({ puppeteer: { headless: false }, clientId: 'bd_'+whatsapp.id });
> >   ```
> > 
> > Depois desse processo feito, foi necessário ler 2X o qrCode, outro detalhe que na tabela whatsapp o session não fica mais pois agora é em arquivo, mas o status fica como conectado.
> > Está funcionando os recursos padrões receber e enviar mensagens, as outras funcionalidades não testei ainda.
> > Essa branch ainda vai sofrer mudanças, então essa é a forma para funcionar momentaneamente se necessário.
> > Abraço
> 
> after scanning qr 2 x the browser immediately closes and reopens but asks for a qr scan again session files are stored in the WWebJS folder ![image](https://user-images.githubusercontent.com/25816482/141677255-86c5ae7a-eacd-411b-9b7a-abbef0737752.png)

realizei alguns testes como foi mencionado e sim o erro ocorre, mas ai fui fazer os testes, baixei a mesma versão do Whaticket que está hoje e ao rodar ele reinicia os serviços, se vocês estão no ambiente de desenvolvimento nos scripts dentro do package.json muda isso "start": "nodemon dist/server.js", para "start": "node dist/server.js", e testem, ao fazer isso rodou lisinho, mas podem acontecer muitas mudanças até todos estarem com o Multidevice ativo.
o nodemon avalia mudanças em arquivos e reinicia para sempre estar atualizado, façam esse teste e se possível deem um feedback se funcionou.

**Comment by ertprs** [comment]
> 

Fiz o teste também, agora conectando e fixando a conexão, porém apenas envio e recebimento de mensagens.

O seu funcionou recebimento de áudio, fotos e vídeos?

**Comment by paulohsilvestre** [comment]
> > 
> 
> Fiz o teste também, agora conectando e fixando a conexão, porém apenas envio e recebimento de mensagens.
> 
> O seu funcionou recebimento de áudio, fotos e vídeos?

Normalmente, o que você precisa validar é o caminho que está salvando as mídias, se o Front não encontra o botão não ativa para ouvir ou ver, e não funciona, verifica no seu arquivo, tenta debugar e ver qual o caminho está sendo mostrado nesse arquivo ModalImageCors/index.js é onde são mostradas as imagens veja se o imageUrl está apontado para o backend corretamente.

**Comment by ertprs** [comment]
> > > 
> > 
> > 
> > Fiz o teste também, agora conectando e fixando a conexão, porém apenas envio e recebimento de mensagens.
> > O seu funcionou recebimento de áudio, fotos e vídeos?
> 
> Normalmente, o que você precisa validar é o caminho que está salvando as mídias, se o Front não encontra o link não ativa para ouvir ou ver, e não funciona, verifica no seu arquivo, tenta debugar e ver qual o caminho está sendo mostrado nesse arquivo ModalImageCors/index.js é onde são mostradas as imagens veja se o imageUrl está apontado para o backend corretamente.
> 
> ![image](https://user-images.githubusercontent.com/5527095/142918913-e671782f-c7be-4517-a65e-7c28852ab644.png)

![image](https://user-images.githubusercontent.com/62783690/142955478-1e6037a0-2548-4367-809b-19f0d40a7249.png)
Deu certo, obrigado pela dica, vou terminar de implementar algumas funções aqui e depois compartilhar aqui no projeto.

Deus abençoe

**Comment by pgdigital** [comment]
Ficando show manin, parabens pelo belissimo trabalho. Quando puder compartilhar algo, fico agradecido de vdd!!!
Deus t abençoe sempre.

**Comment by HerisonMaciel** [comment]
O meu está dando esse erro, alguém sabe o pq?
![image](https://user-images.githubusercontent.com/20330592/143383123-57684ceb-6a00-4e9b-94ec-3144a76fc762.png)

**Comment by AlefMartins** [comment]
> O meu está dando esse erro, alguém sabe o pq? ![image](https://user-images.githubusercontent.com/20330592/143383123-57684ceb-6a00-4e9b-94ec-3144a76fc762.png)

também estou recebendo o mesmo erro

**Comment by fogolin** [comment]
@ertprs Conseguiu implementar as funções que você queria? Se puder compartilhar com a gente seria 10!

**Comment by rodrigofsantos** [comment]
@HerisonMaciel  e @AlefMartins  vocês estão executando como root user e não pode ! precisa ser como usuário comum cria um usuário normal pode ser com nomes de vocês mesmo !!!

**Comment by diazzaid** [comment]
> > > Bom dia, hoje fui verificar, e encontrei esse material aqui [pedroslopez/whatsapp-web.js#889](https://github.com/pedroslopez/whatsapp-web.js/pull/889). ai fiz o seguinte processo esse processo dentro do módulo backend:
> > > 
> > > * removi a pasta node_modules
> > > * entrei no package.json e removi essa linha "whatsapp-web.js": "^1.14.1",
> > > * rodei um npm install
> > > * atualizei com "npm update -f"
> > > * ai instalei o "npm i github:pedroslopez/whatsapp-web.js#multidevice"
> > > * depois editei o wbot.ts na const initWbot
> > >   ```
> > >   const io = getIO();
> > >   const sessionName = whatsapp.name;
> > >   const SESSION_FILE_PATH = './session.json';
> > >   let sessionCfg;
> > >   if (fs.existsSync(SESSION_FILE_PATH)) {
> > >     sessionCfg = require(SESSION_FILE_PATH);
> > >   }
> > >   const wbot: Session = new Client({ puppeteer: { headless: false }, clientId: 'bd_'+whatsapp.id });
> > >   ```
> > > 
> > > Depois desse processo feito, foi necessário ler 2X o qrCode, outro detalhe que na tabela whatsapp o session não fica mais pois agora é em arquivo, mas o status fica como conectado.
> > > Está funcionando os recursos padrões receber e enviar mensagens, as outras funcionalidades não testei ainda.
> > > Essa branch ainda vai sofrer mudanças, então essa é a forma para funcionar momentaneamente se necessário.
> > > Abraço
> > 
> > 
> > after scanning qr 2 x the browser immediately closes and reopens but asks for a qr scan again session files are stored in the WWebJS folder ![image](https://user-images.githubusercontent.com/25816482/141677255-86c5ae7a-eacd-411b-9b7a-abbef0737752.png)
> 
> realizei alguns testes como foi mencionado e sim o erro ocorre, mas ai fui fazer os testes, baixei a mesma versão do Whaticket que está hoje e ao rodar ele reinicia os serviços, se vocês estão no ambiente de desenvolvimento nos scripts dentro do package.json muda isso "start": "nodemon dist/server.js", para "start": "node dist/server.js", e testem, ao fazer isso rodou lisinho, mas podem acontecer muitas mudanças até todos estarem com o Multidevice ativo. o nodemon avalia mudanças em arquivos e reinicia para sempre estar atualizado, façam esse teste e se possível deem um feedback se funcionou.

ok work
thanks..
