### ISSUE TITLE
Whaticket parou de funcionar

### ISSUE THREAD

**Issue by flaviomiran** [canove/whaticket#294]
Olá pessoal! Sou novo aqui.
Há mais ou menos um mês passamos a usar o whaticket para atendimento em nossa empresa e ontem o mesmo parou de funcionar. Perdeu a conexão e não conecta mais.
Provavelmente deve estar sofrendo pelas atualizações ocorridas pelo whatsapp.
Alguém tem solução para esse problema?

**Comment by w3nder** [comment]
Não tem como te ajudar muito, você não deu informação sobre o seu problema...

Você está usando o beta?
Olhou nos logs do backend para ver se tem algum erro?

Ontem eu tive problema com o whatsapp-web.js 1.14.1 (Evaluation failed: TypeError: n._find is not a function)
Ai atualizei a dependência whatsapp-web.js para versão 1.15.1 é problema resolvido. 

Remove o yarn.lock/package-lock 

Vai no package.json é procura "whatsapp-web.js": "^1.14.1", é muda para "whatsapp-web.js": "^1.15.1",
E roda novamente npm install ou yarn (depende do que vc usa ai)

**Comment by rodrigofsantos** [comment]
Duas hipóteses se você atualizou seu whatsapp para ativar o multdevice ferrou vai precisar corrigir o sistema pois o esquema de sessão mudou outro erro e sim atualização da whatsappjs precisa ser feito !! Estou usando a 8 meses sem erro so update mesmo !!!

**Comment by flaviomiran** [comment]
Ola pessoal!
O problema era que o sistema perdeu a conexão e não estava permitindo conectar novamente. Passou dois dias fora do ar.
Não havíamos atualizado o whatsapp para a versão beta (multdevice).
Depois de gerar o QR Code várias vezes, saindo e entrando no sistema, para renovar os mesmos, o conseguimos fazer a conexão novamente e o sistema voltou a funcionar. 
Agradeço a ajuda de vocês.

**Comment by lidernetworktecnologia** [comment]
Aqui parou de funcionar do nada dai fiz conforme o @w3nder informou:  "whatsapp-web.js": "^1.14.1", é muda para "whatsapp-web.js": "^1.15.1" e FUNCIONOU perfeitamente! Obrigado pela contribuição parceiro
