### ISSUE TITLE
Mensagem fora de horário de expediente

### ISSUE THREAD

**Issue by BOCAPO** [canove/whaticket#297]
Galera uma função legal seria a  Mensagem fora de horário de expediente, ter la em configurações opção de de colocar horário de funcionamento da empresa , caso alguém chamar aparece a mensagem  personalizada (que seja possível personalizar).

Vou tentar implementar , se conseguir mando aqui para vcs.

**Comment by rodrigofsantos** [comment]
olha por hora não tem mas você pode instalar o whatsapp business e configurar nele depois configure seu sistema para desativar o whaticket apos X hora tipo apos as 18Hs desabilite seu serviço do whaticket isso ira resolver por hora ate que seja criado essa função !
