### ISSUE TITLE
Impossível salvar contato para iniciar novo ticket.

### ISSUE THREAD

**Issue by Gustavo-Stein** [canove/whaticket#298]
Com duas conexões ativas, com uma sendo a padrão.
Ao seguir a sequência: 
Contatos > Adicionar Contato > 

![image](https://user-images.githubusercontent.com/65373775/142515374-42dfe7a4-faf9-49ec-85c0-20a3a613cede.png)

Alguma ideia de como resolver?

**Comment by BOCAPO** [comment]
> Com duas conexões ativas, com uma sendo a padrão. Ao seguir a sequência: Contatos > Adicionar Contato >
> 
> ![image](https://user-images.githubusercontent.com/65373775/142515374-42dfe7a4-faf9-49ec-85c0-20a3a613cede.png)
> 
> Alguma ideia de como resolver?

Ja Limpou Cache ?

**Comment by DukazzCruz** [comment]
![image](https://user-images.githubusercontent.com/79736683/144109150-08dcd952-420f-4e0f-9dea-372230460f7c.png)

https://github.com/tuyuribr/whatsapp-web.js/commit/20172d674e1c6b402ac69712c325c4d6ab708f56
