### ISSUE TITLE
cor da linha toda cinza

### ISSUE THREAD

**Issue by rodrigoperez84** [canove/whaticket#300]
Olá! Parabéns por este projeto Open Source. Instalei e funciona em espanhol, só corrigi algumas traduções, muito poucas! Não sei por que não recebo as cores no tíquete depois que ele é atribuído a um usuário. Eu vejo tudo em cinza. cor da linha toda cinza

**Comment by rochac2lee** [comment]
As cores são atribuídas somente se estiver com uma fila vinculada ao usuário.

**Comment by rodrigoperez84** [comment]
agora sim! Configurei tudo bem e quando o contato chega na área correspondente, vejo o ticket com a respectiva cor. Obrigado!!

**Comment by rodrigoperez84** [comment]
> As cores são atribuídas somente se estiver com uma fila vinculada ao usuário.

agora sim! Configurei tudo bem e quando o contato chega na área correspondente, vejo o ticket com a respectiva cor. Obrigado!!
