### ISSUE TITLE
Erro ao carregar arquivos

### ISSUE THREAD

**Issue by guisz1** [canove/whaticket#301]
quando carrego um arquivo ele esta vindo com o seguinte erro 
http://meuip:8080:80/public/1637613674547.jpeg

oque devo fazer para resolver
![image](https://user-images.githubusercontent.com/16584514/143088900-f929c9f4-ec8e-4dcc-bc25-03bf6deb21d6.png)
![image](https://user-images.githubusercontent.com/16584514/143088918-1516b8ab-eb94-4045-8382-2443dad6df64.png)

**Comment by rochac2lee** [comment]
@guisz1 Provavelmente não tem permissão de escrita na pasta backend/Public
