### ISSUE TITLE
 não é possível fazer conexões QR com Whaticket

### ISSUE THREAD

**Issue by rodrigoperez84** [canove/whaticket#305]
Olá. Desde ontem não é possível fazer conexões QR com Whaticket. Disseram que o WhatsApp foi atualizado. Executei o processo de atualização, mas gerou erros. Quem pode me guiar. É algo relacionado ao whatsapp-web.js "1.15.1?
Engraçado!!

**Comment by lisboadouglas** [comment]
O

> Olá. Desde ontem não é possível fazer conexões QR com Whaticket. Disseram que o WhatsApp foi atualizado. Executei o processo de atualização, mas gerou erros. Quem pode me guiar. É algo relacionado ao whatsapp-web.js "1.15.1? Engraçado!!

Quais erros foram gerados no processo de atualização?

**Comment by rodrigofsantos** [comment]
precisa atualizar, 
segue esse alteração feita pela pull request : 
https://github.com/canove/whaticket/pull/302/files

apos isso dentro da pasta backend faz um update 
se não resolver 

remove a pasta node_modules 

e instala novamente o modulos do backend
