### ISSUE TITLE
Not working with brazilian 9th digit

### ISSUE THREAD

**Issue by fogolin** [canove/whaticket#306]
I got both, cases when you need to add the 9th digit for brazilian mobile phones and cases when you need to exclude it for the conversation to take place.

![image](https://user-images.githubusercontent.com/11749606/143771701-d3cbbf24-d256-4d98-b038-738d9c20ffe4.png)

In the image attached, the phone numbers are the same, differing only in the 9th digit. The first is set without the 9th digit and in that one all messages get through. The second one is set with the 9th digit, there is no error alert, the messages just never get to the user.

I think this is a bug because its possible to incur in a situation where you have to contact the support user though the app and you can't get to them without even knowing this is an issue.

**Comment by rodrigofsantos** [comment]
o whatsapp não usa nono digito !! precisa remover o nono digito para poder funcionar !

**Comment by fogolin** [comment]
> o whatsapp não usa nono digito !! precisa remover o nono digito para poder funcionar !

Rodrigo, então é o caso de cadastrar como bug para poder corrigir isso no momento de criação do usuário. O número na inserçãonão fica criticado, de forma que o usuário não sabe dizer o que está acontecendo e porque não consegue conversar com a pessoa na outra ponta.

**Comment by Kouthk** [comment]
na biblioteca do web-whatsapp.js  tem uma forma de validar essa situação, para saber se o numero é valido ou não e conseguir já mandar mensagem no numero correto ( automatizar a colocada e retirada do 9 ).  Já consegui implementar uma vez, mas era um codigo bem simples de testes, infelizmente não consigo adaptar a mesma logica ao whaticket... Mas tem como resolver isso =)

**Comment by ricco-douro** [comment]
Não esquecendo porém que o 9 extra tem que ser removido para alguns estados, mas em SP é necessário...

**Comment by fogolin** [comment]
@filipeborelli made a pull request to fix this:
https://github.com/canove/whaticket/compare/master...filipeborelli:patch-1
https://github.com/canove/whaticket/compare/master...filipeborelli:patch-2
