### ISSUE TITLE
Erro ao gravar áudio e enviar

### ISSUE THREAD

**Issue by Jonnas1994** [canove/whaticket#307]
estou gravando um audio normal, quando realizo o envio, o mesmo esta ficando corrompido, alguém passou por isso? estou usando usuário diferente do root em uma vpn da hostinger. Desde já agradeço

[Link para o audio que gravou na pasta /Public](https://drive.google.com/file/d/1ZpyZR7GRhaowamsWB88PtGeniWEqopIy/view?usp=sharing)

**Comment by srmaky** [comment]
Acho que é problema de permissão da pasta
