### ISSUE TITLE
Instalação

### ISSUE THREAD

**Issue by GeovaniAguilarPaixao** [canove/whaticket#308]
Bom dia. Uma dúvida, seria possível realizar mais de uma instalação no mesmo servidor utilizando o mesmo IP? Se sim, o que eu deveria mudar na instalação?

**Comment by rochac2lee** [comment]
@GeovaniAguilarPaixao para cada instalação você precisa definir uma porta diferente para o backend (.env) e frontend (server.js).

**Comment by GeovaniAguilarPaixao** [comment]
@rochac2lee Posso utilizar o mesmo banco de dados?

**Comment by rochac2lee** [comment]
@GeovaniAguilarPaixao Não. Para cada instalação vc precisa definir um banco de dados diferente.

**Comment by GeovaniAguilarPaixao** [comment]
Entendi. Criei um novo usuário, instalei o Docker e adicionei o usuário ao grupo docker. Ao criar o banco de dados, além de alterar o nome (que por padrão é whaticketdb). O que mais devo alterar?

**Comment by rochac2lee** [comment]
Não tenho usado o docker... mas tem que alterar as portas conforme te falei. Depois roda as migrations e seeds no backend e dá um npm run build. No front é só alterar o .env para o endereço do backend e alterar o server.js para outra porta.

**Comment by rodrigofsantos** [comment]
Realmente eu tambem não tenho usado Docker tenho instalado diretamente acho mais simples e acessivel, se voce for atender clientes diferente o ideal e ter banco separados com frontends separados ai basta configurar como nosso colega disse portas diferente mas lembre-se de ter memoria RAM na maquina para isso se não vai ser um travamento sem fim !

**Comment by GeovaniAguilarPaixao** [comment]
@rodrigofsantos Como faço uma instalação direta? Estou sempre tendo problemas ao concluir as migrations e seeds.

**Comment by GeovaniAguilarPaixao** [comment]
Estou usando o tutorial padrão como referencia de instalação. Teria algum alternativo?

**Comment by GeovaniAguilarPaixao** [comment]
Preciso muito resolver essa questão. Se necessário até pago por essa consultoria. Segue meu Whatsapp para contato (37)99664-4234

**Comment by pgdigital** [comment]
Sejam bem vindos, ja estamos com 30 no grupo do Whatsapp para poder ter uma comunicação um pouco mais fluida.

CONVITE GRUPO WHATICKET no WHATSAPP
https://chat.whatsapp.com/Cmsh3jAU4DQGB0L32zIBHb

**Comment by rodrigofsantos** [comment]
@GeovaniAguilarPaixao amigo você mesmo pode instalar basta instalar o mysql manualmente mesmo e setar os dados do banco nos aquivos .env !
