### ISSUE TITLE
Duvida encerramento te ticket.

### ISSUE THREAD

**Issue by PauloJacksonlima** [canove/whaticket#310]
Ola!
Tenho a seguite duvida,  marcamos o ticket como resolvido vai para resolvido ate ai traquilo, porem quando o memos  numero amanda ele nao abre um novo ticket e sim o ticket que foi marcado como resolvido.

**Comment by rodrigofsantos** [comment]
em ate 2 horas se ele entrar em contato novamente sera usado o mesmo ticket apos esse periodo sera aberto um nome, eu mudei para meu uso 45 minutos !

**Comment by PauloJacksonlima** [comment]
pode me falar qual arquivo esta essá confiuração?

**Comment by rodrigofsantos** [comment]
sim edite o arquivo dentro da pasta backend/src/services/ticketservices/ arquivo chamdao FindOrCreateTicketServices.ts 
remova subHours e troque por subMinutes na linha 1 depois na linha 47 faça o mesmo assim :

          [Op.between]: [+subMinutes(new Date(), 45), +new Date()]

**Comment by rodrigofsantos** [comment]
depois npm run build

**Comment by PauloJacksonlima** [comment]
obrigado Rodrigo, estarei editando aqui!

**Comment by PauloJacksonlima** [comment]
Mais uma Duvida eu consigo rodar ele no visual studio code  ?

**Comment by PauloJacksonlima** [comment]
uma outra duvida, sou iniciante na linguagem ainda, queria saber  em quer parte o sistema pega   msg e verifica se existe um ticket.   quero fazer um if ( ticket status == closed ){ iniciar um novo ticket }
e mantendo tempo de 45mim para fechar  o ticket. Eu sabendo onde inicia essas mensagem ficaria  um pouco melhor.

**Comment by PauloJacksonlima** [comment]
Uma Duvida, sou iniciante em node, eu percebi quer  so inicia uma nova msg se o ticket estiver com o status closed e passar o  tempo determinado na linha acima.  teria uma forma de verificar o tempo da msg, sem precisar estar como closed. 
ex se a mensagem atingir o tempo ela automaticamente fecha o ticket. ou ate mandar uma msg de alerta avisando que o ticket será fechado por o chat estar inativo.

**Comment by rodrigofsantos** [comment]
Sim teria sim !

**Comment by PauloJacksonlima** [comment]
Muito bom seu projeto parabens.  é o pessoal do grupo falou em uma trefa Cron ahei boa  a ideia, to estudando as formas ainda e scronizando o codigo,  uma outra coisa  legal seria um chat interno entre os usuarios. 
Obrigado.

**Comment by PauloJacksonlima** [comment]
Ola! como faço para separar o os ticket por aparelho conectado, atualmente se alguém mandar msg mesmo que seja outro numero conectado permanence no mesmo chat.
tipo 
if (ticket && !whatsappId) {
 new ticket

**Comment by developerdevice** [comment]
> Ola! como faço para separar o os ticket por aparelho conectado, atualmente se alguém mandar msg mesmo que seja outro numero conectado permanence no mesmo chat. tipo if (ticket && !whatsappId) { new ticket

Você pode criar filas e associar ao aparelho.

Exemplo: FILA COMERCIAL > associa ao aparelho X. FILA SUPORTE > associal ao aparelho Y

**Comment by PauloJacksonlima** [comment]
Obrigado por responder, eu consegui fazendo umas alteracoes no FindOrCreateTicketService.ts
