### ISSUE TITLE
Duvida Dashbord

### ISSUE THREAD

**Issue by Kouthk** [canove/whaticket#312]
O sistema possui alguma limitação em relação ao numero maximo de mensagens exibidas no dashboard?
![image](https://user-images.githubusercontent.com/34557801/144498426-b27c0739-7016-4ec6-b187-21d2666233fe.png)
Nessa imagem acima, era para ter um numero total de 162.
caso realmente tenha uma limitação, apenas pesquisando no arquivo do front eu consigo resolve-la?

**Comment by jccalbuquerque** [comment]
São os tickets que são processados nesse dasboard,  não mensagens.
Um ticket pode ter dezenas/centenas de mensagens.

Em qui., 2 de dez. de 2021 17:33, Alex Sandro ***@***.***>
escreveu:

**Comment by Kouthk** [comment]
Perdão, quando eu me referi as mensagens eu quis me referir aos TICKETS, tenho 162 Tickets em estado de "aguardando"

**Comment by jccalbuquerque** [comment]
Conferiu data e horário do seu server?

Em qui., 2 de dez. de 2021 17:37, Alex Sandro ***@***.***>
escreveu:

**Comment by Kouthk** [comment]
Existia um limitador, consegui achar essa resposta graças a um usuario no discord. 
![unknown](https://user-images.githubusercontent.com/34557801/144500055-9d1a6bfe-b672-43d0-bef8-e79307471b94.png)
Obrigado pelo auxilio, @jccalbuquerque =D

**Comment by jccalbuquerque** [comment]
Ah, certo.
Havia esquecido,  pois no meu retirei esse limite. Meu dashboard possui
campos para filtrar e permite no máximo 30 dias.

Em qui., 2 de dez. de 2021 17:47, Alex Sandro ***@***.***>
escreveu:

**Comment by Kouthk** [comment]
Também pretendo conseguir incluir essa função de aparecer os ultimos 30 dias.
Alias, sera que é interessante fazer uma PR aumentando aquele limite de 40 tickets para cerca de 100 (ou até maior) visto que isso não impactaria na performace? 
(Na verdade, acho que o melhor metodo seria deixar esse valor em aberto caso também não cause impacto)

**Comment by w3nder** [comment]
> No futuro, também pretendo conseguir incluir essa função de aparecer os ultimos 30 dias. Alias, sera que é interessante fazer uma PR aumentando aquele limite de 40 tickets para cerca de 100 (ou até maior) visto que isso não impactaria na performace? (Na verdade, acho que o melhor metodo seria deixar esse valor em aberto caso também não cause impacto)

Não é muito performático carregar todos esses ticket de uma vez.

Se você precisa que seja exibido (acho que todos) uma quantidade maior, 
talvez o interessante é carregar os ticket sempre que chegar ao fim do scroll fazendo um Infinite Scrolling.

Dessa forma, ele vai carregar os ticket que você precisar, quando chegar ao fim do scroll

**Comment by jccalbuquerque** [comment]
Por isso sempre menciono ao pessoal,  que algumas inclusões/alterações
exigem um alto índice de refatoração
.

Em qui., 2 de dez. de 2021 18:32, Wender Teixeira ***@***.***>
escreveu:

**Comment by eufabianovieira** [comment]
@jccalbuquerque 

Sobre esse recurso de filtro no dashboard, sabe se é possível vir a ser implementado nas futuras atualizações?

Para o nosso uso aqui na empresa seria ótimo podermos contar com essa função.

**Comment by w3nder** [comment]
> @jccalbuquerque
> 
> Sobre esse recurso de filtro no dashboard, sabe se é possível vir a ser implementado nas futuras atualizações?
> 
> Para o nosso uso aqui na empresa seria ótimo podermos contar com essa função.

Vai depender do interesse da comunidade em contribuir.

**Comment by rochac2lee** [comment]
@eufabianovieira Pretendo fazer os filtros sim. Se tiver alguns parâmetros do filtro que vc ache necessário, só me falar que eu adiciono aqui

**Comment by eufabianovieira** [comment]
@rochac2lee No nosso caso, apenas tendo um campo de filtro de seleção por data, para saber quantos tickets houve naquele determinado dia, já ajudaria bastante.

**Comment by Kouthk** [comment]
@rochac2lee Seria bom ter o total de mensagens de conversas iniciadas por cada fila, Ex:
- Fila 1: 12 Conversas
- Fila 2: 41 conversas 
Se essa modificação for possivel, vai ser uma baita mão na roda. =) 

Alias, também junto disso é interessante remover a limitação padrão de '40' numeros para um valor ilimitado no dashboard ( nos tickets não é nescessario, apenas no dashboard)

**Comment by eufabianovieira** [comment]
@Kouthk Essa alteração no "const limit = 40;" também altera o número total de tickets finalizados? ou é somente para os tickets do dia?

Estava precisando liberar esse limitador do total de finalizados que aparece no dashboard, mais ainda não consegui encontrar aonde faço essa alteração.

> Existia um limitador, consegui achar essa resposta graças a um usuario no discord. ![unknown](https://user-images.githubusercontent.com/34557801/144500055-9d1a6bfe-b672-43d0-bef8-e79307471b94.png) Obrigado pelo auxilio, @jccalbuquerque =D

**Comment by Kouthk** [comment]
Aqui: backend/src/services/TicketServices/ListTicketsService.ts 



> @Kouthk Essa alteração no "const limit = 40;" também altera o número total de tickets finalizados? ou é somente para os tickets do dia?
> 
> Estava precisando liberar esse limitador do total de finalizados que aparece no dashboard, mais ainda não consegui encontrar aonde faço essa alteração.
> 
> > Existia um limitador, consegui achar essa resposta graças a um usuario no discord. ![unknown](https://user-images.githubusercontent.com/34557801/144500055-9d1a6bfe-b672-43d0-bef8-e79307471b94.png) Obrigado pelo auxilio, @jccalbuquerque =D
