### ISSUE TITLE
Sugestão - Grupo de gestores.

### ISSUE THREAD

**Issue by lanaparadinha** [canove/whaticket#315]
Criar um grupo de usuário chamado Gestor, onde ele tem acesso a todas as msgs, mão não consegue editar nada do programa.

Meu modelo de trabalho necessita que todos tenham acesso as msgs, e pra isso tive de dar permissão de admin a todos.

No grupo teve outras pessoas com o mesmo problema que o meu.

**Comment by rcalbo** [comment]
Também passo pela mesma situação, tive que liberar o acesso como admin para todos os operadores, porem sempre tem um abençoado que mexe onde não deve....
Vamos pesquisar para tentar encontrar uma solução, quem puder dar uma luz nós agradecemos

**Comment by PauloJacksonlima** [comment]
encalmamento de msg também seria bom.

**Comment by rodrigofsantos** [comment]
Olha isso não acontece com usuários da mesma fila veja se todos as linhas tem os mesmas filas, e todos os usuários estão com as filas que precisa ver, se estiver tudo setado vai aparecer todas as mensagens e não precisa colocar ninguem como admin aqui tenho 5 pessoas no mesmo grupo e todos veem as mensagens uns dois outro em "aguardando" ate ser iniciado o atendimento apos isso realmente a mensagem fica para o atendente mas pode ser transferida !!!
Outra opção seria mudar a opção todos para ser vista pelos usuarios do grupo users !

**Comment by lanaparadinha** [comment]
> Olha isso não acontece com usuários da mesma fila veja se todos as linhas tem os mesmas filas, e todos os usuários estão com as filas que precisa ver, se estiver tudo setado vai aparecer todas as mensagens e não precisa colocar ninguem como admin aqui tenho 5 pessoas no mesmo grupo e todos veem as mensagens uns dois outro em "aguardando" ate ser iniciado o atendimento apos isso realmente a mensagem fica para o atendente mas pode ser transferida !!! Outra opção seria mudar a opção todos para ser vista pelos usuarios do grupo users !

A intenção é ver as msgs que eu o povo aceitou.

**Comment by rcalbo** [comment]
Exatamente, as que já estão em atendimento.

Em sáb., 4 de dez. de 2021 09:58, lanaparadinha ***@***.***>
escreveu:

**Comment by lanaparadinha** [comment]
Resolvi aqui.
no arquivo:
/whaticket/frontend/src/layout/MainListItems.js
Joguei o connections para abaixo do administration:
Linha 81:
   <ListItemLink
        to="/connections"
        primary={i18n.t("mainDrawer.listItems.connections")}
        icon={
          <Badge badgeContent={connectionWarning ? "!" : 0} color="error">
            <SyncAltIcon />
          </Badge>
        }
      />
Coloquei abaixo da linha 110 e depois apaguei a linha de cima.

No arquivo:
/whaticket/frontend/src/components/TicketsManager/index.js
Abaixo da lnha 115, adicionei:
if (user.profile.toUpperCase() === "USER") {
        setShowAllTickets(true);
        }
          // eslint-disable-next-line react-hooks/exhaustive-deps


ficando assim:
 useEffect(() => {
    if (user.profile.toUpperCase() === "ADMIN") {
      setShowAllTickets(true);
    }
          // eslint-disable-next-line react-hooks/exhaustive-deps
   if (user.profile.toUpperCase() === "USER") {
        setShowAllTickets(true);
        }
          // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

Poderia ter feito um else, mas não sei bem as sintaxes de react, então fiz um novo if mesmo.
Fiz um novo rebuild do frontend e já era.

Com isso setei meus colaboradores pra user e todos possuem acesso as conversas.

Só postei para salvar o que fiz, e como existiam mais pessoas interessadas...
