### ISSUE TITLE
Sugestão de melhoria: Envio de mensagem em massa

### ISSUE THREAD

**Issue by Kouthk** [canove/whaticket#319]
Seria interessante poder realizar o envio de mensagens informativas em massa para os numeros que estivessem cadastrados para essa funcionalidade.

Caso alguém saiba como implementar e não tenha tempo, se conseguir dar algumas dicas de como fazer eu posso estar tentando e assim que estiver pronto abrir uma PR aqui no repositorio. =)

**Comment by maxivane** [comment]
Um trabalho danado, ai posta umas coisas dessa aqui e nego vende no ML e ganha mais dinheiro que vc que deu de graça.. 
Ja tem whaticket com chatbot AVANÇADO e integrado com API, envio campanha, mensagem programada, agendamento de consulta, exame, se for ver ta tendo mais funções que o proprio SaaS. kkkkkkk todas essas coisas nao sao novidades no whaticket, o problema é que ninguem vai postar aqui pra depois ver no mercadolivre anuncio do whaticket por 900,00. 1000,00. 2000,00. 3000,00 com um código qe tu teve dor de cabeça e postou de graça...

**Comment by Kouthk** [comment]
Essa questão de ter um trabalho danado para colocar uma funcionalidad e os caras venderem o codigo, sem ao menos realizar uma contribuição sequer é bem foda mesmo. 
Mas bem, infelizmete nao vejo uma forma de parar com isso. Já vi varios videos de pessoas vendendo no youtube e só altetrando o nome..

**Comment by rochac2lee** [comment]
@ricco-douro Desculpa ai parceiro mas eu implementei isso e tenho clientes que rodam mais de 7 mil envios por dia e não bloqueia de jeito nenhum. 
O ideal é apenas configurar um tempo entre cada disparo pois se rodar tudo no mesmo segundo é obvio que caracteriza envio por robô, tomando ban como consequencia.

**Comment by w3nder** [comment]
> Bom dia eu implementei isso na minha versão e gostaria de dar algumas dicas relativamente aos envios em massa:
> 
> **Atenção com os termos de uso do Whatsapp e com os riscos de bloquearem os números de disparo**
> 
> 1 - Sempre associem uma imagem a um disparo, e coloquem a mensagem de texto como caption da mensagem 2 - Criem várias versões da caption, que tem formas diferente de dizer a mesma coisa. O checksum com o qual o whatsap valida a mensagem resulta diferente (eu sempre tenho 5 modelos para a mesma mensagem) 3 - Não enviem mais de 600 mensagens/dia (depois de vários testes, este é um limite seguro), 4 - Mandem as mensagens com intervalos aleatórios, dentro de limites pré estabelecidos

Eu também implementei isso.

Eu envio bastante é também ainda não tive o prazer do block :) 
Em todas as mensagem que envio a mensagem nunca vai igual, coloco uma saudação, pego o nome do contato para a mensagem não ficar igual. 

O intervalo também é fundamental.

**Comment by hiagodotme** [comment]
@w3nder qual intervalo vocês escalam? Tipo a cada envio um número aleatório entre 400 - 3000 ms ?
