### ISSUE TITLE
erro ao rodar o comando npm build

### ISSUE THREAD

**Issue by egondadalt** [canove/whaticket#322]
Pessoal, boa tarde. Tentei rodar o comando npm run build porém sempre me surge esse erro:

Já tentei rodar em ambiente debian 11 e agora estou utilizando o Ubuntu 20.

Sabem me dar uma ajudar nesse?

`dadalt@dadalt-Virtual-Machine:~/whaticket/backend$ npm run build

> backend@1.0.0 build /home/dadalt/whaticket/backend
> tsc

node_modules/@node-redis/client/dist/lib/client/index.d.ts:31:19 - error TS1005: ']' expected.

31     [P in keyof M as M[P] extends never ? never : P]: {
                     ~~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:31:22 - error TS1005: ';' expected.

31     [P in keyof M as M[P] extends never ? never : P]: {
                        ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:31:27 - error TS1005: ';' expected.

31     [P in keyof M as M[P] extends never ? never : P]: {
                             ~~~~~~~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:31:52 - error TS1005: ';' expected.

31     [P in keyof M as M[P] extends never ? never : P]: {
                                                      ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:31:53 - error TS1128: Declaration or statement expected.

31     [P in keyof M as M[P] extends never ? never : P]: {
                                                       ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:32:21 - error TS1005: ',' expected.

32         [C in keyof M[P]]: RedisClientCommandSignature<M[P][C]>;
                       ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:32:26 - error TS1005: ';' expected.

32         [C in keyof M[P]]: RedisClientCommandSignature<M[P][C]>;
                            ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:32:64 - error TS1005: '(' expected.

32         [C in keyof M[P]]: RedisClientCommandSignature<M[P][C]>;
                                                                  ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:34:1 - error TS1128: Declaration or statement expected.

34 };
   ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:36:19 - error TS1005: ']' expected.

36     [P in keyof S as S[P] extends never ? never : P]: RedisClientCommandSignature<S[P]>;
                     ~~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:36:22 - error TS1005: ';' expected.

36     [P in keyof S as S[P] extends never ? never : P]: RedisClientCommandSignature<S[P]>;
                        ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:36:27 - error TS1005: ';' expected.

36     [P in keyof S as S[P] extends never ? never : P]: RedisClientCommandSignature<S[P]>;
                             ~~~~~~~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:36:52 - error TS1005: ';' expected.

36     [P in keyof S as S[P] extends never ? never : P]: RedisClientCommandSignature<S[P]>;
                                                      ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:36:53 - error TS1128: Declaration or statement expected.

36     [P in keyof S as S[P] extends never ? never : P]: RedisClientCommandSignature<S[P]>;
                                                       ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:36:88 - error TS1005: '(' expected.

36     [P in keyof S as S[P] extends never ? never : P]: RedisClientCommandSignature<S[P]>;
                                                                                          ~

node_modules/@node-redis/client/dist/lib/client/index.d.ts:37:1 - error TS1128: Declaration or statement expected.

37 };
   ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:9:19 - error TS1005: ']' expected.

9     [P in keyof M as M[P] extends never ? never : P]: {
                    ~~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:9:22 - error TS1005: ';' expected.

9     [P in keyof M as M[P] extends never ? never : P]: {
                       ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:9:27 - error TS1005: ';' expected.

9     [P in keyof M as M[P] extends never ? never : P]: {
                            ~~~~~~~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:9:52 - error TS1005: ';' expected.

9     [P in keyof M as M[P] extends never ? never : P]: {
                                                     ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:9:53 - error TS1128: Declaration or statement expected.

9     [P in keyof M as M[P] extends never ? never : P]: {
                                                      ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:10:21 - error TS1005: ',' expected.

10         [C in keyof M[P]]: RedisClientMultiCommandSignature<M[P][C], M, S>;
                       ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:10:26 - error TS1005: ';' expected.

10         [C in keyof M[P]]: RedisClientMultiCommandSignature<M[P][C], M, S>;
                            ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:10:75 - error TS1005: '(' expected.

10         [C in keyof M[P]]: RedisClientMultiCommandSignature<M[P][C], M, S>;
                                                                             ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:12:1 - error TS1128: Declaration or statement expected.

12 };
   ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:14:19 - error TS1005: ']' expected.

14     [P in keyof S as S[P] extends never ? never : P]: RedisClientMultiCommandSignature<S[P], M, S>;
                     ~~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:14:22 - error TS1005: ';' expected.

14     [P in keyof S as S[P] extends never ? never : P]: RedisClientMultiCommandSignature<S[P], M, S>;
                        ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:14:27 - error TS1005: ';' expected.

14     [P in keyof S as S[P] extends never ? never : P]: RedisClientMultiCommandSignature<S[P], M, S>;
                             ~~~~~~~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:14:52 - error TS1005: ';' expected.

14     [P in keyof S as S[P] extends never ? never : P]: RedisClientMultiCommandSignature<S[P], M, S>;
                                                      ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:14:53 - error TS1128: Declaration or statement expected.

14     [P in keyof S as S[P] extends never ? never : P]: RedisClientMultiCommandSignature<S[P], M, S>;
                                                       ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:14:99 - error TS1005: '(' expected.

14     [P in keyof S as S[P] extends never ? never : P]: RedisClientMultiCommandSignature<S[P], M, S>;
                                                                                                     ~

node_modules/@node-redis/client/dist/lib/client/multi-command.d.ts:15:1 - error TS1128: Declaration or statement expected.

15 };
   ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:10:19 - error TS1005: ']' expected.

10     [P in keyof M as M[P] extends never ? never : P]: {
                     ~~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:10:22 - error TS1005: ';' expected.

10     [P in keyof M as M[P] extends never ? never : P]: {
                        ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:10:27 - error TS1005: ';' expected.

10     [P in keyof M as M[P] extends never ? never : P]: {
                             ~~~~~~~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:10:52 - error TS1005: ';' expected.

10     [P in keyof M as M[P] extends never ? never : P]: {
                                                      ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:10:53 - error TS1128: Declaration or statement expected.

10     [P in keyof M as M[P] extends never ? never : P]: {
                                                       ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:11:21 - error TS1005: ',' expected.

11         [C in keyof M[P]]: RedisClusterMultiCommandSignature<M[P][C], M, S>;
                       ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:11:26 - error TS1005: ';' expected.

11         [C in keyof M[P]]: RedisClusterMultiCommandSignature<M[P][C], M, S>;
                            ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:11:76 - error TS1005: '(' expected.

11         [C in keyof M[P]]: RedisClusterMultiCommandSignature<M[P][C], M, S>;
                                                                              ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:13:1 - error TS1128: Declaration or statement expected.

13 };
   ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:15:19 - error TS1005: ']' expected.

15     [P in keyof S as S[P] extends never ? never : P]: RedisClusterMultiCommandSignature<S[P], M, S>;
                     ~~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:15:22 - error TS1005: ';' expected.

15     [P in keyof S as S[P] extends never ? never : P]: RedisClusterMultiCommandSignature<S[P], M, S>;
                        ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:15:27 - error TS1005: ';' expected.

15     [P in keyof S as S[P] extends never ? never : P]: RedisClusterMultiCommandSignature<S[P], M, S>;
                             ~~~~~~~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:15:52 - error TS1005: ';' expected.

15     [P in keyof S as S[P] extends never ? never : P]: RedisClusterMultiCommandSignature<S[P], M, S>;
                                                      ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:15:53 - error TS1128: Declaration or statement expected.

15     [P in keyof S as S[P] extends never ? never : P]: RedisClusterMultiCommandSignature<S[P], M, S>;
                                                       ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:15:100 - error TS1005: '(' expected.

15     [P in keyof S as S[P] extends never ? never : P]: RedisClusterMultiCommandSignature<S[P], M, S>;
                                                                                                      ~

node_modules/@node-redis/client/dist/lib/cluster/multi-command.d.ts:16:1 - error TS1128: Declaration or statement expected.

16 };
   ~

node_modules/@node-redis/search/dist/commands/index.d.ts:113:36 - error TS1110: Type expected.

113 export declare type PropertyName = `${'@' | '$.'}${string}`;
                                       ~~~


Found 49 errors.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! backend@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the backend@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dadalt/.npm/_logs/2021-12-10T20_13_59_093Z-debug.log
`



LOG:

`
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle backend@1.0.0~prebuild: backend@1.0.0
6 info lifecycle backend@1.0.0~build: backend@1.0.0
7 verbose lifecycle backend@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle backend@1.0.0~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dadalt/whaticket/backend/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/ga>
9 verbose lifecycle backend@1.0.0~build: CWD: /home/dadalt/whaticket/backend
10 silly lifecycle backend@1.0.0~build: Args: [ '-c', 'tsc' ]
11 silly lifecycle backend@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle backend@1.0.0~build: Failed to exec build script
13 verbose stack Error: backend@1.0.0 build: `tsc`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid backend@1.0.0
15 verbose cwd /home/dadalt/whaticket/backend
16 verbose Linux 5.11.0-41-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 2
22 error backend@1.0.0 build: `tsc`
22 error Exit status 2
23 error Failed at the backend@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
`

**Comment by rochac2lee** [comment]
1 - Remova essas duas libs;
![image](https://user-images.githubusercontent.com/60928171/145636141-c273fe96-1e0c-4557-bcfa-c278210af723.png)
2 - Remova a pasta dist e node_modules
3 - Remova o package-lock.json
4 - Execute npm install && npm run build

**Comment by egondadalt** [comment]
Funcionou perfeitamente. Muito obrigado! Espero contribuir com o projeto.
