### ISSUE TITLE
CUIDADO!!!!!!!!

### ISSUE THREAD

**Issue by jccalbuquerque** [canove/whaticket#323]
Tenho muitos anos na TI, mas sempre me surpreendo com tipos oportunistas sem caráter (não podemos chamar de pessoas ou profissionais).
Já vi muitas vulnerabilidades e o que eu fazia? Avisa o colega dos riscos e ajudava com soluções! Nunca peguei um fonte sem permissão na minha vida.
Este repositório é uma enorme oportunidade!
Estude, implemente, corra atrás, evolua sua versão. Se não souber, peça ajuda para um colega e seja honesto.

EPISÓDIO 1) Sem tempo para me dedicar a criação de um site para mim, contratei um grupo e paguei. Até aqui tudo bem. 
Tempo depois recebo um contato de uma pessoa se dizendo dona do site, e era! Vi no registro.br datas de criação,etc
Descobri que me venderam produto oriundo de web crawler.
O mais certo era tirar o meu do ar e tive que fazer outro. E tive que arrumar tempo e ficar no prejuízo.Vamos em frente!

EPISÓDIO 2) Entre projetos React,PHP e Flutter, me aventurei no whaticket e achei fantástico. 
Já possuo outros sistemas e apis semelhantes, mas gostei do whaticket.
Fiz uma parceria com uma pessoa na qual entendi que essa parceira seria boa para ambos (por isso parceria).
Liberei o código em uma VPS dele.
Ele sem saber, pediu ajuda a outro colega, resumindo: esse cara viu a "oportunidade" e roubou o código fonte!
Hoje anda vendendo o código a varrer na internet.
Pesquisei muito antes de desenhar como eu faria o meu chatbot dentro do whaticket e optei por fazer pensando como um plano de contas contábil e inclusive gerando o FLUXOGRAMA visual 
para o usuário visualizar como se comporta. Não que seja algo inovador , mas não encontrei nenhum que trabalhasse dessa forma.
Portanto, se comprarem esse código, pelo menos comprem sabendo que é oriundo de roubo.A "marca" dele é o FLUXOGRAMA.
Tenho funções dentro dele que me enviam IPs de onde estão utilizando. Coletei muitas informações do ladrão, inclusive endereço e muitas informações.
Sempre que eu descriptografava os dados coletados eu chamava o cara no whatsapp e o discurso dele era o mais puro do mundo! Inocente!
Hoje ainda deu a desculpa mais esfarrapada, acho que cansou de inventar desculpas "bonitas".
Mas o que fazemos com lixo? Jogamos fora e seguimos a vida!
Vai assim mesmo amigo, estou dando corda, vai vendendo... instalando... quero que se dê muito bem... parao tombo ser maior!

Já imaginaram se esse cara fosse gerente de banco? Ah... tenho acesso a conta das pessoas... vou roubar!
Se esse cara ver dinheiro em cima de uma mesa? Ah... deram mole... vou roubar!
Fiquem em paz e protejam-se de tipos assim.
Sorte a todos.

**Comment by ertprs** [comment]
> Tenho muitos anos na TI, mas sempre me surpreendo com tipos oportunistas sem caráter (não podemos chamar de pessoas ou profissionais). Já vi muitas vulnerabilidades e o que eu fazia? Avisa o colega dos riscos e ajudava com soluções! Nunca peguei um fonte sem permissão na minha vida. Este repositório é uma enorme oportunidade! Estude, implemente, corra atrás, evolua sua versão. Se não souber, peça ajuda para um colega e seja honesto.
> 
> EPISÓDIO 1) Sem tempo para me dedicar a criação de um site para mim, contratei um grupo e paguei. Até aqui tudo bem. Tempo depois recebo um contato de uma pessoa se dizendo dona do site, e era! Vi no registro.br datas de criação,etc Descobri que me venderam produto oriundo de web crawler. O mais certo era tirar o meu do ar e tive que fazer outro. E tive que arrumar tempo e ficar no prejuízo.Vamos em frente!
> 
> EPISÓDIO 2) Entre projetos React,PHP e Flutter, me aventurei no whaticket e achei fantástico. Já possuo outros sistemas e apis semelhantes, mas gostei do whaticket. Fiz uma parceria com uma pessoa na qual entendi que essa parceira seria boa para ambos (por isso parceria). Liberei o código em uma VPS dele. Ele sem saber, pediu ajuda a outro colega, resumindo: esse cara viu a "oportunidade" e roubou o código fonte! Hoje anda vendendo o código a varrer na internet. Pesquisei muito antes de desenhar como eu faria o meu chatbot dentro do whaticket e optei por fazer pensando como um plano de contas contábil e inclusive gerando o FLUXOGRAMA visual para o usuário visualizar como se comporta. Não que seja algo inovador , mas não encontrei nenhum que trabalhasse dessa forma. Portanto, se comprarem esse código, pelo menos comprem sabendo que é oriundo de roubo.A "marca" dele é o FLUXOGRAMA. Tenho funções dentro dele que me enviam IPs de onde estão utilizando. Coletei muitas informações do ladrão, inclusive endereço e muitas informações. Sempre que eu descriptografava os dados coletados eu chamava o cara no whatsapp e o discurso dele era o mais puro do mundo! Inocente! Hoje ainda deu a desculpa mais esfarrapada, acho que cansou de inventar desculpas "bonitas". Mas o que fazemos com lixo? Jogamos fora e seguimos a vida! Vai assim mesmo amigo, estou dando corda, vai vendendo... instalando... quero que se dê muito bem... parao tombo ser maior!
> 
> Já imaginaram se esse cara fosse gerente de banco? Ah... tenho acesso a conta das pessoas... vou roubar! Se esse cara ver dinheiro em cima de uma mesa? Ah... deram mole... vou roubar! Fiquem em paz e protejam-se de tipos assim. Sorte a todos.

Que coisa hein, lamentável esse tipo de atitude dessas pessoas. Mas é bola para frente infelizmente.

Tudo de bom ai para você e espero que as pessoas se conscientizem mais nessa questão de abrir a VPS ou acesso remoto para outros que dizem ter o interesse em ajudar.

Eu ajudo da maneira que posso, prefiro passar explicado e detalhado do que fazer.
