### ISSUE TITLE
Determinar fila através de palavras-chave 

### ISSUE THREAD

**Issue by joazvsoares** [canove/whaticket#325]
Olá, primeiramente gostaria de parabenizar os envolvidos nesse projeto fantástico!

Eu gostaria de adicionar uma funcionalidade em que a fila possa ser determinada com base em palavras chave, por exemplo:

"Eu gostaria de **mais informações** sobre o produto" > Poderia ir direto para fila "Comercial"
"Estou com um **problema** na minha compra" > Poderia ir direto para fila "Atendimento"

Eu poderia implementar e criar o Pull Request se fizer sentido para outras pessoas também.

Pensei em criar um novo campo no model Queue, algo como "keywords" em que o usuário possa adicionar as palavras-chave, e com isso comparar com o conteúdo da mensagem, a desvantagem dessa implementação é que precisaria percorrer a lista que Queues. 

Estou aberto a sugestões de implementação.

**Comment by fogolin** [comment]
Acho que faz sentido, mas precisa colocar um controle para que, quando a conversa for aceita por um atendente, interrompa a identificação de palavras chave, para não ficar tentando redistribuir para uma fila diferente quando já está em atendimento.

**Comment by Kouthk** [comment]
Acho que faz sentido, porém é interessante que no painel de ADM tenha uma opção de 'Ativar' e 'Desativar' essa funcionalidade. =)
