### ISSUE TITLE
[Feature] Transfer ticket.

### ISSUE THREAD

**Issue by leobaldoneto** [canove/whaticket#33]
I will try to implement transfer ticket feature.

requirements:

- change assigned operator;
- log an system message informing about the transfer.

**Comment by leobaldoneto** [comment]
Hi @ronna 

It isn't hard, but I'm learning javascript, yet. Whaticket already have an transfer button, but needs to implement the backend algorithm and interface.

**Comment by canove** [comment]
> I will try to implement transfer ticket feature.
> 
> requirements:
> 
> * change assigned operator;
> * log an system message informing about the transfer.

Hey @leobaldoneto. Great idea!

I thought about transfer option in this way: 

Clicking transfer button shows up an Modal with a Autocomplete field, where you can type an User name to select it and click "ok". It should be like the "New ticket" option.

Clicking ok should do a PUT on /tickets/ticketId, with a json containing new ticket's user Id
```
{
 userId: 22
}
```

Would be great if you could implement something like this.

**Comment by leobaldoneto** [comment]
@canove 
Thank you about the direction, it will help me!

**Comment by mayconlemosCloud** [comment]
Any news about ticket transfer?

**Comment by leobaldoneto** [comment]
> Any news about ticket transfer?

Sorry about the delay, I had an busy week. I will look at this on next thursday, if the issue stills open.

**Comment by srgoogle23** [comment]
ainda está de pé?

**Comment by wirys** [comment]
Comecei a desenvolver ontem essa funcionalidade estou realizando alguns testes e irei liberar para o canove aprovar

**Comment by wirys** [comment]
![image](https://user-images.githubusercontent.com/31362538/96803172-e544e900-13e1-11eb-9e41-4665d95a555e.png)

**Comment by mayconlemos** [comment]
Ficou show. Nessa implementação, você conseguiu colocar equipes ou departamentos também, na hora do cadastro? Tem como disponibilizar o código fonte até canove aprovar??

**Comment by wirys** [comment]
Somente Implementei a transferência de técnicos, estou ajustando ainda alguns bugs creio que ate amanha da para disponibilizar

**Comment by wirys** [comment]
Esta como pull Request pra quem quiser baixar pra testar

**Comment by alvares** [comment]
> Esta como pull Request pra quem quiser baixar pra testar

Bacana, como posso testar? Existe alguma branch específica? Ou aguardar ir para a master?

**Comment by wirys** [comment]
> Bacana, como posso testar? Existe alguma branch específica? Ou aguardar ir para a master?
Voce pode Baixar usando esse Link  https://github.com/wirys/whaticket.git

**Comment by canove** [comment]
@wirys thanks for this PR! Great job.

I've changed naming conventions, styling and some cleanup. I also created the backend part of this function, to update tickets list on both old and new user. 

closed by https://github.com/canove/whaticket/commit/63fdecd0387cee288399b3140afa6b9a49b796cb
