### ISSUE TITLE
Mensagem de saudação

### ISSUE THREAD

**Issue by josep112** [canove/whaticket#332]
Nao entra a mensagem de saudação quando envio uma mensagem, nao estou usando emoji , ja alterei varias vezes o texto , troquei o qrcode, isso aconteceu depois que criei filas e deletei

**Comment by Kouthk** [comment]
o dispositivo precisa ter no minimo 2 filas cadastradas para retornar a mensagem configurada.

**Comment by josep112** [comment]
ok, deu certo obrigado!
