### ISSUE TITLE
Lista de opções

### ISSUE THREAD

**Issue by jailtonurbano** [canove/whaticket#334]
Ao chamar a primeira vez o sistema mostra a lista de opções.
Cria o contato automaticamente corretamente.

Porém, se o mesmo contato chama ele já entra na fila anteriormente utilizada.
Tem como ajustar isso?

**Comment by lucasdsb1** [comment]
Por padrão, se o usuário retornar ao atendimento em menos de 2 horas, o atendimento anteriormente fechado retorna. No meu caso, alterei isso para 15 minutos. Se quiser é só alterar a seguinte o arquivo "backend/src/services/TicketServices/FindOrCreateTicketService.ts".

```
[Op.between]: [+subHours(new Date(), 2), +new Date()]
```

NO MEU CASO, eu alterei para:

```
[Op.between]: [+subMinutes(new Date(), 15), +new Date()]
```

Lembre-se de importar o subMinutes (se for utilizar, é claro):

```
import { subMinutes } from "date-fns";
```
