### ISSUE TITLE
Problema com localização

### ISSUE THREAD

**Issue by smartsolucoesgo** [canove/whaticket#339]
Pelo whaticket nao está recebendo a localização enviada, no telefone aparece normal, porem no whaticket nao chega nada..
alguem com o mesmo problema ?

**Comment by w3nder** [comment]
Whaticket até o momento não suporta envio e recebimento de Localização.

Você pode fazer isso aí do seu lado. ou aguardar até alguém contribuir com essa feat.

**Comment by dantecvip** [comment]
Estarei fazendo um pull request ainda hoje ao qual possibilita recebermos Localizações. Já o envio de localizações através do Whaticket ainda continua pendente.

Caso o envio for de uma localização conhecida, será mostrado os detalhes da localização. Em caso de envio de localizações desconhecidas, será apenas mostrado as coordenadas conforme imagens abaixo:

![image](https://user-images.githubusercontent.com/18131772/149780804-3e2ffd6c-2adb-46b0-93ba-fa042e4c0d98.png)

![image](https://user-images.githubusercontent.com/18131772/149780861-36edf8ca-ec79-40c3-b283-4967f09375f0.png)
