### ISSUE TITLE
Leio o QR CODE, no smartphone diz que tem dispositivo conectado, porém, no WhaTicket o status continuar como "Esperando Leitura QR code"

### ISSUE THREAD

**Issue by thiago29** [canove/whaticket#340]
Mais alguém já teve esse tipo de erro? Abaixo mensagem do terminal:

[1642012225634] INFO: Session: Contabilidade AUTHENTICATED
(node:11916) UnhandledPromiseRejectionWarning: Error: Multi-device is not yet supported by whatsapp-web.js. Please check out https://github.com/pedroslopez/whatsapp-web.js/pull/889 to follow the progress.
    at Client.initialize (/home/thiago/whaticket/backend/node_modules/whatsapp-web.js/src/Client.js:205:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11916) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11916) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1642012230210] INFO: Client disconnected
[1642012234279] WARN:
    message: "Invalid token. We'll try to assign a new one on next request"
    statusCode: 403

**Comment by jccalbuquerque** [comment]
Não é compatível com MD

Em qua., 12 de jan. de 2022 15:38, Thiago Mariano ***@***.***>
escreveu:

**Comment by thiago29** [comment]
Desculpa a minha falta de conhecimento, mas o que seria o "MD" a qual vc se refere?

**Comment by w3nder** [comment]
> Multi-device

Multi-device, você está usando o Whatsapp no modo beta.

**Comment by thiago29** [comment]
Perfeito, deu certo! Muito obrigado...
