### ISSUE TITLE
Não consigo loga em outro computador

### ISSUE THREAD

**Issue by Anderson201912** [canove/whaticket#341]
No servidor ele acessa normal, tudo funcionando direito, mais quando e outro computador acessando não loga, fica no loop mais não entra.

![image](https://user-images.githubusercontent.com/85626023/149218479-7b094ed5-6b94-4d80-8296-4b19cd93c918.png)

**Comment by ertprs** [comment]
> No servidor ele acessa normal, tudo funcionando direito, mais quando e outro computador acessando não loga, fica no loop mais não entra.
> 
> ![image](https://user-images.githubusercontent.com/85626023/149218479-7b094ed5-6b94-4d80-8296-4b19cd93c918.png)

aperta o f12 para verificar o que está no console e printa a tela aqui.

**Comment by Anderson201912** [comment]
![image](https://user-images.githubusercontent.com/85626023/149317786-a38952af-4e4e-4fae-bcdc-2e9627c265d2.png)
Fica assim

**Comment by Anderson201912** [comment]
@ertprs Patrício Silva podemos trocar umas ideias no whatsapp, whaticket fiquei com umas duvidas.

**Comment by w3nder** [comment]
> ![image](https://user-images.githubusercontent.com/85626023/149317786-a38952af-4e4e-4fae-bcdc-2e9627c265d2.png) Fica assim

Creio que pelo o log, você já descobriu o problema. 

seu env está configurado para o endereço localhost, 127.0.0.1 é do PC local, só ele vai ter acesso a sua aplicação. 

você tem que editar seu env pro ip da sua rede ou usar esse domínio aí no env.

**Comment by Anderson201912** [comment]
@w3nder valeu cara, isso mesmo, coloquei o ip local, funcionou, mais não estou conseguindo fazer que ele acesse externo, no env coloquei o ddns e nginx, ai volta com loop do login e não acessa externo.
