### ISSUE TITLE
Erro rodar Comuando npx sequelize db:migrate Unknown arguments: modules-path, modulesPath

### ISSUE THREAD

**Issue by iranbk** [canove/whaticket#343]
Ola, estou tentando fazer a instalacao no whaticket, tentei tanto localmente no meu pc, quanto agora na vm da AWS em um ubuntu 18 porem quando vou rodar o comando npx sequelize db:migrate
retorna:

Sequelize CLI [Node: 14.18.3, CLI: 6.3.0, ORM: 5.22.5]

Options:
  --version          Show version number                                                           [boolean]
  --help             Show help                                                                     [boolean]
  --env              The environment to run the command in                 [string] [default: "development"]
  --config           The path to the config file                                                    [string]
  --options-path     The path to a JSON file with additional options                                [string]
  --migrations-path  The path to the migrations folder                      [string] [default: "migrations"]
  --seeders-path     The path to the seeders folder                            [string] [default: "seeders"]
  --models-path      The path to the models folder                              [string] [default: "models"]
  --url              The database connection string to use. Alternative to using --config files     [string]
  --debug            When available show various debug information                [boolean] [default: false]
  --to               Migration name to run migrations until                                         [string]
  --from             Migration name to start migrations from (excluding)                            [string]

Unknown arguments: modules-path, modulesPath

se alguem poder me ajudar

**Comment by vojoobrasil** [comment]
Olá @iranbk, verifique seu arquivo .env do backend, obtive este mesmo erro a um tempo, e era devido a falta do "ponto" do arquivo .env, qualquer coisa me chama no zap que tentamos alguma solução! 27 99263-3735

**Comment by iranbk** [comment]
entao irmao revisei o arquivo e esta certinho... nao achei esse ponto que voce falou, copei o comando do tutorial... vou te chamar irmao obrigado

**Comment by iranbk** [comment]
@vojoobrasil

**Comment by tpmr8** [comment]
Eu passei pelo mesmo erro hoje. Minha solução foi criar um novo arquivo pelo FTP e colar/salvar os dados do arquivo atual. Assim a instalação procedeu normalmente.

**Comment by rodrigofsantos** [comment]
@iranbk @tpmr8 @vojoobrasil  senhores a solução esta no proprio erro eles que a variavel de ambiente não existe modules-path nem modulespath ente whaticket/backend/.sequelizerc e vai achar o seguinte conteudo:

const { resolve } = require("path");

module.exports = {
  "config": resolve(__dirname, "dist", "config", "database.js"),
  "modules-path": resolve(__dirname, "dist", "models"),
  "migrations-path": resolve(__dirname, "dist", "database", "migrations"),
  "seeders-path": resolve(__dirname, "dist", "database", "seeds")
};


Altere a linha 5 para:
"models-path": resolve(__dirname, "dist", "models"),

**Comment by rodrigofsantos** [comment]
Não esqueça de realizar um npm run build novamente ok !!!
