### ISSUE TITLE
Erro ao deletar mensagem enviada

### ISSUE THREAD

**Issue by rumeniquej** [canove/whaticket#346]
Olá, fiz o upgrading dia 18/01/2022 (guiado pelo repositório) agora não consigo deletar mensagem enviada da erro .
 
![Screenshot_20220118-130046_Chrome](https://user-images.githubusercontent.com/17551375/149986617-faead209-2a20-4ef3-95ac-bfe83d870797.jpg)

Outra coisa seria sobre ao clicar nas configurações a página parece cair.

https://user-images.githubusercontent.com/17551375/149986733-11e0d352-f01d-4ac1-9578-ed704b5738fa.mp4

Se alguém puder ajudar agradeço.

**Comment by w3nder** [comment]
Olá,

Fiz uns teste para descobrir o motivo de não remover a mensagem.
Encontrei o problema, 
```
Error: Evaluation failed: TypeError: msg.canRevoke is not a function
    at __puppeteer_evaluation_script__:4:50
```

https://github.com/pedroslopez/whatsapp-web.js/pull/1107

Como pode ver, não é um erro no Whaticket é sim na lib whatsapp-web.js

A correção não foi aceita ainda, enquanto não é aceita, você pode atualizar ai de forma manual.
é quando sair a correção, você só vai precisar atualizar o whatsapp-web.js


Sobre a página de configuração,
Executar a seed específica da criação do token.

`npx sequelize db:seed --seed 20200904070006-create-apiToken-settings.js`

**Comment by rumeniquej** [comment]
Obrigado pela ajuda

**Comment by ertprs** [comment]
![image](https://user-images.githubusercontent.com/62783690/150013851-a8b5f8a5-aa52-4f55-b49b-bc7c47db5cda.png)

Correção é fazer um fork do projeto e editar o arquivo conforme a imagem e no package.json apontar a instalação do whatsapp-web.js para sua conta do github onde vc fez o fork do projeto.

**Comment by andremarretto** [comment]
Olá @ertprs ,  conseguiu funcionar o delete com essa alteração do message.js? Aqui não consegui funcionar.
