### ISSUE TITLE
Erro ao enviar mídia/anexos

### ISSUE THREAD

**Issue by lucasdsb1** [canove/whaticket#347]
Olá pessoal, após a atualização de ontem (18/01/2022), estou tendo problema ao enviar qualquer tipo de mídia. Está recebendo normal, mas não estou conseguindo enviar.

![image](https://user-images.githubusercontent.com/43189494/150127756-a677f472-4f2d-4e96-a2e7-cd22429fc26b.png)

Retirei o try/catch da função SendWhatsAppMedia e obtive esse erro:
![image](https://user-images.githubusercontent.com/43189494/150131809-36e261da-5a0f-44d4-9673-aa30782a7d3e.png)

**Comment by lucasdsb1** [comment]
Resolvi hehe

Para quem estiver com problema, resolve da seguinte maneira:

src/controllers/MessageController.ts

```
export const store = async (req: Request, res: Response): Promise<Response> => {
  const { ticketId } = req.params;
  const { body, quotedMsg }: MessageData = req.body;
  const medias = req.files as Express.Multer.File[];

  const ticket = await ShowTicketService(ticketId);

  SetTicketMessagesAsRead(ticket);

  if (medias) {
    await Promise.all(
      medias.map(async (media: Express.Multer.File) => {
        await SendWhatsAppMedia({ body, media, ticket }); //ESSA LINHA FOI ALTERADA, FALTA A VARIAVEL "body"
      })
    );
  } else {
    await SendWhatsAppMessage({ body, ticket, quotedMsg });
  }

  return res.send();
};
```

**Comment by joazvsoares** [comment]
@lucasdsb1 você acha que devemos fazer um Pull Request com essa correção?

**Comment by lucasdsb1** [comment]
@joazvsoares Acredito que sim, porém não tive tempo (ainda) de analisar qual o impacto total da alteração.

**Comment by fogolin** [comment]
> Resolvi hehe
> 
> Para quem estiver com problema, resolve da seguinte maneira:
> 
> src/controllers/MessageController.ts
> 
> ```
> export const store = async (req: Request, res: Response): Promise<Response> => {
>   const { ticketId } = req.params;
>   const { body, quotedMsg }: MessageData = req.body;
>   const medias = req.files as Express.Multer.File[];
> 
>   const ticket = await ShowTicketService(ticketId);
> 
>   SetTicketMessagesAsRead(ticket);
> 
>   if (medias) {
>     await Promise.all(
>       medias.map(async (media: Express.Multer.File) => {
>         await SendWhatsAppMedia({ body, media, ticket }); //ESSA LINHA FOI ALTERADA, FALTA A VARIAVEL "body"
>       })
>     );
>   } else {
>     await SendWhatsAppMessage({ body, ticket, quotedMsg });
>   }
> 
>   return res.send();
> };
> ```

Essa solução não permite enviar mais de um arquivo de uma só vez. A do @w3nder no https://github.com/canove/whaticket/pull/348 permite. As duas são concorrentes, uma não funciona em conjunto com a outra e, aplicando apenas a solução do W3nder, funcionam as mídias e envio de múltiplos arquivos.

**Comment by lucasdsb1** [comment]
@fogolin exato, seguir com a solução do @w3nder, ou aguarda o a aprovação do PR.
