### ISSUE TITLE
Production, npm run build error

### ISSUE THREAD

**Issue by emmannweb** [canove/whaticket#349]
- No backend, não consegui instalar o pacote (sharp), ele deu error também.

- As linhas de baixo são os erros no console, quando tentei para rodar a comanda build

backend@1.0.0 build /home/deploy/whaticket/backend
> tsc

src/controllers/WhatsAppSessionController.ts:35:8 - error TS2339: Property 'logout' does not exist on type 'Session'                                                                                                                         .

35   wbot.logout();
          ~~~~~~

src/helpers/GetTicketWbot.ts:1:35 - error TS2307: Cannot find module 'whatsapp-web.js' or its corresponding type dec                                                                                                                         larations.

1 import { Client as Session } from "whatsapp-web.js";
                                    ~~~~~~~~~~~~~~~~~

src/helpers/GetWbotMessage.ts:1:40 - error TS2307: Cannot find module 'whatsapp-web.js' or its corresponding type de                                                                                                                         clarations.

1 import { Message as WbotMessage } from "whatsapp-web.js";
                                         ~~~~~~~~~~~~~~~~~

src/helpers/GetWbotMessage.ts:21:40 - error TS7006: Parameter 'msg' implicitly has an 'any' type.

21     const msgFound = chatMessages.find(msg => msg.id.id === messageId);
                                          ~~~

src/libs/wbot.ts:2:24 - error TS2307: Cannot find module 'whatsapp-web.js' or its corresponding type declarations.

2 import { Client } from "whatsapp-web.js";
                         ~~~~~~~~~~~~~~~~~

src/libs/wbot.ts:16:28 - error TS2339: Property 'getChats' does not exist on type 'Session'.

16   const chats = await wbot.getChats();
                              ~~~~~~~~

src/libs/wbot.ts:53:12 - error TS2339: Property 'initialize' does not exist on type 'Session'.

53       wbot.initialize();
              ~~~~~~~~~~

src/libs/wbot.ts:55:12 - error TS2339: Property 'on' does not exist on type 'Session'.

55       wbot.on("qr", async qr => {
              ~~

src/libs/wbot.ts:55:27 - error TS7006: Parameter 'qr' implicitly has an 'any' type.

55       wbot.on("qr", async qr => {
                             ~~

src/libs/wbot.ts:72:12 - error TS2339: Property 'on' does not exist on type 'Session'.

72       wbot.on("authenticated", async session => {
              ~~

src/libs/wbot.ts:72:38 - error TS7006: Parameter 'session' implicitly has an 'any' type.

72       wbot.on("authenticated", async session => {
                                        ~~~~~~~

src/libs/wbot.ts:79:12 - error TS2339: Property 'on' does not exist on type 'Session'.

79       wbot.on("auth_failure", async msg => {
              ~~

src/libs/wbot.ts:79:37 - error TS7006: Parameter 'msg' implicitly has an 'any' type.

79       wbot.on("auth_failure", async msg => {
                                       ~~~

src/libs/wbot.ts:102:12 - error TS2339: Property 'on' does not exist on type 'Session'.

102       wbot.on("ready", async () => {
               ~~

src/libs/wbot.ts:122:14 - error TS2339: Property 'sendPresenceAvailable' does not exist on type 'Session'.

122         wbot.sendPresenceAvailable();
                 ~~~~~~~~~~~~~~~~~~~~~

src/libs/wbot.ts:146:30 - error TS2339: Property 'destroy' does not exist on type 'Session'.

146       sessions[sessionIndex].destroy();
                                 ~~~~~~~

src/services/WbotServices/CheckIsValidContact.ts:11:38 - error TS2339: Property 'isRegisteredUser' does not exist on                                                                                                                          type 'Session'.

11     const isValidNumber = await wbot.isRegisteredUser(`${number}@c.us`);
                                        ~~~~~~~~~~~~~~~~

src/services/WbotServices/CheckNumber.ts:9:42 - error TS2339: Property 'getNumberId' does not exist on type 'Session                                                                                                                         '.

9     const validNumber : any = await wbot.getNumberId(`${number}@c.us`);
                                           ~~~~~~~~~~~

src/services/WbotServices/GetProfilePicUrl.ts:9:36 - error TS2339: Property 'getProfilePicUrl' does not exist on typ                                                                                                                         e 'Session'.

9   const profilePicUrl = await wbot.getProfilePicUrl(`${number}@c.us`);
                                     ~~~~~~~~~~~~~~~~

src/services/WbotServices/ImportContactsService.ts:14:32 - error TS2339: Property 'getContacts' does not exist on ty                                                                                                                         pe 'Session'.

14     phoneContacts = await wbot.getContacts();
                                  ~~~~~~~~~~~

src/services/WbotServices/ImportContactsService.ts:21:34 - error TS7031: Binding element 'number' implicitly has an                                                                                                                          'any' type.

21       phoneContacts.map(async ({ number, name }) => {
                                    ~~~~~~

src/services/WbotServices/ImportContactsService.ts:21:42 - error TS7031: Binding element 'name' implicitly has an 'a                                                                                                                         ny' type.

21       phoneContacts.map(async ({ number, name }) => {
                                            ~~~~

src/services/WbotServices/SendWhatsAppMedia.ts:2:54 - error TS2307: Cannot find module 'whatsapp-web.js' or its corr                                                                                                                         esponding type declarations.

2 import { MessageMedia, Message as WbotMessage } from "whatsapp-web.js";
                                                       ~~~~~~~~~~~~~~~~~

src/services/WbotServices/SendWhatsAppMessage.ts:1:40 - error TS2307: Cannot find module 'whatsapp-web.js' or its co                                                                                                                         rresponding type declarations.

1 import { Message as WbotMessage } from "whatsapp-web.js";
                                         ~~~~~~~~~~~~~~~~~

src/services/WbotServices/wbotMessageListener.ts:11:8 - error TS2307: Cannot find module 'whatsapp-web.js' or its co                                                                                                                         rresponding type declarations.

11 } from "whatsapp-web.js";
          ~~~~~~~~~~~~~~~~~

src/services/WbotServices/wbotMessageListener.ts:178:36 - error TS2339: Property 'sendMessage' does not exist on typ                                                                                                                         e 'Session'.

178     const sentMessage = await wbot.sendMessage(`${contact.number}@c.us`, body);
                                       ~~~~~~~~~~~

src/services/WbotServices/wbotMessageListener.ts:192:40 - error TS2339: Property 'sendMessage' does not exist on typ                                                                                                                         e 'Session'.

192         const sentMessage = await wbot.sendMessage(
                                           ~~~~~~~~~~~

src/services/WbotServices/wbotMessageListener.ts:248:31 - error TS2339: Property 'getContactById' does not exist on                                                                                                                          type 'Session'.

248       msgContact = await wbot.getContactById(msg.to);
                                  ~~~~~~~~~~~~~~

src/services/WbotServices/wbotMessageListener.ts:259:38 - error TS2339: Property 'getContactById' does not exist on                                                                                                                          type 'Session'.

259         msgGroupContact = await wbot.getContactById(msg.to);
                                         ~~~~~~~~~~~~~~

src/services/WbotServices/wbotMessageListener.ts:261:38 - error TS2339: Property 'getContactById' does not exist on                                                                                                                          type 'Session'.

261         msgGroupContact = await wbot.getContactById(msg.from);
                                         ~~~~~~~~~~~~~~

src/services/WbotServices/wbotMessageListener.ts:428:8 - error TS2339: Property 'on' does not exist on type 'Session                                                                                                                         '.

428   wbot.on("message_create", async msg => {
           ~~

src/services/WbotServices/wbotMessageListener.ts:428:35 - error TS7006: Parameter 'msg' implicitly has an 'any' type                                                                                                                         .

428   wbot.on("message_create", async msg => {
                                      ~~~

src/services/WbotServices/wbotMessageListener.ts:432:8 - error TS2339: Property 'on' does not exist on type 'Session                                                                                                                         '.

432   wbot.on("media_uploaded", async msg => {
           ~~

src/services/WbotServices/wbotMessageListener.ts:432:35 - error TS7006: Parameter 'msg' implicitly has an 'any' type                                                                                                                         .

432   wbot.on("media_uploaded", async msg => {
                                      ~~~

src/services/WbotServices/wbotMessageListener.ts:436:8 - error TS2339: Property 'on' does not exist on type 'Session                                                                                                                         '.

**Comment by rcalbo** [comment]
Qual versão do node?
Tive o mesmo problema e troquei a versão do node para 14 e funcionou legal.

**Comment by emmannweb** [comment]
Estou usando a versão 14, quando rodei o build falou q não achou o mudule: whatsapp-web.js

**Comment by eduardofiorini** [comment]
Estou usando o nodejs versão 16.13.1 e apresenta o mesmo erro:
src/services/WbotServices/CheckNumber.ts:9:42 - error TS2339: Property 'getNumberId' does not exist on type 'Session'.
9     const validNumber : any = await wbot.getNumberId(`${number}@c.us`);

**Comment by eduardofiorini** [comment]
O erro ainda persiste na versão 16 do nodejs
