### ISSUE TITLE
Erro 400 Quando tento adicionar numero de celular a parte

### ISSUE THREAD

**Issue by allisonwilliancandido** [canove/whaticket#350]
@canove 

Quando tento adicionar um numero de celular avulso no log apresenta esse erro 400

Ja fiz no formato como mostrado do placeholder 5543999999999 e sem o nono digito tbm 554399999999 

Mas mostra o erro WARN:
    message: "ERR_WAPP_INVALID_CONTACT"
    statusCode: 400

**Comment by lucasdsb1** [comment]
Mesmo problema aqui. Mas em uma das instâncias apenas. A outra instância está salvando normal

**Comment by lucasdsb1** [comment]
Fiz alguns testes e percebi que o problema ocorre na versão business e não é um problema do Whaticket, e sim da lib Whatsapp-web.js, cujo a validação "isRegisteredUser" parou de funcionar.

**Comment by allisonwilliancandido** [comment]
entendi lucas. vlw. 
o whats deve ter lançado alguma atualização entao
