### ISSUE TITLE
Nenhum historico é apresentado quando inicia a conversa ou depois

### ISSUE THREAD

**Issue by allisonwilliancandido** [canove/whaticket#351]
![Screenshot_67](https://user-images.githubusercontent.com/77209255/150424157-c9e005ea-adc0-4251-b0d3-c5b6cf51854b.png)
 Depois de iniciar a conversa o historio ou mensagens que foram enviadas não são exibidas na tela do whaticket

**Comment by Queenzao** [comment]
Isso é normal do sistema, cada ticket só grava a conversa do id do ticket no banco de dados.
Você pode dar uma olhada no que o Pedro fez e disponibilizou no YouTube para adaptar no seu sistema.

```
https://youtu.be/rE4_zSHqN2M
```

**Comment by allisonwilliancandido** [comment]
> Isso é normal do sistema, cada ticket só grava a conversa do id do ticket no banco de dados. Você pode dar uma olhada no que o Pedro fez e disponibilizou no YouTube para adaptar no seu sistema.
> 
> ```
> https://youtu.be/rE4_zSHqN2M
> ```

opa Queenzo obrigado por responder.

Entendi quanto ao historico. Mas o que quis dizer é que no momento do atendimento, quando ainda está aberto, não aparece nada de mensagem quando é enviada ou quando é recebida.
