### ISSUE TITLE
Instalei o Whaticket so que está so que está dando erro na hora de cadastrar um novo usuário 

### ISSUE THREAD

**Issue by AndresJoseColina** [canove/whaticket#352]
Está dando erro na hora de cadastrar um novo usuário, alguém poderia me ajudar?
disse nenhuma configuração encontrada com esta ID. no cmd disse " message: "ERR_NO_SETTING_FOUND"
    statusCode: 404"

**Comment by w3nder** [comment]
@AndresJoseColina 
Opa, você rodou o comando `npx sequelize db:seed:all` ?

Tem uma seed que é executado quando você roda o comando acima, que vai criar um registro na tabela.
Dessa forma, você vai conseguir fazer o cadastro.

**Comment by AndresJoseColina** [comment]
> 
 Rodei sim, no \backend, fiz toda a instalação. npx sequelize seed:all

Sequelize CLI [Node: 14.15.0, CLI: 5.5.1, ORM: 5.22.5]

sequelize [command]

Commands:
  sequelize db:migrate                        Run pending migrations
  sequelize db:migrate:schema:timestamps:add  Update migration table to have timestamps
  sequelize db:migrate:status                 List the status of all migrations
  sequelize db:migrate:undo                   Reverts a migration
  sequelize db:migrate:undo:all               Revert all migrations ran
  sequelize db:seed                           Run specified seeder
  sequelize db:seed:undo                      Deletes data from the database
  sequelize db:seed:all                       Run every seeder
  sequelize db:seed:undo:all                  Deletes data from the database
  sequelize db:create                         Create database specified by configuration
  sequelize db:drop                           Drop database specified by configuration
  sequelize init                              Initializes project
  sequelize init:config                       Initializes configuration
  sequelize init:migrations                   Initializes migrations
  sequelize init:models                       Initializes models
  sequelize init:seeders                      Initializes seeders
  sequelize migration:generate                Generates a new migration file                 [aliases: migration:create]
  sequelize model:generate                    Generates a model and its migration                [aliases: model:create]
  sequelize seed:generate                     Generates a new seed file                           [aliases: seed:create]

Options:
  --help     Show help                                                                                         [boolean]
  --version  Show version number                                                                               [boolean]

Unknown arguments: config, seed:all

**Comment by w3nder** [comment]
> > 
> 
> Rodei sim, no \backend, fiz toda a instalação. npx sequelize seed:all
> 
> Sequelize CLI [Node: 14.15.0, CLI: 5.5.1, ORM: 5.22.5]
> 
> sequelize [command]
> 
> Commands: sequelize db:migrate Run pending migrations sequelize db:migrate:schema:timestamps:add Update migration table to have timestamps sequelize db:migrate:status List the status of all migrations sequelize db:migrate:undo Reverts a migration sequelize db:migrate:undo:all Revert all migrations ran sequelize db:seed Run specified seeder sequelize db:seed:undo Deletes data from the database sequelize db:seed:all Run every seeder sequelize db:seed:undo:all Deletes data from the database sequelize db:create Create database specified by configuration sequelize db:drop Drop database specified by configuration sequelize init Initializes project sequelize init:config Initializes configuration sequelize init:migrations Initializes migrations sequelize init:models Initializes models sequelize init:seeders Initializes seeders sequelize migration:generate Generates a new migration file [aliases: migration:create] sequelize model:generate Generates a model and its migration [aliases: model:create] sequelize seed:generate Generates a new seed file [aliases: seed:create]
> 
> Options: --help Show help [boolean] --version Show version number [boolean]
> 
> Unknown arguments: config, seed:all

Executou, só que deu erro ali. `Unknown arguments: config, seed:all`

Você configurou o arquivo .env? 
`cp .env.example .env`
depois de adicionar as configuração do banco de dados, rodou o `npm run build`?

**Comment by AndresJoseColina** [comment]
configurei sim. rodei tudo conforme os passos , verifiquei as tabelas no MySQL foram criadas certinho 12 tabelas

**Comment by AndresJoseColina** [comment]
NODE_ENV=
BACKEND_URL=localhost
FRONTEND_URL=localhost:3000
PROXY_PORT=8080
PORT=8080

DB_DIALECT=mysql
DB_HOST=localhost
DB_USER=whaticket
DB_PASS=whaticket
DB_NAME=whaticket

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756

estou rodando no localhost

**Comment by AndresJoseColina** [comment]
npm install
npm run build
npx sequelize db:migrate
npx sequelize seed:all
npm start

cd frontend
npm install
npm run build
npm start

**Comment by kaoehenrik** [comment]
Eu estou fazendo a instalação Local, e também estou com esse mesmo problema..

**Comment by mdestafadilah** [comment]
> Eu estou fazendo a instalação Local, e também estou com esse mesmo problema..

it's resolve now?
