### ISSUE TITLE
Não é possível ler qrcode, problema no módulo puppeteer

### ISSUE THREAD

**Issue by AdrianoRobson** [canove/whaticket#354]
Um bug no módulo puppeteer está impossibilitando a leitura do qrcode, não é mais possível conectar o dispositivo.
Abaixo um trecho da exception gerada após a tentativa de leitura do qrcode pelo dispositivo:
/Downloads/whaticket/backend/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221
            throw new Error('Evaluation failed: ' + helper_js_1.helper.getExceptionMessage(exceptionDetails));
                  ^

**Comment by LinkyS1** [comment]
Comigo está acontecendo algo parecido, ele até le o QR Code, porem não conecta no Whaticket.

**Comment by AdrianoRobson** [comment]
> Comigo ocorre a mesma coisa: ![image](https://user-images.githubusercontent.com/98433279/151081014-f36aaf90-8ee4-4bb1-99be-e8553104bacd.png)

Roda esse comando no diretorio backend
$ npm update whatsapp-web.js
Era problema da api do pedro lopez e ja foi atualizado agora pouco
