### ISSUE TITLE
error send media

### ISSUE THREAD

**Issue by swalayan-hasbuna** [canove/whaticket#356]
![image](https://user-images.githubusercontent.com/74512439/151226404-00d066f1-538b-4518-8161-23f341792e63.png)

**Comment by swalayan-hasbuna** [comment]
anybody can help me?

**Comment by kozac** [comment]
same problem here :(

**Comment by w3nder** [comment]
https://github.com/canove/whaticket/pull/348

**Comment by swalayan-hasbuna** [comment]
how to aplly.. ?

**Comment by LinkyS1** [comment]
kozan, what did you do to solve?

**Comment by swalayan-hasbuna** [comment]
please tell me how to apply the solution?

**Comment by LinkyS1** [comment]
pm2 stop all -> pm2 start all
