### ISSUE TITLE
O Build falho no Backend (sharp)

### ISSUE THREAD

**Issue by emmannweb** [canove/whaticket#357]
Mesmo no ambiente de desenvolvimento o build falhou, o pacote sharp está dando problema, e não achei no package.json, mesmo colocando, ele continua dando pau. favor olha o build tanto no ambiente de desenvolvimento e na produção.

**Comment by ricardoapaes** [comment]
@emmannweb Aqui no meu deu problema com node 16. Usei o node 14 e está funcionando corretamente.
Dá pra usar o [nvm](https://github.com/nvm-sh/nvm) pra instalar várias versões do nodejs.

Obs: No windows use essa versão [aqui](https://github.com/coreybutler/nvm-windows).
