### ISSUE TITLE
Other Session Problem?

### ISSUE THREAD

**Issue by KatiaSishost** [canove/whaticket#36]
i fresh installation to test the new version...

and i cant register accout... and you can logging with an inexistent accounts.

(i cleared the browser.)

all database has been installed without problems.

**Comment by canove** [comment]
Hi Katia. There is indeed an issue with session handler. I'm still working in a better solution.

**Comment by canove** [comment]
@KatiaSishost , I just made a little change on auth logic. Can you give it a try and share your results?

**Comment by KatiaSishost** [comment]
> @KatiaSishost , I just made a little change on auth logic. Can you give it a try and share your results?

Hello Canove! whats up!?

im trying with a fresh instalation... and when try login or register... it only refresh the page and not create user and no login... i will try to new fresh instalation again.

**Comment by canove** [comment]
Do you mind sharing your chrome console when trying to create an account?

**Comment by KatiaSishost** [comment]
Well... i can login... i try it and tell how work. only error but work properly..:

websocket.js:124 WebSocket connection to 'wss://api.demodomain.com/socket.io/?EIO=3&transport=websocket&sid=ISddPjRzBboSxvySAAA6' failed: Error during WebSocket handshake: Unexpected response code: 400
d.doOpen @ websocket.js:124
i.open @ transport.js:84
f.probe @ socket.js:402
f.onOpen @ socket.js:423
f.onHandshake @ socket.js:484
f.onPacket @ socket.js:446
(anonymous) @ socket.js:278
r.emit @ index.js:145
i.onPacket @ transport.js:149
(anonymous) @ polling.js:144
t.decodePayload @ browser.js:417
f.onData @ polling.js:148
(anonymous) @ polling-xhr.js:129
r.emit @ index.js:145
c.onData @ polling-xhr.js:303
c.onLoad @ polling-xhr.js:370
hasXDR.t.onreadystatechange @ polling-xhr.js:256

**Comment by canove** [comment]
So, in the end it works? You are able to login, logout and create users?

**Comment by KatiaSishost** [comment]
> Entonces, ¿al final funciona? ¿Puede iniciar sesión, cerrar sesión y crear usuarios?

Yes... it work perfect.
