### ISSUE TITLE
ENVIO DE MIDEA NÃO FUNCIONA 

### ISSUE THREAD

**Issue by AndresJoseColina** [canove/whaticket#360]
Olá boa noite, eu já coloquei a solução na VPS tudo certinho, está funcionando quase tudo. somente o envio de mídia e áudios não funciona, sempre que tento enviar disse verifique a pagina conexões. tem alguma dica?

**Comment by rumeniquej** [comment]
Acredito ser essa a solução. 

https://github.com/canove/whaticket/pull/348

**Comment by Anderson201912** [comment]
![image](https://user-images.githubusercontent.com/85626023/151807967-771bcf0f-718c-40d1-b310-0c5467db90bf.png)
Solução do envio de medio não é #348 pois e quando build que está dando esse erro, justamente referente envio de imagen.

**Comment by AndresJoseColina** [comment]
funcionou, obrigado :)

**Comment by Clausruber** [comment]
Também tenho o mesmo problema, que solucao funcionou pessoal ?
