### ISSUE TITLE
An unexpected error occurred:

### ISSUE THREAD

**Issue by AndresJoseColina** [canove/whaticket#361]
Boa tarde, alguém poderia me ajudar?. não consigo acessar no painel e tampouco consigo instalar o certificado ssl

An unexpected error occurred:
AttributeError: module 'lib' has no attribute 'X509_get_notAfter'
Please see the logfiles in /var/log/letsencrypt for more details.

vou deixar a instancia ativa para verificarem:

**Comment by w3nder** [comment]
Boa tarde,

Você olhou no /var/log/letsencrypt para ver o os logs do problema?

**Comment by AndresJoseColina** [comment]
> Boa tarde,
> 
> Você olhou no /var/log/letsencrypt para ver o os logs do problema?

esta vazio

**Comment by w3nder** [comment]
Esse não é um problema no whaticket.

Qual sistema operacional está usando para fazer o deploy do whaticket?

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/152018648-a64dd70d-12cd-4692-b0e0-15c9b50667bf.png)

**Comment by AndresJoseColina** [comment]
ubuntu

**Comment by w3nder** [comment]
Tente executar os comando abaixo. 

`pip uninstall pyOpenSSL`
`pip install pyOpenSSL`

Eu gosto de seguir esse tutorial aqui para instalar o certificado. 
https://phoenixnap.com/kb/letsencrypt-nginx

**Comment by AndresJoseColina** [comment]
> Tente executar os comando abaixo.
> 
> `pip uninstall pyOpenSSL` `pip install pyOpenSSL`
> 
> Eu gosto de seguir esse tutorial aqui para instalar o certificado. https://phoenixnap.com/kb/letsencrypt-nginx

vou fazer isso
