### ISSUE TITLE
Duvida personalização frontend

### ISSUE THREAD

**Issue by TheuDeXter** [canove/whaticket#366]
Olá, colegas! gostaria de saber se é possível realizar algumas alterações no frontend.

Na coluna **1 vermelho** - Gostaria que ela iniciasse minimizada ao invés de iniciar maximizada como padrão.
Na coluna **2 em azul** - Diminuir um pouco width, deixando menos larga.
Na coluna **3 em amarelo** - Uma vez que a coluna 2 irá diminuir, consequentemente desejaria aumentar a coluna 3.
Na coluna **4 em roxo** - Coluna Dados do Contatos já iniciar aberta ao clicar no ticket.

- `Frontend Padrão ↓`

![d1](https://user-images.githubusercontent.com/63432628/152889863-d7e62f53-179f-4697-af5c-f30a6fdc0af7.png)

- `Frontend Desejado ↑`
Alguém poderia me dar uma direção de como fazer isso ? Desde já, agradeço
Abçs!

**Comment by lanaparadinha** [comment]
1) frontend/src/layout/index.js
alterar de true para false na linha 116 (deve ser essa)

const [menuOpen, setMenuOpen] = useState(true);
para 
const [menuOpen, setMenuOpen] = useState(false);
*** Buildar depois ***
2 e 3) você pode assistir o video do paulinho da nase que ensina a alterar o frontend, conforme:
https://www.youtube.com/watch?v=vqjMU6Bfd6Y

4) Essa eu tb não sei, mas acho que com a ajuda do video acima da uma ideia de como fazer isso...

**Comment by WesleyjanLacerda** [comment]
Referente: "Na coluna 1 vermelho - gostaria que ela iniciasse ao invés de iniciar maximizada como padrão."
  no arquivo: C:\Whaticket\frontend\src\layout\index.js
  Linha 122,
                    useEffect(() => {
                      if (document.body.offsetWidth > 600) {
                        setDrawerOpen(false);  // << vai está true, mude para false
                      }
                    }, []);

**Comment by joao-dio** [comment]
consegue fazer trocando o sinal > por <  antes do 600 , prox a linha 122 
no arquivo: C:\Whaticket\frontend\src\layout\index.js, porem no mobile abre inverso, mas resolvel


useEffect(() => {
    if (document.body.offsetWidth < 600) {
      setDrawerOpen(true);
    }
  }, []);

**Comment by Marcmanc** [comment]
Punto 2 y 3:  ampliar o reducir el ancho de la Columna Central (Tickets Manager) y la Columna Derecha (Chat)

archivo: frontend\src\pages\Tickets    dentro de return:
