### ISSUE TITLE
Personalização de Permissão

### ISSUE THREAD

**Issue by ram0ng1** [canove/whaticket#369]
Boa Tarde!

Estou precisando apenas ocultar a aba "Conexões" do perfil user, como prosseguir?

**Comment by jccalbuquerque** [comment]
Edite o arquivo MainListItems.js e mova o componente das conexões para "dentro" do componente "Can".
Esse seria o das conexões:
`<ListItemLink
              to="/connections"
              primary={i18n.t("mainDrawer.listItems.connections")}
              icon={
                <Badge badgeContent={connectionWarning ? "!" : 0} color="error">
                  <SyncAltIcon />
                </Badge>
              }
            />`
