### ISSUE TITLE
Docker run

### ISSUE THREAD

**Issue by KatiaSishost** [canove/whaticket#374]
i have problem to up with docker...

any can giveme a example for functional .env files?

for default... the front end is up with port 3000.... but it try to connect to back in 3000 too?

chrome console:
http://localhost:3000/api/auth/signup 404 (Not Found)

and notification: no se encontro ninguna configuracion con esta ID

**Comment by yamikarajput546** [comment]
hey, @KatiaSishost it's because in the backend Dockerfile 3000 port is exposed.
