### ISSUE TITLE
Sempre que a sessão do watsapp é desconectada pela segunda vez ocorre um bug que não deixa desconectar

### ISSUE THREAD

**Issue by AdrianoRobson** [canove/whaticket#375]
Esse bug não deixa desconectar. A única alternativa é derrubar a aplicação e executar novamente o backend com o npm start

![error](https://user-images.githubusercontent.com/40671414/153918916-335454f7-99c5-4053-8289-d5178f4d2908.jpg)

**Comment by jccalbuquerque** [comment]
Aparentemente seria erro/incompatibilidade da whatsapp-web.js na versão 1.15.6.
Na versão anterior não estava ocasionando esse erro.

**Comment by Davidiasdesousa** [comment]
Estou com o mesmo problema
