### ISSUE TITLE
Os tickets não são mostrados em resolvidos

### ISSUE THREAD

**Issue by Zedmerlol** [canove/whaticket#378]
Por algum motivo os tickets não aparecem, apenas a notificação para aceitar, os tickets resolvidos não aparecem na aba resolvidos, e a lista de linhas aparece vazia

![image](https://user-images.githubusercontent.com/54508766/154202380-8ec28a4c-cb88-49d4-a9dc-52ed2a63351f.png)

**Comment by Kouthk** [comment]
Opa, você precisa associar as filas ao seu usuario para que elas possam aparecer.
