### ISSUE TITLE
[Feature Suggestion] Outcome Webhooks

### ISSUE THREAD

**Issue by tatosjb** [canove/whaticket#38]
Create a background outcome webhooks for integration with other platforms.

When certain actions happens, it could call urls. On moments like:

1 - When a ticket was open.
2 - When a ticket was assigned.
3 - When a ticket was transferred.
4 - When a ticket was closed.
5 - When any message was enter(sent or received).
6 - When a message was received.
7 - When a message was sent.

So it could be integrated with many other sell platforms.

**Comment by canove** [comment]
duplicated of #17
