### ISSUE TITLE
File `package-lock.json` ignored

### ISSUE THREAD

**Issue by ricardoapaes** [canove/whaticket#380]
Tive vários problemas já com repos nodejs ou reactjs que não tem o ".lock" (package-json.lock ou yarn.lock) que as vezes é colocada no "package.json" uma lib, por exemplo: "^2.2.0", se uma atualização é lançada, por exemplo se faz npm install ele sempre vai puxar a última versão da lib, se já existir a 2.10.15, ela que seja instalada, que o "^" no inicio ali significa aquela versão ou semelhante (só não vai trocar a major, no caso para 3.0 por exemplo). Dai naquela versão mais recente ocorre um bug com meu repo, mas esse problema só vai dar na maquina que fez instalação por último, ou seja, nem todas as instalações terão as mesmas dependencias, ocorrendo bugs inesperados, etc.

Até tive esse problema com aqui quando tentei instalar com NodeJS 16 que simplesmente não funciona o backend, tem que ser na versão 14, pode ser por causa de alguma versão de lib ou algo parecido.

Vi pelo menos mais um [issue](https://github.com/canove/whaticket/issues/349) que isso poderia ter resolvido o problema.

**Comment by fogolin** [comment]
UP

Toda vez que temos atualização do WhatsApp Web JS há a necessidade de mexer nessa configuração, e se não houvesse essa trava, seria possível simplificar esse processo.
