### ISSUE TITLE
Origin has been blocked by CORS policy

### ISSUE THREAD

**Issue by spark-jesus** [canove/whaticket#382]
Hi! 
I have an error in login app.whaticket subdomain 

Access to XMLHttpRequest at 'https://apiwhaticket.subdomian.com/socket.io/?EIO=4&transport=polling&t=NyYx7lV' from origin 'https://appwhaticket.subdomain' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Can you help me?

**Comment by spark-jesus** [comment]
Sorry, I fix my own error, 
I didnt change the proxy pass in nginx conf
So that throw error by cors

**Comment by WALLYCE** [comment]
> 

poderia me ajudar, estou com mesmo erro

**Comment by IrgvBello** [comment]
yo tengo el mismo error en localhost  cuando intento entrar desde otra computadora

**Comment by ricardorohde** [comment]
alguem conseguiu resolver isso no windows / localhost ?
