### ISSUE TITLE
Ajuda para configurar portas

### ISSUE THREAD

**Issue by AndresJoseColina** [canove/whaticket#386]
Boa pessoal, instalei o whaticket recentemente rodei ele na porta 3000 no automatico sem certificado SSL. mas agora que instalei o cetificado e troquei as portas fica carregando o aplicativo mas não entra. poderiam me ajudar para configurar corretamente ? minha configuração atual. como tem que ficar os arquivos .env?

também 

sudo nano /etc/nginx/sites-available/whatcket-frontend

sudo nano /etc/nginx/sites-available/whaticket-backend

fico no aguardo

**Comment by ricardoapaes** [comment]
Quando abrir no chrome dá uma olhada na aba "console" que quando aqui aconteceu isso estava dando erro de cors.
Se for isso verifica a URL_FRONTEND no backend (ela não pode ter o "/" no final).

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/155435875-f08c611b-e23e-4e94-baff-09fc0b123017.png)

**Comment by AndresJoseColina** [comment]
com o certificado instalado como devem estar configurados os .env?

**Comment by ricardoapaes** [comment]
O frontend deve estar em um dominio diferente que o backend. Vi que está usando o mesmo para os dois.

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/155436685-1370d169-3a42-4314-a5e4-99408f771a61.png)

**Comment by ricardoapaes** [comment]
Agora está acontecendo o problema que citei no começo, erro de `cors`.

**Comment by AndresJoseColina** [comment]
> Agora está acontecendo o problema que citei no começo, erro de `cors`.

Como posso solucionar esse problema?

**Comment by ricardoapaes** [comment]
![image](https://user-images.githubusercontent.com/38794747/155438026-fb2faf4f-34e7-48ed-aaea-601377ea144e.png)

Agora parece que isso está resolvido, porém o certificado do api.* está errado, tem que gerar dois certificados, um para cada dominio, veja que abri aqui o dominio. api.* e o certificado é do app.*

**Comment by AndresJoseColina** [comment]
> certificado é do a

vou fazer isso

**Comment by AndresJoseColina** [comment]
quando vou instalar o certificado so me aparece a opção para criar para app.whatizap.com.br

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/155440542-535ef8ee-cdba-456b-a981-e9c22cc9e73c.png)

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/155440881-f3157baa-84ec-44c6-9c19-0e8276f7a9c7.png)

**Comment by ricardoapaes** [comment]
O primeiro comando que gera o certificado deu erro.

```bash
unknown option: --manual
```
Não sou um expert em certbot, mas pelo jeito essa opção não existe.

**Comment by ricardoapaes** [comment]
Como está sua configuração do nginx? Estão configurados para os dois dominios?

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/155444990-0177256e-d2d3-47df-a9f1-5f4eaf48878d.png)

**Comment by ricardoapaes** [comment]
Você chegou a executar esse comando aqui, ele está na propria documentação do whaticket.

```bash
sudo ln -s /etc/nginx/sites-available/whaticket-backend /etc/nginx/sites-enabled
```

Que pelo que vi o arquivo existe em `sites-available`, mas o nginx inclui os arquivos da pasta `sites-enabled`.

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/155531278-c8e6e184-263e-45e3-8776-9274f3f3bcde.png)

**Comment by AndresJoseColina** [comment]
inclui o arquivo na pasta so que agora o certbot esta dando erro

**Comment by w3nder** [comment]
> ![image](https://user-images.githubusercontent.com/89264434/155531278-c8e6e184-263e-45e3-8776-9274f3f3bcde.png)

![image](https://user-images.githubusercontent.com/1123103/155531418-585d9ff4-7650-45e9-bd15-d73bbe1171e0.png)
está faltando uma } no seu config.

**Comment by AndresJoseColina** [comment]
agora foi kkkkk muitisimo obrigado jajajja consegui rodar com o ssl agora

**Comment by AndresJoseColina** [comment]
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/155642746-3c27109a-f772-46be-998a-56fb38b2509d.png)

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/155643319-d41395bf-d327-4596-800e-902a69b5cd3f.png)

**Comment by AndresJoseColina** [comment]
a vps parou e teve que dar um stop i rodar depois com novo ip. deu em isso

**Comment by AndresJoseColina** [comment]
> a vps parou e teve que dar um stop i rodar depois com novo ip. deu em isso

sudo /etc/init.d/apache2 stop
sudo systemctl restart nginx

solução
