### ISSUE TITLE
Mensagem de alerta sobre filas

### ISSUE THREAD

**Issue by lukasabino** [canove/whaticket#390]
Ao entrar uma nova mensagem, caso o solicitante não mandar o numero da fila de forma correta, mandar uma mensagem de alerta, como: "Favor selecionar uma das filas acima", pois caso o cliente mande muitas mensagem sem responder o BOT, fica muito mais poluída a visualização por conta da mensagem de saudação poder ser grande.

Exemplo:
![image](https://user-images.githubusercontent.com/70410692/155539402-31c4dfce-c02c-422a-9205-427acabfdd65.png)

**Comment by rtenorioh** [comment]
Essa função ajudaria muito mesmo...

Pois se o cliente fica mandando mensagem sem nenhum retorno acaba prejudicando o atendimento.

**Comment by rumeniquej** [comment]
É difícil mesmo, principalmente no início de uso do whaticket o cliente selecionar o número da opção. Mas com o passar do tempo isso melhora. Eu deixo isso escrito na msg de saudação e despedida. 
![Screenshot_20220312-065215_WhatsApp](https://user-images.githubusercontent.com/17551375/158013300-1bc28154-234d-42bd-aa11-0548cf1ba179.jpg)

**Comment by caeteweb** [comment]
Deve ter uma forma de somente mandar a fila depois de XX horas!
Cliente manda OI
Depois Manda Bom dia

Aí vai a fila 2X!
