### ISSUE TITLE
PROBLEMA COM CODIGO QR 

### ISSUE THREAD

**Issue by AndresJoseColina** [canove/whaticket#393]
![image](https://user-images.githubusercontent.com/89264434/155858978-d3d7ad4e-1fee-4698-8047-83c7532f42ca.png)

**Comment by AndresJoseColina** [comment]
> Amigo, estou com o mesmo problema. Conseguiu resolver?

consegui sim

Solução 
cd backend
npm update whatsapp-web.js

**Comment by fernandodenardin** [comment]
Resolvi com os passos abaixo:
- remover pasta backend/node_modules
- remover o arquivo backend/package-lock.json
- npm update whatsapp-web.js
- npm install
- npm run build
