### ISSUE TITLE
Error: Evaluation failed: Error: Comms::sendIq called before startComms

### ISSUE THREAD

**Issue by WALLYCE** [canove/whaticket#395]
I get the same error whenever I send or receive a message, nothing appears on the notification front end for me ERROR: Error handling whatsapp message: Err: Error: Evaluation failed: Error: Comms::sendIq called before startComms

**Comment by jonaskirch** [comment]
Same error here

**Comment by xmariodiaz** [comment]
same

**Comment by jonaskirch** [comment]
The error is whatsapp-web.js library, in client.getProfilePicUrl function.

Whaticket use this in verifyContact function of backend/src/services/WbotServices/wbotMessageListener.ts.

PR:
https://github.com/pedroslopez/whatsapp-web.js/pull/1264

So, wait merge or fixed manually.

**Comment by WALLYCE** [comment]
> The error is whatsapp-web.js library, in client.getProfilePicUrl function.
> 
> Whaticket use this in verifyContact function of backend/src/services/WbotServices/wbotMessageListener.ts.
> 
> PR: [pedroslopez/whatsapp-web.js#1264](https://github.com/pedroslopez/whatsapp-web.js/pull/1264)
> 
> So, wait merge or fixed manually.

how do i do it? I was not able to

**Comment by filipesr** [comment]
> > The error is whatsapp-web.js library, in client.getProfilePicUrl function.
> > Whaticket use this in verifyContact function of backend/src/services/WbotServices/wbotMessageListener.ts.
> > PR: [pedroslopez/whatsapp-web.js#1264](https://github.com/pedroslopez/whatsapp-web.js/pull/1264)
> > So, wait merge or fixed manually.
> 
> how do i do it? I was not able to

nops... didnt functioned to me... any other approuch?

**Comment by xmariodiaz** [comment]
> The error is whatsapp-web.js library, in client.getProfilePicUrl function.
> 
> Whaticket use this in verifyContact function of backend/src/services/WbotServices/wbotMessageListener.ts.
> 
> PR: [pedroslopez/whatsapp-web.js#1264](https://github.com/pedroslopez/whatsapp-web.js/pull/1264)
> 
> So, wait merge or fixed manually.

I updated the dependencies and it didn't work
