### ISSUE TITLE
Mensagens não aparecem

### ISSUE THREAD

**Issue by LinkyS1** [canove/whaticket#396]
![image](https://user-images.githubusercontent.com/98433279/156078970-2c54017c-5f92-4300-b415-7b47320eb3ab.png)

Alguem pode me ajudar com isso?

Ao mandar mensagem aparece o seguinte erro no Backend:

![image](https://user-images.githubusercontent.com/98433279/156079132-ba85f3b9-aeba-44cc-a37e-6a53d9b55173.png)

**Comment by lanaparadinha** [comment]
Estou com o mesmo problema.
Sabe me dizer se o seu celular saiu da versão Beta?

**Comment by LinkyS1** [comment]
a versão do whatsapp vc diz, se for, acho que não é beta não, porem é s versão Business.

> Estou com o mesmo problema. Sabe me dizer se o seu celular saiu da versão Beta?

a versão do whatsapp vc diz, se for, acho que não é beta não, porem é versão Business.

**Comment by lanaparadinha** [comment]
Aqui tb é a versão busines... 
Tbm não é o beta, mas já é multidevices.

**Comment by joaojkuligowskii** [comment]
Aqui ocorreu o mesmo, não está na MD, fiz a atualização, conecta e envia as mensagens, mas não aparece no frontend as conversas.

**Comment by glauco-oliveira** [comment]
Estou com o mesmo problema! Estou tentando identificar o motivo...

**Comment by fernandodenardin** [comment]
Estou com o mesmo problema aqui.

**Comment by w3nder** [comment]
Para resolver esse problema temporariamente até a lib atualizar, 
https://github.com/pedroslopez/whatsapp-web.js/pull/1264/files

editando lá no node_modules
na pasta do whatsapp-web.js

e depois rodando o npm run build novamente.

**Comment by glauco-oliveira** [comment]
**Quem quiser resolver manualmente, basta apenas seguir os passos abaixo:**

1. Acessar o arquivo **/node_modules/whatsapp-web.js/src/Client.js** dentro do backend
2. Na linha 878 você verá o script abaixo:
`async getProfilePicUrl(contactId) {
        const profilePic = await this.pupPage.evaluate((contactId) => {
            const chatWid = window.Store.WidFactory.createWid(contactId);
            return window.Store.getProfilePicFull(chatWid);
        }, contactId)`
3. Substitua pelo script abaixo:
`const profilePic = await this.pupPage.evaluate(async contactId => {
            let asyncPic;
            if (window.Store.Features.features.MD_BACKEND) {
                const chatWid = window.Store.WidFactory.createWid(contactId);
                asyncPic = await window.Store.getProfilePicFull(chatWid).catch(() => {
                    return undefined;
                });
            } else {
                asyncPic = await window.Store.Wap.profilePicFind(contactId).catch(() => {
                    return undefined;
                });
            }
            return asyncPic;`
4. E por fim rode o comando **npm run build** dentro do backend

Realizando esse passo a passo o problema estará resolvido!!

**Comment by lanaparadinha** [comment]
2022-03-03T17:21:26: /www/wwwroot/whaticket/backend/node_modules/whatsapp-web.js/src/Client.js:878
2022-03-03T17:21:26: const profilePic = await
2022-03-03T17:21:26:       ^^^^^^^^^^

**Comment by w3nder** [comment]
Só seguir a pull, não tem erro, tiver com duvida, copia o arquivo inteiro é faz a troca....

só seguir galera.

**Comment by lanaparadinha** [comment]
> a o arquivo inteiro é faz a troca....

Gostaria que fosse fácil assim. Mas simplesmente o problema é sempre o mesmo.

**Comment by joaojkuligowskii** [comment]
> 

Perfeito!! 1000%

**Comment by joaojkuligowskii** [comment]
> **Quem quiser resolver manualmente, basta apenas seguir os passos abaixo:**
> 
> 1. Acessar o arquivo **/node_modules/whatsapp-web.js/src/Client.js** dentro do backend
> 2. Na linha 878 você verá o script abaixo:
>    `async getProfilePicUrl(contactId) { const profilePic = await this.pupPage.evaluate((contactId) => { const chatWid = window.Store.WidFactory.createWid(contactId); return window.Store.getProfilePicFull(chatWid); }, contactId)`
> 3. Substitua pelo script abaixo:
>    `const profilePic = await this.pupPage.evaluate(async contactId => { let asyncPic; if (window.Store.Features.features.MD_BACKEND) { const chatWid = window.Store.WidFactory.createWid(contactId); asyncPic = await window.Store.getProfilePicFull(chatWid).catch(() => { return undefined; }); } else { asyncPic = await window.Store.Wap.profilePicFind(contactId).catch(() => { return undefined; }); } return asyncPic;`
> 4. Depois rode o comando **npm run build** dentro do backend
> 5. E por fim rode o comando **pm2 restart whaticket-backend**
> 
> Realizando esse passo a passo o problema estará resolvido!!

Perfeito, 1000%

**Comment by LinkyS1** [comment]
Galera aqui funcionou, obrigado a todos!!! Valeu mesmo!
