### ISSUE TITLE
Não aparece nada no Painel

### ISSUE THREAD

**Issue by thiagoaraujo007** [canove/whaticket#397]
![image](https://user-images.githubusercontent.com/92159572/156233370-b9d52d4e-a2d4-48ac-8839-115ba0975dcf.png)

Fiz a Instalação corretamente, porém não chega nada quando recebe mensagem!

**Comment by Kouthk** [comment]
Olá, é nescessario que vincule o usuario as filas criadas, para que elas apareçam para ele.
