### ISSUE TITLE
WhatsApp Beta! 

### ISSUE THREAD

**Issue by AndresJoseColina** [canove/whaticket#399]
Alguém consigui a aplicação reconhecer no QR no WhatsApp Beta funcional?

**Comment by rodrigofsantos** [comment]
Lembre-se que para renovar uma sessão agora e preciso remover a pasta .www que fica dentro de backend\ !!!

**Comment by AndresJoseColina** [comment]
> 

muito obrigado rodrigo, so não achei essa pasta .www no backend

**Comment by AndresJoseColina** [comment]
![image](https://user-images.githubusercontent.com/89264434/156409157-f19f12eb-0c07-4bab-9556-78bf0ae282df.png)

**Comment by AndresJoseColina** [comment]
> Lembre-se que para renovar uma sessão agora e preciso remover a pasta .www que fica dentro de backend\ !!!

aguardo. grato!

**Comment by AndresJoseColina** [comment]
eu consegui aqui já, mas tem um problema, não estão chegando todas as mensagens. algumas mensagens não são recebidas pelo aplicativo.

**Comment by AndresJoseColina** [comment]
funciona parcialmente, não precisa do tlf conectado etc. porem nem todas as mensagens são recebidas, tem ideia do que poderia ser?

**Comment by AndresJoseColina** [comment]
![WhatsApp Image 2022-03-02 at 15 38 30](https://user-images.githubusercontent.com/89264434/156426753-46d50c9e-b712-4833-95e6-61746342f7cd.jpeg)

**Comment by rodrigofsantos** [comment]
olha aqui tive esse problema mas foi quando eu usei a minha versão, apos eu baixar do zero e fazer nova instalação mas usando o mesmo banco de dados resolveu 
!!

**Comment by rodrigofsantos** [comment]
usa essa versão :

https://github.com/ricardoapaes/whaticket/

**Comment by AndresJoseColina** [comment]
resolvido
