### ISSUE TITLE
[Help] Error sending emoticon and login

### ISSUE THREAD

**Issue by Max2287** [canove/whaticket#40]
Hello guys!
Did any of you guys have these errors while using whaticket and can you help me?

When wanting to send an emoticon, a page connection error message appears. But the emoticon is still sent to the recipient.
![image](https://user-images.githubusercontent.com/22262813/95590486-7e582500-0a1c-11eb-92a2-7db76e2284d8.png)

When the user tries to log in for the first time, an invalid session error appears as shown in the image. But if you try a second time, you will be logged in normally.
![image](https://user-images.githubusercontent.com/22262813/95589485-2e2c9300-0a1b-11eb-9d9f-3fad0259bd79.png)

Thank you very much!

**Comment by canove** [comment]
Hi @Max2287 , welcome, and thanks for testing Whaticket.

About login errors:
The session handler part of Whaticket is not doe yet. I'm still figuring out a way to make it a bit more secured than just using access token on localStorage, while keeping user logged in for long period. 

My last try was to add a httpOnly cookie to refresh access token, but it not working so well. It's a work in progress.

I think the emoji problem is related. Today I noticed that I can't send some medias, and some of then throws this error too.

**Comment by canove** [comment]
Hi @Max2287. I've made some improvement on session handler on recent commits. Since I'm not facing this errors anymore, I'm closing this issue.

If you need further help, let me now.
