### ISSUE TITLE
Erro ao atualizar o whatsapp-web.js para a 1.6.1 

### ISSUE THREAD

**Issue by joaojkuligowskii** [canove/whaticket#400]
Boa tarde, com a chegada do MD fiz a atualização com sucesso para a versão 1.6.1 do whatsapp-web.js. Está funcionando perfeitamente, exceto quando crio um ticket com um número que não está na minha lista de conversas do Whatsapp, retorna este erro:

![image](https://user-images.githubusercontent.com/99497011/156449964-bc4b1b99-2a88-43b5-beb4-1a22c51f87ac.png)

Alguma luz de como resolver a questão?

**Comment by w3nder** [comment]
A lib [whatsapp-web.js](https://wwebjs.dev/)
está com uma atualização pendente que corrigi o problema da imagem do perfil do contato.

como ela está com problema, faz o whaticket retornar o erro,
você pode olhar aqui, ou até mesmo atualizar de forma manual.. 

https://github.com/pedroslopez/whatsapp-web.js/pull/1264
