### ISSUE TITLE
Whaticket parou de funcionar não autentica QR code com nova versão WB.

### ISSUE THREAD

**Issue by PauloBettin** [canove/whaticket#403]
Apresenta este erro:

Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts ao tentar o QR code via console.

Depois da mensagem o backend da crash.

**Comment by LinkyS1** [comment]
Igual aqui

**Comment by lanaparadinha** [comment]
Paulo, existem muitos tópicos pra baixo sobre isso.
Se não me engano o issue 401 é o mais acertivo.

Mas pra te deixar feliz mesmo de verdade, nem mesmo o whats esta 100% funcional.
Em algumas versões nem mesmo essa issue funciona.. em outra sim.

**Comment by PauloBettin** [comment]
Issue 401 não retrata os mesmos erros, aqui o problema é na autenticação de um dos números, o qual o WB está com uma versão diferente que não permite ativar o MultiDevice, ao que parece ja fica ativo direto. Segue o erro:

**Comment by PauloBettin** [comment]
LegacySessionAuth.js:57
        if(isMD) throw new Error('Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.');

**Comment by crvroberto** [comment]
Desinstala esse o app WB que está com a Md ativa, e instala novamente

**Comment by lanaparadinha** [comment]
> 

Td é o mesmo problema Paulo! td é referente ao MD.

**Comment by PauloBettin** [comment]
Vou tentar, mas ele não está ativo, não foi ativo, nem sequer aparece opção de ativar e inativar isso que estou querendo dizer.

**Comment by sidneylopes** [comment]
Estou com o mesmo problema. Qual versão do whatsapp-web.js está usando?

**Comment by PauloBettin** [comment]
Estava com uma versão mais antiga, umas das 1.15 quando parou a 3 dias, ai tentei atualizar para a última a 1.16.2, mas também não funciona.

**Comment by lucasdsb1** [comment]
Agora no WWebJS é necessário configurar a estratégia de autenticação por causa do multidevice. Mesmo que o seu número não seja MD, ainda sim é necessário configurar a estratégia de autenticação. No meu caso, eu fiz o seguinte:

backend > src > libs > wbot.ts > function initWbot

```
const wbot: Session = new Client({
         //Adicionei essa linha, utilizei a método LocalAuth que cria uma pasta local. Mas existem outros métodos.
         authStrategy: new LocalAuth({clientId: `bd_${whatsapp.id}`}),
         
         //session: sessionCfg,
         puppeteer: {
                 executablePath: process.env.CHROME_BIN || undefined,
                 // @ts-ignore
                 browserWSEndpoint: process.env.CHROME_WS || undefined,
                 args: args.split(' ')
         }
});
```

Isso fará com que ele crie uma pasta chamada .wwebjs_auth dentro do projeto.
Mais informações: https://wwebjs.dev/guide/authentication.html

**Comment by postgres99** [comment]
> 

Aqui fiz a mesma coisa, autentica mas apresenta o erro abaixo tanto no envio como no recebimento de mensagens.

ERROR: Error handling whatsapp message: Err: Error: Evaluation failed: i

**Comment by lucasdsb1** [comment]
> > 
> 
> Aqui fiz a mesma coisa, autentica mas apresenta o erro abaixo tanto no envio como no recebimento de mensagens.
> 
> ERROR: Error handling whatsapp message: Err: Error: Evaluation failed: i

Atualiza para o whatsapp-web.js 1.16.3, ele corrige um problema de não enviar mensagens devido a imagem do perfil do usuário

**Comment by postgres99** [comment]
> > > 
> > 
> > 
> > Aqui fiz a mesma coisa, autentica mas apresenta o erro abaixo tanto no envio como no recebimento de mensagens.
> > ERROR: Error handling whatsapp message: Err: Error: Evaluation failed: i
> 
> Atualiza para o whatsapp-web.js 1.16.3, ele corrige um problema de não enviar mensagens devido a imagem do perfil do usuário

Muito obrigado Lucas, deu tudo certo.
Abs

**Comment by CodePrince29** [comment]
Eu recebo o seguinte erro ao escrever seu script no arquivo ts
[1647205160143] ERROR: args is not defined
    ReferenceError: args is not defined
        at C:\Users\Israel Aguirre\3D Objects\okredito-crm\backend\dist\libs\wbot.js:55:27
        at new Promise (<anonymous>)
        at C:\Users\Israel Aguirre\3D Objects\okredito-crm\backend\dist\libs\wbot.js:40:12
        at Generator.next (<anonymous>)
        at C:\Users\Israel Aguirre\3D Objects\okredito-crm\backend\dist\libs\wbot.js:8:71
        at new Promise (<anonymous>)
        at __awaiter (C:\Users\Israel Aguirre\3D Objects\okredito-crm\backend\dist\libs\wbot.js:4:12)
        at Object.exports.initWbot (C:\Users\Israel Aguirre\3D Objects\okredito-crm\backend\dist\libs\wbot.js:39:34)
        at C:\Users\Israel Aguirre\3D Objects\okredito-crm\backend\dist\services\WbotServices\StartWhatsAppSession.js:29:35
        at Generator.next (<anonymous>)
        at fulfilled (C:\Users\Israel Aguirre\3D Objects\okredito-crm\backend\dist\services\WbotServices\StartWhatsAppSession.js:5:58)

**Comment by Jmallone** [comment]
> Agora no WWebJS é necessário configurar a estratégia de autenticação por causa do multidevice. Mesmo que o seu número não seja MD, ainda sim é necessário configurar a estratégia de autenticação. No meu caso, eu fiz o seguinte:
> 
> backend > src > libs > wbot.ts > function initWbot
> 
> ```
> const wbot: Session = new Client({
>          //Adicionei essa linha, utilizei a método LocalAuth que cria uma pasta local. Mas existem outros métodos.
>          authStrategy: new LocalAuth({clientId: `bd_${whatsapp.id}`}),
>          
>          //session: sessionCfg,
>          puppeteer: {
>                  executablePath: process.env.CHROME_BIN || undefined,
>                  // @ts-ignore
>                  browserWSEndpoint: process.env.CHROME_WS || undefined,
>                  args: args.split(' ')
>          }
> });
> ```
> 
> LEMBRANDO QUE é necessário estar com a versão 1.16.1 ou superior do WWebJS Isso fará com que ele crie uma pasta chamada .wwebjs_auth dentro do projeto. Mais informações: https://wwebjs.dev/guide/authentication.html

Deu certo :)

**Comment by maickon10** [comment]
> 

Como fez, pode ajudar?

**Comment by rumeniquej** [comment]
> 

Qual versão do whatsapp-web.js vc está usando?

**Comment by rumeniquej** [comment]
Eu atualizei assim (última versão é a 1.16.5)
npm i whatsapp-web.js
npm run build
pm2 restart all

**Comment by maickon10** [comment]
> Eu atualizei assim (última versão é a 1.16.5)
> npm i whatsapp-web.js
> npm run build
> pm2 restart all

Fiz assim para atualizar, porém nada, tentei atualizar o site todo aí deu ruim kk

**Comment by rumeniquej** [comment]
Kkkkk, aí lascou.
Manda fotos aí dos erros. Sua instalação é nova? Ou já estava funcionando?

**Comment by maickon10** [comment]
Instalação é nova, a aplicação está rodando aqui:
app.plugar.tech

**Comment by rumeniquej** [comment]
A aplicação subiu e funcionou? E deu problema após atualizar o WhatsAppweb.js? Ou nem funcionou?

**Comment by maickon10** [comment]
Rodou mas não funcionava a leitura do QR code, atualizei oi whatsappweb.js e nada também, então atualizei a aplicação por inteira, aí não subiu mais.

**Comment by rumeniquej** [comment]
Quais erros aparecem no log?

**Comment by maickon10** [comment]
Reinstalei o sistema, agora ele não loga, entra na tela de login porém ficando rodando e não loga.
