### ISSUE TITLE
Puppeteer problema ao ler o qrcode e manter a sessão quando lido

### ISSUE THREAD

**Issue by AdrianoRobson** [canove/whaticket#404]
Não é possível ler qrcode ou quando lê o qrcode, a sessão não é mantida após para a aplicação backend e executar novamente. 
Mostra o seguinte erro quando tento ler o qrcode:
![Screenshot from 2022-03-09 08-56-27](https://user-images.githubusercontent.com/40671414/157441998-48072a82-5a5b-412d-b054-ded5fc8158c2.png)

**Comment by ricardoapaes** [comment]
Parece que tem relação com essa issue aqui:

https://github.com/pedroslopez/whatsapp-web.js/issues/1305

**Comment by lucasdsb1** [comment]
Já existe um pré-patch de correção no WWebJS, atualiza para a v1.16.4-alpha0

https://github.com/pedroslopez/whatsapp-web.js/commit/2718c1328c636d0acecd8cc2910592a693e899b6
