### ISSUE TITLE
error need help

### ISSUE THREAD

**Issue by swalayan-hasbuna** [canove/whaticket#405]
![image](https://user-images.githubusercontent.com/74512439/157518503-be57a446-c0df-499e-8861-7ab88fbba196.png)

**Comment by swalayan-hasbuna** [comment]
![image](https://user-images.githubusercontent.com/74512439/157520475-11a82cfe-38f7-49ab-8c54-bb49d6df1f5e.png)

**Comment by CristianoDNBX** [comment]
É só atualizar o whatsapp-web.js para a versão 1.16.4
roda o comando:
`npm install whatsapp-web.js@1.16.4`
depois faz o build e é só correr para o abraço.

**Comment by CristianoDNBX** [comment]
Don't you have tried update whatsapp-web.js to 1.16.4?
just run this command 
`npm install whatsapp-web.js@1.16.4`
after update just rebuild the backend Et voilà!
