### ISSUE TITLE
Ler QR Mas nao libera acesso 

### ISSUE THREAD

**Issue by athila755** [canove/whaticket#411]
(node: 1413) UnhandledPromiseRejectionkarning: Error: Authenticating via JSON session is not supported for MultiDevice-enabled Wh
atsApp accounts.

at LegacySessionAuth.getAuthEventPayload (/home/whats/uhat icket/backend/node_modules/uhatsapp-web. js/src/authStrategies/Lega
cySessionfuth. js:57:24)

at runMicrotasks (<anonymaus>)

at processTicksAndRejections (internal/pracess/task_queues. js )

at async Client. initialize (/home/uhats/uhat icket/backend/node_modules/whatsapp-web. js/src/Client . js:217:34)
(node: 1413) UnhandledPromiseReject ionWarning: Unhandled promise rejection. This error originated either by throwing inside of an
async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node prac
ess on unhandled promise rejection, use the CLI flag ‘--unhandled-rejections=strict’ (see https://nodejs.org/api/cli.html#cli_un
handled_rejections_mode). (rejection id: 1)
(node:1413) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that ar
e not handled will terminate the Node. js process with a non-zero exit cade.

**Comment by LinkyS1** [comment]
Mesmo ocorreu aqui.

**Comment by diazzaid** [comment]
try changing wbot.ts and package.json for multi device support
wbot.ts and package.json
https://github.com/diazzaid/whaticket-1/blob/master/backend/src/libs/wbot.ts
https://github.com/diazzaid/whaticket-1/blob/master/backend/package.json
npm run build
and ignore if there is an error message
npm start

**Comment by LinkyS1** [comment]
Fiz os procedimentos porem problema persiste!

**Comment by JorgeCruzato** [comment]
Pelo Jeiro modo Beta virou definitivo para whatsapp, creio q a biblioteca whatsapp-web.js n suporta multi-devices

**Comment by Lu4nrc** [comment]
tentar desativar a opção de multi-devices no whatsapp app. estava ocorrendo o mesmo erro para mim.
