### ISSUE TITLE
Client disconnected

### ISSUE THREAD

**Issue by armandoboza** [canove/whaticket#412]
Ao clicar para "aceitar" algum ticket o sistema tenta abrir a página do mesmo mas fica em branco e aparece "Client disconnected" no backend, pressionando F5 pra recarregar a página abre normal.

![image](https://user-images.githubusercontent.com/7945361/159125639-ff51736b-534f-43d1-b60e-cc51d53542bc.png)

O mesmo acontece quando estou na página de tickets e recebo nova mensagem, simplesmente fica em branco a página forçando eu pressionar F5.

Será que existe alguma configuração que estou esquecendo de fazer?

**Comment by luangomestm** [comment]
Acredito que não, estou com o mesmo problema.

**Comment by lidernetworktecnologia** [comment]
Aqui mesma coisa...

**Comment by luanscar** [comment]
tbm estou com esse prblema

**Comment by armandoboza** [comment]
> Opa Amigo. Consegui Resolver Aqui.
> 
> Na Pasta /whaticket/frontend/src/components/TicketListItem
> 
> Edite o arquivo index.js
> 
> Na Linha 215 deixe assim:
> 
> ```
> <div className={classes.userTag} title={i18n.t("ticketsList.connectionTitle")}>{ticket.whatsapp?.name}</div>
> ```
> 
> Não entendo muito de react, mas resolveu o problema da tela branca.

Se for isso mesmo seria interessante o @canove  dar uma olhada, afinal o código é dele kkkkkk

**Comment by w3nder** [comment]
> > Opa Amigo. Consegui Resolver Aqui.
> > Na Pasta /whaticket/frontend/src/components/TicketListItem
> > Edite o arquivo index.js
> > Na Linha 215 deixe assim:
> > ```
> > <div className={classes.userTag} title={i18n.t("ticketsList.connectionTitle")}>{ticket.whatsapp?.name}</div>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Não entendo muito de react, mas resolveu o problema da tela branca.
> 
> Se for isso mesmo seria interessante o @canove dar uma olhada, afinal o código é dele kkkkkk

É um projeto open source, você ou qualquer outro, é livre para contribuir. 
Se você encontrou um problema é conseguiu resolver, por que não contribuir?

**Comment by armandoboza** [comment]
> É um projeto open source, você ou qualquer outro, é livre para contribuir. Se você encontrou um problema é conseguiu resolver, por que não contribuir?

Desculpe, não programo em react, por isso comentei sobre o ajuste, mas se pareceu ofensivo esse Issue queira por gentileza desconsiderá-lo.

**Comment by lidernetworktecnologia** [comment]
Obrigado @MatheusMani aqui resolvido com sua solução!
