### ISSUE TITLE
Tela Branca ao Responder Ticket

### ISSUE THREAD

**Issue by MatheusMani** [canove/whaticket#413]
Esta funcionando normalmente o whaticket, porem quando foi responder um ticket a tela toda fica branca.

Alguem poderia ajudar?
Estou usando o whaticket na vps da aws (meddium)

**Comment by armandoboza** [comment]
É o mesmo problema do Issue que abri anterior ao seu: https://github.com/canove/whaticket/issues/412

**Comment by MatheusMani** [comment]
Caraca, nem percebi :), achei que era eu que estava fazendo algo errado, re instalei umas 5 vezes ontem o whaticket e nada.
