### ISSUE TITLE
DOCKER RUN --NAME...

### ISSUE THREAD

**Issue by srgoogle23** [canove/whaticket#42]
![image](https://user-images.githubusercontent.com/62403037/95897147-6d344e80-0d63-11eb-8048-911ad9b30392.png)

I can't create a database on the docker, how do I proceed?

**Comment by canove** [comment]
Hi @srgoogle23, it looks like its trying to create a container based on a image called "whaticket". Maybe it's some line break bug when you copy the code from tutorial.

Try copying it to a notepad first, remove all line breaks and copy again to your terminal.
