### ISSUE TITLE
Whatsapp QRCode is not working

### ISSUE THREAD

**Issue by djogjanetwork** [canove/whaticket#423]
Hello, 

Suddenly all of my whaticket server loss connection to whatsapp web.

Now, After I scan the barcode it won't connected to whatsapp again. Any idea?

**Comment by rumeniquej** [comment]
Olá
1- Pare o serviço e reinicie novamente para ver se volta novamente. 

2- Tenta excluir a conexão e criar uma nova conexão com outro nome.

3- Verifique se o WhatsAppweb.js está atualizado.

**Comment by AdrianoRobson** [comment]
> Hello,
> 
> Suddenly all of my whaticket server loss connection to whatsapp web.
> 
> Now, After I scan the barcode it won't connected to whatsapp again. Any idea?

Whatsapp is upgrading from multidevice beta version to multidevice standard version so you need to change wbot.ts connection strategy from session.js to localAuth strategy

Like this bro:
https://github.com/w3nder/whaticket

**Comment by djogjanetwork** [comment]
The problem still exist please update the script, thanks..
