### ISSUE TITLE
 Erro ao RESPONDER a GRUPOS

### ISSUE THREAD

**Issue by hadsonmartins** [canove/whaticket#424]
Ao responder a qualquer grupo eu recebo esse erro,

![erro-responder-grupos](https://user-images.githubusercontent.com/64390960/164022767-39e931b7-ea4e-418f-a2d3-6f407a9f5ebf.jpg)

**Comment by jailtonurbano** [comment]
Bom dia.
Estou com esse mesmo bug.
Já foi resolvido?

**Comment by lucasvieirawerner** [comment]
any update?
