### ISSUE TITLE
Frontend Nao inicia com PM2 

### ISSUE THREAD

**Issue by lRafaelOliveira** [canove/whaticket#425]
Boa tarde Pessoal, alguem consegue me ajudar ? 

Estou executando o projeto e ele esta funcionando perfeitamente. Porem, quando tento iniciar com pm2 o frontend nao inicia.. 

o backend Inicia Normal, se eu iniciar o frontend com npm start a aplicacao funciona normal, porem, se tento iniciar o frontend com pm2 start frontend-whaticket nao inicia..

com pm2 list ele mostra que frontend-whaticket esta online, porem quando tento acessar localhost:3000 nao entra...  e nao salva nada em logs.. 
![image](https://user-images.githubusercontent.com/63177618/164312422-338bc49c-edad-4a78-a3be-b846c44a9aa3.png)

**Comment by lRafaelOliveira** [comment]
se eu Uso o pm2 monit, para monitorar a aplicação, ele me mostra que o frontend esta sim online. 

![image](https://user-images.githubusercontent.com/63177618/164312908-67e3a0d0-9e99-4916-971c-1238e8e96ba2.png)

**Comment by Gedehamsen021** [comment]
conseguiu algum resultado?

**Comment by OtavioSR** [comment]
Conseguiu resolver esse erro @lRafaelOliveira ? passando pelo mesmo problema, inclusive com o Forever.

**Comment by jbastos62** [comment]
same isuue, did u solve it ?
