### ISSUE TITLE
Error registering first user and login / Erro ao cadastrar primeiro usuario e login

### ISSUE THREAD

**Issue by hahndouglasf** [canove/whaticket#428]
Hello, I performed the installation in development without docker, but in a container through ProxmoxVE.
An error is occurring when trying to register a user, when clicking on the registration button, no action occurs..
And when trying to log in with a non-registered user, it does not return any error, it is in a processing loop as shown in the image..
Please, I would like some help to resolve these errors and be able to test in this build mode!

Ola, realizei a instalacao em desenvolvimento sem o docker, mas em um conteiner atraves do ProxmoxVE.
Esta ocorrendo erro ao tentar cadstrar usuario, ao clicar no botao de cadstro nao acontece nenhuma acao..
E ao tentar logar com usuario nao cadstrado nao retorna nenhum erro, fica em loop de processamento conforme a imagem..
Por favor, gostaria de um auxilio para resolvers estes erros e poder testar neste modo de contrucao!

![erro_cadastro](https://user-images.githubusercontent.com/91286300/166182618-c98f8762-9ebd-4dd6-8f7c-6758772d2dd5.JPG)
![erro_login](https://user-images.githubusercontent.com/91286300/166182633-c88378be-461e-439e-a516-ebf4129d9c99.JPG)

**Comment by bragaelmo** [comment]
Não esta obtendo a resposta do backend. verifque se o arquvio .env ta correto

**Comment by hahndouglasf** [comment]
Este é meu .env

![image](https://user-images.githubusercontent.com/91286300/169551762-2b6c81c6-4b45-49c7-bf69-e237f42f1d5f.png)

**Comment by Kouthk** [comment]
Qual o .env do seu front-end?

**Comment by nodestark** [comment]
Eu tive o mesmo erro, resolvi executando "npm start" no lugar de "serve -s build".

Espero que te ajude.

**Comment by izaias-nascimento** [comment]
> Este é meu .env
> 
> ![image](https://user-images.githubusercontent.com/91286300/169551762-2b6c81c6-4b45-49c7-bf69-e237f42f1d5f.png)

@hahndouglasf Se ainda não resolveu segue uma dica.

Se usou o guia de instalação do mysql no docker contido no REDME a senha do banco (DB_PASS) whaticket e não strongpassword, a senha strongpassword é do root.

**Comment by SilasAlvesJunior** [comment]
I don't know if it make sense, but .env environment variables aren't load when you build and run npm start or npm run dev:server.
 I just tried to pass absolutely .env path but is doesn't work.

Anyone have an ideia?!
