### ISSUE TITLE
[Error] Sequelize CLI

### ISSUE THREAD

**Issue by alvares** [canove/whaticket#43]
Hi.
When I tried to enter the command  `npx sequelize db:migrate` the error appeared, do you know hot to solve it?
```
~/whaticket/backend$ npx sequelize db:migrate

Sequelize CLI [Node: 12.19.0, CLI: 5.5.1, ORM: 5.22.3]

Loaded configuration file "dist/config/database.js".

ERROR: Dialect needs to be explicitly supplied as of v4.0.0
```

**Comment by srgoogle23** [comment]
Dialect needs to be explicitly supplied as of v4.0.0
![image](https://user-images.githubusercontent.com/62403037/96038944-4a2a9d00-0e3e-11eb-916f-2bcdf9a28878.png)


put the dialet right here, like, sql, mongodb or mysql

**Comment by canove** [comment]
@alvares , @srgoogle23 solution works for you? 
Remember to build backend again after changes.

**Comment by srgoogle23** [comment]
mine had given this error and I solved it like this, did the solution solve for you? @alvares

**Comment by alvares** [comment]
Yes, Thank very much!
