### ISSUE TITLE
Nao consigo mais conectar numero usando QrCode

### ISSUE THREAD

**Issue by lidernetworktecnologia** [canove/whaticket#430]
Sábado passado o whaticket parou inesperadamente. Ao tentar ler o QrCode exibe a seguinte mensagem:

`UnhandledPromiseRejectionWarning: Error: Authenticating via JSON session is not supported for MultiDevice-enabled WhatsApp accounts.
    at LegacySessionAuth.getAuthEventPayload (/home/whaticket/backend/node_modules/whatsapp-web.js/src/authStrategies/LegacySessionAuth.js:57:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Client.initialize (/home/lider/whaticket/backend/node_modules/whatsapp-web.js/src/Client.js:217:34)
(node:22467) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22467) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Já desinstalei completamente o whaticket, clonei o repositório, e não voltou mais. Tentei tmb atualizar o pacote Whatsapp-web.js e tambem o puppeteer para a versao 14.1.0 mas continua a apresentar mesmo problema. Detalhe é que não há outras sessoes abertas em nenhum dispositivo, pois somente é utilizado um unico numero em um unico dispositivo...
Alguem tem alguma solução??

**Comment by lidernetworktecnologia** [comment]
Obrigado pela ajuda! Consegui conectar mas agora ao enviar mensagem ela nao chega nos ticket pendentes, na verdade ela nao aparece em lugar nenhum, teria algum outro local que possa corrigir? Veja como ficou meu codigo:
`const wbot: Session = new Client({
        authStrategy: new LocalAuth({
          clientId: sessionName,
        })
      /*  puppeteer: {
          executablePath: process.env.CHROME_BIN || undefined,
          // @ts-ignore
          browserWSEndpoint: process.env.CHROME_WS || undefined,
          args: args.split(' ')
        } */
      });`

**Comment by rogeriojlle** [comment]
Eu não estou no meu computador agora, então as instruções vão ficar um pouco vagas...

remova a conexão existente, confira no celular se ela também desapareceu, pare o backend e apague a pasta "backend/.ww<algumacoisa>" (repare no ponto, ela está oculta)

troque para versão mais recente do pacote whatsapp-web.js (versão 1.16.6 no momento que escrevo isso)

suba o backend e crie de novo a conexão, certifique-se de que no nome dela não tenha espaços e se liga no mome que você escolheu.

pare de novo o backend.

execute o chromium que esta na pasta do puppeteer (dentro de node_modules/puppeteer, também oculta) passando o parametro  --user-data-dir=<a pasta que foi apagada lá no passo acima/(a dica do nome que voce escolheu) >

Estou considerando que você não especificou o binário  do chromium/chrome, então é por ali assim que ele vai estar

Vai ter um aviso para atualizar a versão do cliente web do whatsapp, faça. Feche o chromium

suba de volta o backend.

Divirta-se.

**Comment by lidernetworktecnologia** [comment]
Ola! Obrigado pela ajuda, mas continua a nao funcionar porque a pasta .wwebjs-auth nao é criada se usar o wbot.js original do repositorio. Tentei "mesclar" com o que o @rogeriojlle falou e a pasta dessa forma é criada mas as mensagens e ate conecta mas as mensagens nao chegam e quando chegam somem. Meu wbot.js está assim:

`const wbot: Session = new Client({
        session: sessionCfg,
        authStrategy: new LocalAuth({ clientId: sessionName, }),
        puppeteer: {
          executablePath: process.env.CHROME_BIN || undefined,
          // @ts-ignore
          browserWSEndpoint: process.env.CHROME_WS || undefined,
          args: args.split(' ')
        }
      });`

Também atualizei o whatsapp-web.js para a versao 1.16.6 e o puppeteer para a versao 14.1.0 com o novo chromium.
Tambem nao consegui entender como executar o puppeteer entao apenas o atualizei.
Já estamos desde de sábado sem atendimento :(
Alguma soluçao a ser aplicada ainda?

**Comment by developerdevice** [comment]
O problema está 

> Ola! Obrigado pela ajuda, mas continua a nao funcionar porque a pasta .wwebjs-auth nao é criada se usar o wbot.js original do repositorio. Tentei "mesclar" com o que o @rogeriojlle falou e a pasta dessa forma é criada mas as mensagens e ate conecta mas as mensagens nao chegam e quando chegam somem. Meu wbot.js está assim:
> 
> `const wbot: Session = new Client({ session: sessionCfg, authStrategy: new LocalAuth({ clientId: sessionName, }), puppeteer: { executablePath: process.env.CHROME_BIN || undefined, // @ts-ignore browserWSEndpoint: process.env.CHROME_WS || undefined, args: args.split(' ') } });`
> 
> Também atualizei o whatsapp-web.js para a versao 1.16.6 e o puppeteer para a versao 14.1.0 com o novo chromium. Tambem nao consegui entender como executar o puppeteer entao apenas o atualizei. Já estamos desde de sábado sem atendimento :( Alguma soluçao a ser aplicada ainda?

O problema está no arquivo `backend/node_modules/whatsapp-web.js/src/Client.js` 

![image](https://user-images.githubusercontent.com/24875140/168816296-2db9b1b6-90f3-42de-874e-1d0708ddc9bd.png)
 
Eu basicamente precisei comentar o bloco da imagem e definir de forma manual o tipo de autenticação, no meu caso NoAuth, mas você pode definir qualquer um. Não debuguei ainda para localizar o motivo desse "bug", mas já resolve paliativo.

No começo desse mesmo arquivo você deve importar o método de autenticação que for usar.

```
const LegacySessionAuth = require('./authStrategies/LegacySessionAuth');
const NoAuth = require('./authStrategies/NoAuth');
```

Já no arquivo `backend/src/libs/wbot.ts`  você indica na instância do Client o AuthStrategy definido anteriormente

```
const wbot: Session = new Client({
        authStrategy: new NoAuth(),
        puppeteer: {
        args: ['--no-sandbox', '--disable-setuid-sandbox'],
          executablePath: process.env.CHROME_BIN || undefined
        },
});
```

**Comment by lidernetworktecnologia** [comment]
Ola, obg pela ajuda! @developerdevice realizei todos os procedimentos repassados e continua o mesmo problema, após leitura do QRCode é realizada a conexão porem as mensagens entrar e depois somem, se aceitar uma pendente ela entra em atendendo e depois some. Se enviar nova msg ela nao aparece em lugar nenhum. Ja tentei os métodos NoAuth e LocalAuth e nenhum deles funcionou ficam dessa forma conecta mas as msg nao funcionam como esperado...

**Comment by developerdevice** [comment]
> Ola, obg pela ajuda! @developerdevice realizei todos os procedimentos repassados e continua o mesmo problema, após leitura do QRCode é realizada a conexão porem as mensagens entrar e depois somem, se aceitar uma pendente ela entra em atendendo e depois some. Se enviar nova msg ela nao aparece em lugar nenhum. Ja tentei os métodos NoAuth e LocalAuth e nenhum deles funcionou ficam dessa forma conecta mas as msg nao funcionam como esperado...

Então sugiro uma nova instalação limpa do Whaticket.

Ao salvar os arquivos você deu `npm run build` na pasta backend?

**Comment by lidernetworktecnologia** [comment]
Consegui um avanço! Agora conectado e recebendo mensagens, somente ao enviar do Whaticket nele nao mostra o que vc esta enviando mas no celular aparece. Acredito q esta mais facil de resolver, vc tem alguma ideia do que seja? Estou usando o LocalAuth dessa forma:
`const wbot: Session = new Client({
        authStrategy: new LocalAuth({ clientId: sessionName, }),
        session: sessionCfg,
        puppeteer: {
          executablePath: process.env.CHROME_BIN || undefined,
          // @ts-ignore
          browserWSEndpoint: process.env.CHROME_WS || undefined,
          args: args.split(' ')
        }
      }); `

e no client.js esta assim apos comentar o bloco de codigo conforme vc me orientou:

`this.authStrategy = new LocalAuth();`

**Comment by lidernetworktecnologia** [comment]
Pronto resolvido! Apos a ultima tentativa troquei novamente a forma de conexão para NoAuth no wbot.js e client.js, deixando o session informado no parâmetro de entrada.

`const wbot: Session = new Client({ authStrategy: new NoAuth(), session: sessionCfg, puppeteer: { executablePath: process.env.CHROME_BIN || undefined, // @ts-ignore browserWSEndpoint: process.env.CHROME_WS || undefined, args: args.split(' ') } });`

Obrigado aos colegas @rogeriojlle , @developerdevice pela valiosa ajuda! Vamos em frente...
