### ISSUE TITLE
ERROR: UNKNOWN ERROR TO SIGNUP FRIST USER

### ISSUE THREAD

**Issue by srgoogle23** [canove/whaticket#44]
Error: ENOENT: no such file or directory, stat '/home/deploy/whaticket/frontend/build/index.html'

**Comment by srgoogle23** [comment]
when i acess my ip of vps after follow all the steps ( i just didnt install the nginx ) its appear that

**Comment by srgoogle23** [comment]
solved this issue, i have new one:
![image](https://user-images.githubusercontent.com/62403037/96051391-caa6c900-0e51-11eb-9239-7966faf04f83.png)

when i try to signup give this error ^

**Comment by srgoogle23** [comment]
xhr.js:184 POST http://192.168.1.126:3333/auth/signup 404 (Not Found)

**Comment by srgoogle23** [comment]
thats what is showing on console of chrome

**Comment by srgoogle23** [comment]
xhr.js:184 POST http://192.168.1.126:8080/auth/signup 404 (Not Found)

**Comment by srgoogle23** [comment]
helppp lol

**Comment by canove** [comment]
You need to check if your backend is running and listening on :8080. Try to access  http://192.168.1.126:8080/ and you should see a "cannot get /" on chrome. 

For further investigation, try running pm2 logs to see what's going on in backend console.

**Comment by srgoogle23** [comment]
which part of the VPS walkthrough can I have wrong?

**Comment by srgoogle23** [comment]
caralho canove tu fala pt-BR KKKKKKKK
coe
aliás, eu tava seguindo o passo a passo VPS daí a única coisa diferente que eu fiz foi ao invés de criar um DB com docker eu conectei ao meu DB online
tem algo que posso ter errado?

**Comment by canove** [comment]
Opa, falo sim! rsrs
O ideal é manter a comunicação aqui em inglês, assim a sua solução pode ajudar outras pessoas. 

Você fez o teste de tentar acessar a URL do backend direto pelo navegador?

**Comment by srgoogle23** [comment]
yes, i kno that, i was thinking in create a discord group, what u think about that?
then, asking ur question, i tried but i didint get the error that u said, it was "we could find ..."

**Comment by srgoogle23** [comment]
and i run "pm2 log whaticket-backend" and it was just "server running on port 8080"

**Comment by srgoogle23** [comment]
wow, tried now in another pc, running it and i get "cannot get / "

**Comment by srgoogle23** [comment]
but i'm still getting the same error when i tried to signup some user

**Comment by srgoogle23** [comment]
POST http://localhost:8080/auth/signup net::ERR_CONNECTION_REFUSED
when i open the DevTools on signup page i saw this error on console log

**Comment by srgoogle23** [comment]
http://192.168.1.125:3333/signup
im accessing this by this url on my pc bc it its on a vbs machine

**Comment by srgoogle23** [comment]
i fix it, i went to backend/.env and edit .env deleting localhost phrases and puting the ip of my machine
