### ISSUE TITLE
Tickets duplicando.

### ISSUE THREAD

**Issue by italow6** [canove/whaticket#441]
![image](https://user-images.githubusercontent.com/6899447/173395157-f68be604-1263-4288-a2f3-f7ae36ef4525.png)

Alguns tickets ficam duplicando, chega essa mensagem em braco e duplica no chamado. 

![b1978f8e-26d0-40f4-904a-56905dcb74ab](https://user-images.githubusercontent.com/6899447/173395309-bee271e8-bf25-40ec-b641-43ca76f6480f.jpg)
m

alquém tem a solução?

**Comment by jhonnatanBezerra** [comment]
alguem solucionou isso ?
@italow6

**Comment by DevShop1251** [comment]
Estou com o mesmo problema, alguém conseguiu resolver?

**Comment by codsec** [comment]
> Estou com o mesmo problema, alguém conseguiu resolver?

Limpe o banco de dados provavelmente houve uma conexão duplicada
