### ISSUE TITLE
ERROR: Error handling whatsapp message: Err: Error: Evaluation failed: r

### ISSUE THREAD

**Issue by AdrianoRobson** [canove/whaticket#447]
Algumas vezes estou obtendo esse erro. A Conexão esta conectada porem ao tentar enviar mensagem, aparece esse erro e não é possível enviar. A solução é reler o qrcode do numero novamente sempre que acontece isso. Alguem tem ideia do que possa ser isso?
![175752391-d9c55bc3-59fe-4885-9836-9d9bdb1f0a5e](https://user-images.githubusercontent.com/40671414/177798012-d9972b4e-1480-4eee-9cd7-db4da10710a6.png)

**Comment by Kouthk** [comment]
Você fez alguma modificação no codigo  da aplicação que está em uso? 
Qual a versão da biblioteca "Whatsapp-web.js" que você está utilizando? 
Esse erro surgiu de que forma? Estava funcionando normalmente antes? Ou é a primeira vez que você usa?

**Comment by AdrianoRobson** [comment]
> 

Versão do Whatsapp-web.js v1.17.1
Esse erro surgi ocasionalmente. A medida que novos tickets vao sendo criado.
Estava funcionando, nao sei se foi alguma atualização do whatsapp-web.js. Acontece que a aplicação esta rodando ai do nada da esse erro ao tentar enviar mensagem. 
Estou usando ubuntu 18.04
Dispositivo esta no MD

**Comment by AdrianoRobson** [comment]
> Algumas vezes estou obtendo esse erro. A Conexão esta conectada porem ao tentar enviar mensagem, aparece esse erro e não é possível enviar. A solução é reler o qrcode do numero novamente sempre que acontece isso. Alguem tem ideia do que possa ser isso? ![175752391-d9c55bc3-59fe-4885-9836-9d9bdb1f0a5e](https://user-images.githubusercontent.com/40671414/177798012-d9972b4e-1480-4eee-9cd7-db4da10710a6.png)

Esse erro esta relacionado a espaço em disco. A sessão precisa armazenar informções na pasta de sessão. Acontece que estava com muito pouco espaço e isso estava empedindo a sessão de armazenar informações  na pasta de session do whatsapp
