### ISSUE TITLE
check and double-check  disappear

### ISSUE THREAD

**Issue by xmariodiaz** [canove/whaticket#45]
Hi,  suddenly my check and double-check icons stop being shown that they were read or sent, it just shows the clock icon, however of this issue, the messages system is working fine. How can I fix it without relinking the session, I already tried restarting the backend and frontend but it didn't work, how can I address this issue?.
thanks.
![Untitled](https://user-images.githubusercontent.com/46854726/96285936-9fd18780-0fad-11eb-8546-f6b43b131013.png)

**Comment by canove** [comment]
Hey @xmariodiaz! 

It was caused by a change in new WhatsApp web version. You need to update your dependencies. You can do it by deleting your node_modules folder and running `npm install` and `npm run build` again on backend folder.
