### ISSUE TITLE
Quantas instâncias em um servidor

### ISSUE THREAD

**Issue by lucaspaulino** [canove/whaticket#456]
Boa noite, gostaria de saber quantas instâncias eu consigo subir em um servidor:

Single 4-Core Xeon E3 v5 3.4Ghz
16GB de ram

ou então se puderem me dizer algum outro exemplo.

att

**Comment by GabrielMaestre** [comment]
Cara, isso vai depender MUITO.
Se você definir 4gb de ram e ter seila 50 movimentações de tickets por dia, vai sobrar ram
e se você definir 2gb e ter umas 2000 movimentação dependendo vai faltar, mas o consumo que vejo do Whaticket é cerca de 200~300mb para 50 contatos, cerca de 2 tickets por hora.
Então consigo suplir tudo isso com apenas 2gb e sobra ainda.
Recomendo uma media de 2gb por whaticket (back end) o front end não requer mais do que 200mb
