### ISSUE TITLE
error npm run build frontend

### ISSUE THREAD

**Issue by srgoogle23** [canove/whaticket#46]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle frontend@0.1.0~prebuild: frontend@0.1.0
6 info lifecycle frontend@0.1.0~build: frontend@0.1.0
7 verbose lifecycle frontend@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle frontend@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/deploy/whaticket/frontend/node_modules/.bin:/us$
9 verbose lifecycle frontend@0.1.0~build: CWD: /home/deploy/whaticket/frontend
10 silly lifecycle frontend@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle frontend@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle frontend@0.1.0~build: Failed to exec build script
13 verbose stack Error: frontend@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid frontend@0.1.0
15 verbose cwd /home/deploy/whaticket/frontend
16 verbose Linux 4.15.0-39-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error frontend@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the frontend@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by canove** [comment]
Did you run `npm install before building?

**Comment by srgoogle23** [comment]
yes, i followed the same script to ubuntu vps

**Comment by canove** [comment]
Post here the output of `npm -v` and `node -v`

**Comment by srgoogle23** [comment]
![image](https://user-images.githubusercontent.com/62403037/96295878-c0f1a280-0fc4-11eb-9616-031f5f80f53c.png)

**Comment by canove** [comment]
We need more information. Try a `npm start` to see if development server starts ok.

**Comment by srgoogle23** [comment]
![Uploading image.png…]()

**Comment by srgoogle23** [comment]
![image](https://user-images.githubusercontent.com/62403037/96297695-a40a9e80-0fc7-11eb-91f2-ef604b15b1d3.png)

**Comment by srgoogle23** [comment]
wait a few seconds

**Comment by srgoogle23** [comment]
i waited for so many time and didnt show anything

**Comment by srgoogle23** [comment]
deploy@vps24731:~/whaticket/frontend$ npm run build

> frontend@0.1.0 build /home/deploy/whaticket/frontend
> react-scripts build

Creating an optimized production build...

<--- Last few GCs --->

[11223:0x2e47cc0]   335843 ms: Mark-sweep 250.7 (258.0) -> 250.4 (258.2) MB, 107                                                                                        1.4 / 0.1 ms  (average mu = 0.154, current mu = 0.019) allocation failure scaven                                                                                        ge might not succeed
[11223:0x2e47cc0]   337701 ms: Mark-sweep 251.0 (258.2) -> 250.7 (258.5) MB, 184                                                                                        7.9 / 0.1 ms  (average mu = 0.066, current mu = 0.002) allocation failure scaven                                                                                        ge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1eacf66008d1 <JSObject>
    0: builtin exit frame: concat(this=0x1bf380ea9d51 <JSArray[0]>,0x384dd4c50b5                                                                                        1 <Node map = 0x29e9a1d08b89>,0x1bf380ea9d51 <JSArray[0]>)

    1: registerBinding [0x37a57683e6c9] [/home/deploy/whaticket/frontend/node_mo                                                                                        dules/@babel/traverse/lib/scope/index.js:~555] [pc=0x3c5efe4fa8b3](this=0x391e60                                                                                        a38511 <Scope map = 0x29cbaafc20f9>,0x18ed4e30dd81 <String[#3]: var>,0x1bf380ea9                                                                                        c09 <NodePath map ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaS                                                                                        cript heap out of memory
 1: 0xa17c40 node::Abort() [node]
 2: 0xa1804c node::OnFatalError(char const*, char const*) [node]
 3: 0xb95a7e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bo                                                                                        ol) [node]
 4: 0xb95df9 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, c                                                                                        har const*, bool) [node]
 5: 0xd53075  [node]
 6: 0xd53706 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector)                                                                                         [node]
 7: 0xd5ffc5 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageC                                                                                        ollector, v8::GCCallbackFlags) [node]
 8: 0xd60e75 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v                                                                                        8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xd6392c v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::A                                                                                        llocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment                                                                                        ) [node]
10: 0xd2af1e v8::internal::Factory::NewFixedArrayWithHoles(int, v8::internal::Al                                                                                        locationType) [node]
11: 0xc0cd23  [node]
12: 0xc0d518 v8::internal::Builtin_ArrayConcat(int, unsigned long*, v8::internal                                                                                        ::Isolate*) [node]
13: 0x1409319  [node]
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the frontend@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/deploy/.npm/_logs/2020-10-16T20_03_32_372Z-debug.log

**Comment by srgoogle23** [comment]
npm ERR! /home/deploy/.npm/_logs/2020-10-16T20_03_32_372Z-debug.log 

is that:


0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.8
3 info using node@v12.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle frontend@0.1.0~prebuild: frontend@0.1.0
6 info lifecycle frontend@0.1.0~build: frontend@0.1.0
7 verbose lifecycle frontend@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle frontend@0.1.0~build: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/deploy/whaticket/frontend/node_modules/.bin:/us$
9 verbose lifecycle frontend@0.1.0~build: CWD: /home/deploy/whaticket/frontend
10 silly lifecycle frontend@0.1.0~build: Args: [ '-c', 'react-scripts build' ]
11 silly lifecycle frontend@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle frontend@0.1.0~build: Failed to exec build script
13 verbose stack Error: frontend@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid frontend@0.1.0
15 verbose cwd /home/deploy/whaticket/frontend
16 verbose Linux 4.15.0-39-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v12.19.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error frontend@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the frontend@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by srgoogle23** [comment]
:)

**Comment by canove** [comment]
`FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaS cript heap out of memory`

Maybe your VPS are running out memory. Since t's not appear to be related to whaticket itself. I'm closing this issue.
