### ISSUE TITLE
Error With WSS , Delay , etc

### ISSUE THREAD

**Issue by Askeshine** [canove/whaticket#460]
I have so much domains in my vps and i only have 1 PUBLIC IP, i cant use only 1 vps with NGINX with exclusive port 433 and 80 , etc

I add site to my apache2 with proxy same nginx WORKING fine all site working and functions but i have problem.

When recive message or when try to send message i have so MUCH DELAY (Like 3 mins between action)

Console log show thats:
![image](https://user-images.githubusercontent.com/37356127/186069529-a0e4fb2e-76f2-421c-858e-5af86cdbba8d.png)

When i send message i cant do nothing after 2 mins message send and page show fine but idk what happend.

Any can help me ?

**Comment by GabrielMaestre** [comment]
Is not a Delay problem, is a Backend problem,
check all ports (front end, backend in .env file, and nginx), try to use curl in backend (to check if page is online/working).
And try to REBUILD all aplication (front and back end).
