### ISSUE TITLE
npm run build - "FATAL ERROR"

### ISSUE THREAD

**Issue by paladinoestudio** [canove/whaticket#461]
Estou tentando instalar o Whaticket com aapanel durante a instalação deu um erro no run Build, alguém sabe me dizer o que pode ser?

![image](https://user-images.githubusercontent.com/111941093/186697640-3d34ecc2-897d-4a0a-bbfe-37aebabdfd71.png)

**Comment by Horgun** [comment]
Se vc nao tiver feito nenhuma modificação acredito que seja falta de memoria.
Ou, pode ser que a configuração desse aapanel esteja limitando o uso de memoria (nao sei como ele funciona, nunca usei).

**Comment by eduamaral23** [comment]
No *nix da um export NODE_OPTIONS=--max-old-space-size=4096
4096 eh a quantidade de memoria que será alocada para compilar.

**Comment by GabrielMaestre** [comment]
Tente fazer o que os dois cavaleiros a cima disse e use uma versão LTS do NodeJS por exemplo (16.16.0).
