### ISSUE TITLE
Arquitetura arm64

### ISSUE THREAD

**Issue by B4bayaga** [canove/whaticket#462]
Ola, gostaria de saber se roda em processador arm64, sempre que instalo não aparece o qrcode para connexão. Nesses casos uso o chomium pois o google chrome não roda arm64.

**Comment by GabrielMaestre** [comment]
Não sei te responder mas tente reinstalar as dependencias (puppeteer) que fica responsavel por isso, e como o chrome não roda em arm64 talvez o choromium tb não, mas você pesquisar os requisitos do choromium ou do puppeteer e ver se consegue rodar.
Qualquer coisa você pode tentar usar outro navegador que o puppeteer consiga usar.
