### ISSUE TITLE
I cant reply in groups , the message cant be sent

### ISSUE THREAD

**Issue by DPTOProgramacionIslaNetworks** [canove/whaticket#466]
Hi, i have a brand new installation of whaticket and 
im having troubles replying in groups

the error only ocurrs in groups , in direct message to a phone number works fine

the error code is the following

    message: "ERR_SENDING_WAPP_MSG"
    statusCode: 400

this error hapens in the file whaticket/backend/src/services/WbotServices/SendWhatsAppMessage.ts

i tried to fix it but no success
i hope somebody can help me

thanks in advance

**Comment by Luskan777** [comment]
I have same problem

**Comment by Luskan777** [comment]
I solved this problem through this [commit](https://github.com/canove/whaticket-community/commit/71faee03adf047f815f9a7fe4bea993be405f47f) .
