### ISSUE TITLE
CANT ACESS BACKEND AFTER FOLLOW NIGIX STEPS

### ISSUE THREAD

**Issue by srgoogle23** [canove/whaticket#49]
I will not post anything else here, they tried bruteforce on my server instead of helping us, as is the purpose of github.

**Comment by srgoogle23** [comment]
![image](https://user-images.githubusercontent.com/62403037/96636350-91f46d00-12f3-11eb-8451-f2f61779180a.png)

**Comment by EmersonGarrido** [comment]
Como esta suas portas?
