### ISSUE TITLE
Upgrade whatsapp-web.js ( Important update - media messages )

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [canove/whaticket#50]
@canove 

Important update
This release fixes an issue introduced in WhatsApp Web v2.2043.8 that prevented media messages from being sent reliably. Updating to this version is required to continue sending media messages.

https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.10.0

**Comment by canove** [comment]
Thanks for noting! I just updated package.json to use lastest version. 
To fix it in your environment, you can run `npm install whatsapp-web.js`
