### ISSUE TITLE
[Question] How to upgrade

### ISSUE THREAD

**Issue by ronna** [canove/whaticket#55]
I would like to upgrade an existing install and test the ticket transfer feature. I followed the instructions for installation and I am getting the below error after running:  npx sequelize db:seed:all

ubuntu@ip-172-31-24-121:~/whaticket/backend$ npx sequelize db:seed:all

Sequelize CLI [Node: 12.19.0, CLI: 5.5.1, ORM: 5.22.3]

Loaded configuration file "dist/config/database.js".
== 20200904070004-create-default-settings: migrating =======

ERROR: Validation error

What is the best way to upgrade an existing installation

**Comment by canove** [comment]
Hi, @ronna. Great question!

Just added upgrade instructions to README, take a look https://github.com/canove/whaticket#upgrading
