### ISSUE TITLE
Attach file error 500 ( Internal Server Error )

### ISSUE THREAD

**Issue by alvares** [canove/whaticket#56]
After I updated with git pull, when attaching a file an error is appearing:
https://i.imgur.com/K230rgO.png
POST appears on the console http: // ***: 8080 / messages / 16 500 (Internal Server Error).

Would anyone know what could be happening?
```
/whaticket/backend$ 
drwxrwxr-x   2 deploy deploy  12288 Oct 26 19:31 public/
```

**Comment by alvares** [comment]
I changed the folder permission to public on / backend /
`drwxrwxrwx 2 deploy deploy 12288 Oct 26 19:59 public /`

But the error has changed, now the message is
https://i.imgur.com/wfrsfeo.png
POST http: // ***: 8080 /messages/16 400 (Bad Request)

**Comment by canove** [comment]
Hi @alvares 
What version of whatsap-web.js did you have on your's backend package.json?

**Comment by alvares** [comment]
Hi @canove.
The version is "whatsapp-web.js": "^1.10.0",

A question, to solve this problem, can I delete the whaticket folder and clone it again from git and follow the step to upload the application again?
I ask, because in this case I wouldn't delete the data, right?

**Comment by canove** [comment]
Yeah, you can! All yours messages are stored in your database. You will lose just the medias that are stored in public folder.

**Comment by alvares** [comment]
Cool, I'll do it.
Thanks @canove.

Another question, would you know how to backup data (users, contacts) to transfer to another server?

**Comment by wirys** [comment]
> Legal, vou fazer isso.
> Obrigado @canove .
> 
> Outra pergunta, você saberia como fazer backup de dados (usuários, contatos) para transferir para outro servidor?

### Como fazer a migração do Whaticket para outro servidor sem perder dados

**1 º** -   Você realiza o backup da sua base em seu SGBD

**2 º** -  após isso vc faz  a copia da pasta  public. onde fica armazenada as mídias enviadas  e recebidas  e coloca ela no novo servidor 

**_OBSERVAÇÃO:_** após restaurar pare o serviço backend do servidor atual para não dar conflito com o novo.
Em seguida pode iniciar o serviço no servidor novo e verificar se estão todos os dados, depois de verificar se veio todos os dados vai em conexões e ver se esta conectado provavelmente vc vai ter que escanear o QR code novamente.DE 

EM AMBIENTE DE PRODUÇÃO TE ACONSELHO A FAZER ISSO EM UM HORARIO QUE VC NÃO RECEBE MENSSAGEM POIS AS MESSAGENS QUE SAO ENVIADAS DURANTE O PERIODO QUE O SERVIÇO BACKEND NÃO ESTA ATIVO AS INFORMAÇÕES NÃO APARECEM

**Comment by canove** [comment]
@alvares , it worked?

**Comment by alvares** [comment]
> @alvares , it worked?

Yeah! Thanks for all. I uploaded the files again and got back to working.
