### ISSUE TITLE
Error: Evaluation failed: Error: MsgKey error: don't have a matching constructor

### ISSUE THREAD

**Issue by xmariodiaz** [canove/whaticket#62]
Error: Evaluation failed: Error: MsgKey error: don't have a matching constructor

suddenly I got this message in my backend while in the  web site:

 Error: Request failed with status code 500.

**Comment by canove** [comment]
Hi, @xmariodiaz. Its related to an whatsappweb update releases yesterday. You need to update your whatsapp-web.js to fix it.

You can just run `npm install whatsapp-web.js@1.11.0` in you'rs backend folder, and rebuild /  restart backend.

See: https://github.com/pedroslopez/whatsapp-web.js/releases/tag/v1.11.0
