### ISSUE TITLE
Implement functionality to create "ticket in contact"

### ISSUE THREAD

**Issue by srgoogle23** [canove/whaticket#63]
In 9 days ago, an user called wirys created in a fork/pull of your project a cool implement: [the ticket in chat](https://github.com/wirys/whaticket)
Could you please review the pull and put in the your master?
Because I really think that's a good implement to your project.

**Comment by srgoogle23** [comment]
https://github.com/canove/whaticket/pull/58
https://github.com/wirys/whaticket

**Comment by srgoogle23** [comment]
@canove

**Comment by canove** [comment]
Hi @srgoogle23. I'm out of time these days. I'll take a look as soon as I can. Feel free to use @wirys meanwhile
