### ISSUE TITLE
[SUGESTÃO] Opção de ignorar grupos

### ISSUE THREAD

**Issue by developerdevice** [canove/whaticket#65]
Há a possibilidade de manter apenas mensagens enviadas no privado, ignorando mensagens de grupos?

**Comment by canove** [comment]
Eaí, @developerdevice , blz? 

Não existe uma opção pronta para isso, mas funcionalidade de tratar mensagens de grupos foi adicionada nesse commit: https://github.com/canove/whaticket/commit/4c67067d8f8e4d9fec1e1b9c9977d85e6cef728a

Você pode tentar remover esse código na sua aplicação ou criar uma configuração para desativar / reativar as mensagens em grupo.
