### ISSUE TITLE
ERRO DE CORS

### ISSUE THREAD

**Issue by developerdevice** [canove/whaticket#66]
Estou com um problema de CORS, quando tento fazer login na página de frontend, ele dá erro de CORS, pra usar a aplicação preciso usar uma extensão que altera o cabeçalho.

Já tentei mudar em todas as rotas do projeto e adicionar 

```
app.use(function(req, res, next) {
  res.header("Access-Control-Allow-Origin", "*"); 
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
  next();
});
```

porém mesmo assim não dá certo, alguma dica?

**Comment by canove** [comment]
Bom dia, @developerdevice. 

Geralmente esses erros ocorrem quando a configuração do ".env" não está correta no backend. Posta o exato erro que aparece no navegador e também seu arquivo .env do backend pra gente tentar entender melhor.

Abraço

**Comment by developerdevice** [comment]
Esse é o meu arquivo .env

```
NODE_ENV=DEVELOPMENT
BACKEND_URL=https://api.meusite.com.br
FRONTEND_URL=https://app.meusite.com.br
PROXY_PORT=443
PORT=8080

DB_HOST=localhost
DB_DIALECT=
DB_USER=whaticket
DB_PASS=whaticket
DB_NAME=whaticket

JWT_SECRET=3123123213123
JWT_REFRESH_SECRET=75756756756
```
Abaixo o erro no browser

Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em https://api.meusite.com.br/whatsapp/. (Motivo: esperado 'true' no cabeçalho CORS 'Access-Control-Allow-Credentials').

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.meusite.com.br/whatsapp/. (Reason: CORS request did not succeed).

Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em https://api.meusite.com.br/users/2. (Motivo: esperado 'true' no cabeçalho CORS 'Access-Control-Allow-Credentials').

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.meusite.com.br/users/2. (Reason: CORS request did not succeed).

Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em https://api.meusite.com.br/tickets?withUnreadMessages=true. (Motivo: esperado 'true' no cabeçalho CORS 'Access-Control-Allow-Credentials').

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.meusite.com.br/tickets?withUnreadMessages=true. (Reason: CORS request did not succeed).

Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em https://api.meusite.com.br/tickets?pageNumber=1&status=open&showAll=false. (Motivo: esperado 'true' no cabeçalho CORS 'Access-Control-Allow-Credentials').

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.meusite.com.br/tickets?pageNumber=1&status=open&showAll=false. (Reason: CORS request did not succeed).

Requisição cross-origin bloqueada: A política de mesma origem (Same Origin Policy) impede a leitura do recurso remoto em https://api.meusite.com.br/tickets?pageNumber=1&status=pending&showAll=true. (Motivo: esperado 'true' no cabeçalho CORS 'Access-Control-Allow-Credentials').

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.meusite.com.br/tickets?pageNumber=1&status=pending&showAll=true. (Reason: CORS request did not succeed).

**Comment by canove** [comment]
Acredito que o nginx pode estar conflitando com a política de CORS do express. O seu arquivo de configuração do nginx está exatamente igual ao do tutorial?

**Comment by developerdevice** [comment]
esse é o backend, eu revisei todo o readme, refiz todos os passos, mas estagnou nesse passo.


![Screenshot_1](https://user-images.githubusercontent.com/24875140/99068453-5021b400-258b-11eb-9c71-078616377ab1.png)

**Comment by canove** [comment]
Parece estar tudo ok. Em qual cloud provider vc está rodando a aplicação? As políticas de CORS são definidas no arquivo app.ts do backend: 
![image](https://user-images.githubusercontent.com/24817866/99069181-a511fa00-258c-11eb-8dc7-efeb392fafe3.png)

Se você não alterou esse arquivo, tudo deveria funcionar corretamente...

**Comment by developerdevice** [comment]
Apaguei a pasta `backend` e subi a do github, só assim parou os erros, obrigado pela força.
