### ISSUE TITLE
Pega as mensagens nao lidas (recebidas quando o bot estava offline)

### ISSUE THREAD

**Issue by luizoseas** [canove/whaticket#7]
Olá, percebi que no seu código está comentada os códigos:
			 const chats = await wbot.getChats();
			 let unreadMessages;                
			 for (let chat of chats) {
			 	if (chat.unreadCount > 0) {
			 		unreadMessages = await chat.fetchMessages({
			 			limit: chat.unreadCount,
					 });
					 Messageset.store(unreadMessages);
			 	}
			 }
			 console.log(unreadMessages);

Mas percebi que está incompleto, os dados não estão sendo armazenado no DB. Pergunto quais funções para que esses dados sejam tratados e armazenados no db?

**Comment by canove** [comment]
Olá, @luizoseas . Sim, foi apenas um teste para saber se era possível pegar todas as mensagens não lidas do whatsapp, para caso o bot fique offline. Não continuei a implementação, pois no meu cenário o WhaTicket roda em uma VM que fica sempre online, então acabei não concluindo a lógica. 

Se você quiser implementar, acho que os próximos passos seria usar as funções do arquivo wbotMessageListener (handleMessage, verifyTicket etc) em cada uma das mensagens encontradas nesse loop.

**Comment by luizoseas** [comment]
Obrigado!

**Comment by luizoseas** [comment]
Gostei bastante do seu projeto!
