### ISSUE TITLE
Error to send attach files

### ISSUE THREAD

**Issue by alvares** [canove/whaticket#71]
I'm having a problem sending an attachment to the message. 
When trying to attach a file, the error "Internal Server Error" appears. 
`POST http: //*.*.*: 8080/messages/02 500 (Internal Server Error)` appears on the console browser.

**Comment by luancv** [comment]
Make sure that redirecting hosts within your frontend is properly configured with your server, I was having the same failure and after studying the project I checked the properties of the Socket.Io that were in the frontend and were actually missing some information

**Comment by luancv** [comment]
> I'm having a problem sending an attachment to the message.
> When trying to attach a file, the error "Internal Server Error" appears.
> `POST http: //*.*.*: 8080/messages/02 500 (Internal Server Error)` appears on the console browser.

Make sure that redirecting hosts within your frontend is properly configured with your server, I was having the same failure and after studying the project I checked the properties of the Socket.Io that were in the frontend and were actually missing some information

**Comment by alvares** [comment]
Can you tell me what information is missing?
The error practically occurred alone, as it was working and stopped suddenly.

**Comment by alvares** [comment]
> > I'm having a problem sending an attachment to the message.
> > When trying to attach a file, the error "Internal Server Error" appears.
> > `POST http: //*.*.*: 8080/messages/02 500 (Internal Server Error)` appears on the console browser.
> 
> Make sure that redirecting hosts within your frontend is properly configured with your server, I was having the same failure and after studying the project I checked the properties of the Socket.Io that were in the frontend and were actually missing some information

**Comment by canove** [comment]
Hi, @alvares. You can try to running backend with `NODE_ENV=DEVELOPMENT` and take a look on terminal error. This should give you better information.

**Comment by canove** [comment]
> Make sure that redirecting hosts within your frontend is properly configured with your server, I was having the same failure and after studying the project I checked the properties of the Socket.Io that were in the frontend and were actually missing some information

I don't think it's related to Socket.io configuration, but I'm curious about this missing information you found up.

**Comment by alvares** [comment]
> Hi, @alvares. You can try to running backend with `NODE_ENV=DEVELOPMENT` and take a look on terminal error. This should give you better information.

Hi. When i run `npm start` show this:

`
> backend@1.0.0 start /home/deploy/whaticket/backend
> nodemon dist/server.js

[nodemon] 2.0.6
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node dist/server.js`
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::8080
    at Server.setupListenHandle [as _listen2] (net.js:1317:16)
    at listenInCluster (net.js:1365:12)
    at Server.listen (net.js:1451:7)
    at Function.listen (/home/deploy/whaticket/backend/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/home/deploy/whaticket/backend/dist/server.js:10:30)
    at Module._compile (internal/modules/cjs/loader.js:1015:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
    at Module.load (internal/modules/cjs/loader.js:879:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1344:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '::',
  port: 8080
}
[nodemon] app crashed - waiting for file changes before starting...
`

**Comment by canove** [comment]
Looks like another instance are running on port 8080

**Comment by luancv** [comment]
> > Make sure that redirecting hosts within your frontend is properly configured with your server, I was having the same failure and after studying the project I checked the properties of the Socket.Io that were in the frontend and were actually missing some information
> 
> @luancv
> I don't think it's related to Socket.io configuration, but I'm curious about this missing information you found up.

Your project helped me learn a little about Socket.Io and React, at first I was lost in the Socket.Io settings and really the flaw was related to the @alvares, the backend instance was directed to an origin that was not being allowed access and the server ports configured on the frontend were also different
