### ISSUE TITLE
app restart

### ISSUE THREAD

**Issue by inforeis** [canove/whaticket#73]
Pessoal, boa noite

sempre que recebo um mídia (jpeg, pdf, etc) a aplicacao reinicia e no chat a imagem não aparece (a não ser que a página seja recarregada). Alguém já passou por isso?

<img width="694" alt="Captura de Tela 2020-11-14 às 21 35 53" src="https://user-images.githubusercontent.com/39631830/99160022-629e0980-26c1-11eb-9ca6-51e6464e2af9.png">

| Change detected on path public/1605400277220.jpeg for app api - restarting
PM2           | Stopping app:api id:1
PM2           | pid=14484 msg=failed to kill - retrying in 100ms
PM2           | App [api:1] exited with code [0] via signal [SIGINT]
PM2           | pid=14484 msg=process killed
PM2           | App [api:1] starting in -fork mode-
PM2           | App [api:1] online

**Comment by canove** [comment]
Boa noite!

Parece que você está rodando o nodemon com o PM2, aí ele detecta uma nova imagem na pasta como mudança no código...

Tenta remover o serviço do pm2 (`pm2 delete 1`) e adicionar novamente com `pm2 start backend/dist/server.js` --name backend

**Comment by inforeis** [comment]
eu estou usando o pm2 como falou. porém não estou usando esse diretorio: backend/dist/server.js  pq n exite. estou colocando backend/src/app.js

talvez seja pq quando estou rodando npm install

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN backend@1.0.0 No description
npm WARN backend@1.0.0 No repository field.

added 455 packages from 338 contributors and audited 456 packages in 20.466s


dai tive que substituir por # yarn assim ele instala as tudo...

**Comment by canove** [comment]
Entendi... acho que você está usando a versão antiga, que era em JS... a versão nova em typescript gera essa pasta "dist" ao rodar yarn build

**Comment by inforeis** [comment]
Isso mesmo. Eu tive que fazer algumas customizações aqui p empresa. Por isso não atualizei p TS.
Alguma sugestão p corrigir o problema?

**Comment by canove** [comment]
De acordo com o site, você pode tentar `pm2 stop 0 --watch` onde `0` é o ID do seu backend
https://pm2.keymetrics.io/docs/usage/watch-and-restart/

**Comment by inforeis** [comment]
obrigado k9. reiniciei sem usar o watch

pm2 star src/app.js --name backend

quando acrescento --watch aconte este problema. ;)
