### ISSUE TITLE
Help install local

### ISSUE THREAD

**Issue by rapososoftwares** [canove/whaticket#74]
Hello, I followed the tutorial to install on my virtual machine (local) everything is running fine, however when I try to register or login, it presents me an error in the chrome console.

"Access to XMLHttpRequest at 'http://192.168.0.110:8080/auth/signup' from origin 'http://192.168.0.110:3333' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."
http://prntscr.com/vjm886

When i acces 192.168.0.110:8080 returns with Cannot GET /
and console: "GET http://192.168.0.110:8080/ 404 (Not Found)"
http://prntscr.com/vjm8u1

How can i proceed?

**Comment by luancv** [comment]
Make sure that the Frontend IP and port is correctly directed in the 'dist/app.js' path between lines 48 and 50, see if 'origin' is correctly passed on to the Frontend path. Backend interprets it as a whole, so putting '/' or any other character in front of the path defined in 'origin', will cause Backend to interpret only that way, the same method applies when passing to Web servers

**Comment by luancv** [comment]
> Hello, I followed the tutorial to install on my virtual machine (local) everything is running fine, however when I try to register or login, it presents me an error in the chrome console.
> 
> "Access to XMLHttpRequest at 'http://192.168.0.110:8080/auth/signup' from origin 'http://192.168.0.110:3333' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute."
> http://prntscr.com/vjm886
> 
> When i acces 192.168.0.110:8080 returns with Cannot GET /
> and console: "GET http://192.168.0.110:8080/ 404 (Not Found)"
> http://prntscr.com/vjm8u1
> 
> How can i proceed?

Make sure that the Frontend IP and port is correctly directed in the 'dist/app.js' path between lines 48 and 50, see if 'origin' is correctly passed on to the Frontend path. Backend interprets it as a whole, so putting '/' or any other character in front of the path defined in 'origin', will cause Backend to interpret only that way, the same method applies when passing to Web servers

**Comment by rapososoftwares** [comment]
Thanks for the answer.
I didn't find frontend ip on 'dist/app.js', https://prnt.sc/vk0wty


This is how was configured on localhost, dont know if is correct because on readme teaches only on a VPS with domain name.
Frontend/.env = https://prnt.sc/vk0qcl
Backend/.env = https://prnt.sc/vk0pun
/etc/nginx/sites-available/whaticket-frontend = https://prnt.sc/vk0vlv
/etc/nginx/sites-available/whaticket-backend = https://prnt.sc/vk0w0l

**Comment by canove** [comment]
Hi, @rapososoftwares. Try changing `PROXY_PORT` to `80`

**Comment by rapososoftwares** [comment]
Thanks for the answer @canove .
Changed proxy port to 80 on whaticket/backend/.env and npm run build / sudo service nginx restart
still getting the error https://prnt.sc/vk4t3s

**Comment by canove** [comment]
> Thanks for the answer @canove .
> Changed proxy port to 80 on whaticket/backend/.env and npm run build / sudo service nginx restart
> still getting the error https://prnt.sc/vk4t3s

See the last part of my reply (edit now). You need to use DNS names and reach port 80 on your browser, not the service port itself (8080)

**Comment by rapososoftwares** [comment]
I don't know where I'm going wrong, https://prnt.sc/vk5a5h
but this is good for learning.
(for me who didn't know anything about linux, or nodejs is already an advance to get here.).

Thanks for now.

**Comment by canove** [comment]
On backend.env, change PROXY_PORT to 80
delete `backend/dist` folder and run `npm run build` again

**Comment by rapososoftwares** [comment]
Working now, thank you so much for you help @canove !
https://prnt.sc/vk7szz
