### ISSUE TITLE
Suggestion, save sessions.

### ISSUE THREAD

**Issue by KatiaSishost** [canove/whaticket#75]
How to save the session to when i restart the server... it not loss the conection with whatsapp.

**Comment by canove** [comment]
Hi, @KatiaSishost. The session details are stored in database. It should reconnect with same session once you start your backend again.

**Comment by wirys** [comment]
Hi, @KatiaSishost. check that your session is not expiring by default it expires in 15 min.
you can increase this time by changing the auth file inside the config folder on the backend.
![image](https://user-images.githubusercontent.com/31362538/99392374-5fba3900-28ba-11eb-8710-59aa39120629.png)
