### ISSUE TITLE
[PROBLEMA] Se Estiver muitas mensagens sem ler ele separa em vários tickets cada mensagem 

### ISSUE THREAD

**Issue by wirys** [canove/whaticket#76]
**Realizei o teste utilizando a nova funcionalidade de buscar mensagens não lidas assim que conecta o QR code**

![image](https://user-images.githubusercontent.com/31362538/99387851-67c2aa80-28b3-11eb-8b46-b8cece684c16.png)

**Comment by canove** [comment]
Olá, @wirys! De fato, também notei esse bug. Vou analisar mais tarde. Obrigado!

**Comment by canove** [comment]
@wirys. Tentei reproduzir esse problema mas não consegui. Desliguei o servidor, enviei várias mensagens de outro número e depois liguei o servidor novamente todas as mensagens chegaram no mesmo ticket. Você conseguiu reproduzir de forma consistente?

**Comment by wirys** [comment]
Verifiquei com Mensagens de Grupo de Contatos não cheguei a ver se ocorre

**Comment by luancv** [comment]
@canove @wirys, não sei se e somente pra mim, mas eu notei este bug também porém percebi que nas notificações ele não multiplicando o os tickets, somente na área de pending, inclusive pra utilização eu retirei a área de pending e mantive somente as notificações, e pra mim não esta mais ocasionando o bug porem ao habilitar novamente o pending e possível ver os tickets de aguardando todos multiplicados.

**Comment by luancv** [comment]
@canove @wirys, não sei se e somente pra mim, mas eu notei este bug também, porém percebi que nas notificações ele não multiplica os tickets, somente na área de pending, inclusive pra utilização eu retirei a área de pending e mantive somente as notificações, e pra mim não esta mais ocasionando o bug, caso seja habilitado novamente o pending e possível ver os tickets de aguardando todos multiplicados.

**Comment by esteves67** [comment]
@wirys Esse bug não havia me ocorrido até então, mas na última semana ocorreu, depois não ocorreu mais, bem raro esse bug.
