### ISSUE TITLE
Elemento permitido somente para admin

### ISSUE THREAD

**Issue by luancv** [canove/whaticket#77]
Estou com uma duvida, eu coloquei algumas paginas para acesso somente com usuário admin, porem eu queria permitir o botão todos somente para admin também, estou com grande dificuldade pois quando faço alterações o botão fica inacessível para ambos usuários, poderiam me dar uma dica de como acrescentar estas permissões.

**Comment by igormenin** [comment]
@luancv posta a parte do código aonde você tenta dar permissões específicas par ao ADMIN.

**Comment by canove** [comment]
@luancv. Dá uma olhada nesse arquivo, nele eu "escondo" alguns itens do menu caso o usuário não seja admin: https://github.com/canove/whaticket/blob/master/frontend/src/components/_layout/MainListItems.js

Basicamente seria isso, e também implementar a validação no backend

**Comment by luancv** [comment]
> @luancv. Dá uma olhada nesse arquivo, nele eu "escondo" alguns itens do menu caso o usuário não seja admin: https://github.com/canove/whaticket/blob/master/frontend/src/components/_layout/MainListItems.js
> 
> Basicamente seria isso, e também implementar a validação no backend

Consegui dei uma olhada no arquivo que me falou e consegui alterar bastante coisa, restringir bastante elemento, muito obrigado.
