### ISSUE TITLE
PM2 - FRONTEND não Start

### ISSUE THREAD

**Issue by odcni** [canove/whaticket#78]
Bom dia.

Estou com dificuldades, de fazer um start pelo pm2 do frontend. Ele start, mas não faz mais nada.

Estou fazendo pelo windows 10.

Alguém passou pela essa dificuldade e conseguiu achar um caminho certo.

**Comment by wirys** [comment]
Bom dia por acaso vc utilizou o comando 
`npm run build`
em seu frontend?

**Comment by esteves67** [comment]
@odcni Caso não consiga com o PM2 tente o Forever, ele é tão bom quanto o PM2 na minha opinião, para rodar é a mesma coisa: forever start dist/server.js, eu atualmente na minha instância do Whaticket utilizo o Forever para manter a aplicação sempre rodando.

**Comment by odcni** [comment]
> Bom dia por acaso vc utilizou o comando
> `npm run build`
> em seu frontend?

Sim. Rodei. Com backend foi. Mas com a parte do frontEnd não

**Comment by odcni** [comment]
> @odcni Caso não consiga com o PM2 tente o Forever, ele é tão bom quanto o PM2 na minha opinião, para rodar é a mesma coisa: forever start dist/server.js, eu atualmente na minha instância do Whaticket utilizo o Forever para manter a aplicação sempre rodando. Mas vai do gosto e aplicação no caso concreto de cada um, claro.


 start dist/server.js, seria o backend. Qual seria do frontend pra Forever?

**Comment by esteves67** [comment]
@odcni Verdade me enganei, desculpa, para o frontend seria o comando `start server.js` dentro da pasta frontend.
Segue o print como utilizo o Forever para iniciar automaticamente quando o servidor reinicia, e daí em diante ele fica rodando sem parar

![image](https://user-images.githubusercontent.com/18627611/99583236-f58cbb80-29c1-11eb-9119-60400dee09e9.png)

**Comment by esteves67** [comment]
@odcni Verdade me enganei, desculpa, para o frontend seria o comando `start server.js` dentro da pasta frontend.
Segue o print como utilizo o Forever para iniciar automaticamente quando o servidor reinicia, e daí em diante ele fica rodando sem parar

![image](https://user-images.githubusercontent.com/18627611/99583236-f58cbb80-29c1-11eb-9119-60400dee09e9.png)

**Comment by esteves67** [comment]
@odcni Verdade me enganei, desculpa, para o frontend seria o comando `forever start server.js` dentro da pasta frontend.
Segue o print como utilizo o Forever no crontab/cronjob para iniciar automaticamente quando o servidor reinicia, e daí em diante ele fica rodando sem parar

![image](https://user-images.githubusercontent.com/18627611/99583236-f58cbb80-29c1-11eb-9119-60400dee09e9.png)

**Comment by odcni** [comment]
> @odcni Verdade me enganei, desculpa, para o frontend seria o comando `forever start server.js` dentro da pasta frontend.
> Segue o print como utilizo o Forever no crontab/cronjob para iniciar automaticamente quando o servidor reinicia, e daí em diante ele fica rodando sem parar
> 
> ![image](https://user-images.githubusercontent.com/18627611/99583236-f58cbb80-29c1-11eb-9119-60400dee09e9.png)

Tentei aqui, mas sem sucesso. 

![image](https://user-images.githubusercontent.com/73964455/99584912-5c12d900-29c4-11eb-826f-d8e319844e92.png)


Alguma ideia?

**Comment by esteves67** [comment]
@odcni Na minha máquina rodando este comando eu acesso o ip da máquina na porta 3333 (exemplo 192.168.100.123:3333), e a frontend está lá rodando. No meu caso também não aparece nenhuma mensagem depois de rodar o comando de start.

![image](https://user-images.githubusercontent.com/18627611/99586446-86659600-29c6-11eb-88ae-b49bd4d3bd9d.png)
![image](https://user-images.githubusercontent.com/18627611/99586455-88c7f000-29c6-11eb-9b75-f21084f05d03.png)

**Comment by esteves67** [comment]
@odcni No caso se vc for abrir a frontend no próprio computador que está rodando a frontend, para acessar é só colocar http://localhost:3333 na barra de endereços

**Comment by odcni** [comment]
> @odcni Na minha máquina rodando este comando eu acesso o ip da máquina na porta 3333 (exemplo 192.168.100.123:3333), e a frontend está lá rodando. No meu caso também não aparece nenhuma mensagem depois de rodar o comando de start.
> 
> ![image](https://user-images.githubusercontent.com/18627611/99586446-86659600-29c6-11eb-88ae-b49bd4d3bd9d.png)
> ![image](https://user-images.githubusercontent.com/18627611/99586455-88c7f000-29c6-11eb-9b75-f21084f05d03.png)

Bom dia, ele até executou a pagina. Mas parece que não esta fazendo a comunicação com backend 
![image](https://user-images.githubusercontent.com/73964455/99664478-00d5fa80-2a47-11eb-932b-e0bcc5033cbc.png)

**Comment by esteves67** [comment]
@odcni Boa tarde! 
Se for problema de comunicação entre o backend e o frontend,
tente verificar algumas informações no `.env` da pasta Backend e da pasta Frontend, tem que estar assim:

Backend `.env `
```
BACKEND_URL=http://192.168.1.200
FRONTEND_URL=http://192.168.1.200:3333
```

Frontend `.env `
```
REACT_APP_BACKEND_URL = http://192.168.1.200:8080/
```

Após alterar essas informações:
1 - apague a pasta `dist` do backend e execute o comando `npm run build` dentro da pasta backend.
2 - apague a pasta `build` do frontend e execute o comando `npm run build` dentro da pasta frontend.
2 - execute o comando `forever start dist/server.js` na pasta backend.
4 - execute o comando `forever start server.js` na pasta frontend.
5 - tente acessar novamente a frontend http://192.168.1.200:3333 e logar com seu usuário ou criar uma conta.

**Comment by esteves67** [comment]
@odcni Boa tarde! 
Se for problema de comunicação entre o backend e o frontend,
tente verificar algumas informações no `.env` da pasta Backend e da pasta Frontend, tem que estar assim:

Backend `.env `
```
BACKEND_URL=http://192.168.1.200
FRONTEND_URL=http://192.168.1.200:3333
PROXY_PORT=8080
PORT=8080
```

Frontend `.env `
```
REACT_APP_BACKEND_URL = http://192.168.1.200:8080/
```

Após alterar essas informações:
1 - apague a pasta `dist` do backend e execute o comando `npm run build` dentro da pasta backend.
2 - apague a pasta `build` do frontend e execute o comando `npm run build` dentro da pasta frontend.
2 - execute o comando `forever start dist/server.js` na pasta backend.
4 - execute o comando `forever start server.js` na pasta frontend.
5 - tente acessar novamente a frontend `http://192.168.1.200:3333` e logar com seu usuário ou criar uma conta.

Obs: testei no windows através do xampp com node e está funcionando na minha máquina, torcendo pra dar certo na sua máquina também :rocket:

**Comment by crismxin** [comment]
me chama no whatsapp que sei a resposta 
62984035561

**Comment by crismxin** [comment]
em breve posto aqui

**Comment by barkerpedro** [comment]
Try:

```shell
cd backend/
pm2 start dist/server.js --name whaticket-backend
cd ../frontend/
pm2 start node_modules/react-scripts/scripts/start.js --name whaticket-frontend

```

**Comment by faletotal** [comment]
did u get an update? 
- please send a message to us right here, i think i can help u
