### ISSUE TITLE
 sessão default

### ISSUE THREAD

**Issue by inforeis** [canove/whaticket#84]
Qual a diferença entre a opção de sessão default e a não default do WhatsApp no whaticket @canove ?

**Comment by canove** [comment]
@inforeis, os tickets que são aberto quando você recebe uma mensagem, são atrelados ao whatsappId da sessão que recebeu a mensagem, mas quando você é você que cria um novo ticket, ele associa ao whatsapp default.

A opção de "importar contatos", também importa do default.

**Comment by inforeis** [comment]
blza. obrigado.

**Comment by inforeis** [comment]
.
