### ISSUE TITLE
[Feature Suggestion] character and collate Mysql

### ISSUE THREAD

**Issue by Cyrizx** [canove/whaticket#86]
use  character utf8mb4 and collate utf8mb4_unicode_ci in table Messages and LastMessages to be able to store and view messages with emojis, 

Currently if a person starts a conversation with an emoji, it does not reach the system

**Comment by canove** [comment]
Hi, @Cyrizx.
I'm already using it. 

If follow follow tutorial and use `docker run --name whaticketdb -e MYSQL_ROOT_PASSWORD=strongpassword -e MYSQL_DATABASE=whaticket -e MYSQL_USER=whaticket -e MYSQL_PASSWORD=whaticket --restart always -p 3306:3306 -d mariadb:latest --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
`  to create your database, it should work .
