### ISSUE TITLE
[Feature Suggestion] - Create an a Discord group for the whaticket repository

### ISSUE THREAD

**Issue by faletotal** [canove/whaticket#89]
If u wanna help with this, i can help

**Comment by luancv** [comment]
It would be very good for us to help each other.

**Comment by faletotal** [comment]
yes, im waiting the @canove answer

**Comment by esteves67** [comment]
@faletotal people currently uses pedroslopez's whatsapp-web.js (https://github.com/pedroslopez/whatsapp-web.js) discord which is a lib dependency that whaticket uses, there in that discord channel they have a portuguese section where brazilian people talk with each other, the community is pretty big there. If you want to join while whaticket discord group isn't created yet, here is the link for whatsapp-web.js channel: https://discord.gg/H7DqQs4 .

**Comment by canove** [comment]
@faletotal, I just created the server, but i'm not a heavy discord user. Message me there and I'll give you admin rights, so you can manage the server :)
https://discord.gg/MmtSXgGw

**Comment by luancyrne** [comment]
> @faletotal, I just created the server, but i'm not a heavy discord user. Message me there and I'll give you admin rights, so you can manage the server :)
> https://discord.gg/MmtSXgGw

If possible generate a new link please try to access this link but it is not available.

**Comment by canove** [comment]
Sorry guys, I'll try to update discord server this weekend. 

This is the permanent link: https://discord.gg/Dp2tTZRYHg
