### ISSUE TITLE
[Suggestion] Ignore Group Messages

### ISSUE THREAD

**Issue by esteves67** [canove/whaticket#9]
**Hello!**

> **Not a issue!** [ Suggestion ]

Since my bot is also in some groups, i've been using in my Whaticket instance, the function `msg.author != null`.
What it does is that it ignores group messages.

**Reason why im using that function:** 
I realized that someone send a message in a group the backend says it came from the person directly to me like if it were a private message not a group message. And it feels like the person is talking to me while the person is actually talking to the group.

I don't know if it will be useful inserting that code in Whaticket, but i wanted to point out what i found.

My code (wbotMessageListener.js):
```javascript
wbot.on("message_create", async msg => {
		// console.log(msg);
		if (
			msg.from === "status@broadcast" ||
			msg.type === "location" ||
			msg.type === "call_log" ||
			msg.author != null  // Ignore Group Messages
		) {
			return;
		}
```

**Comment by canove** [comment]
Thanks, @esteves67 . Suggestion implemented!
