### ISSUE TITLE
Enviar msg pelo backend através da api

### ISSUE THREAD

**Issue by ThunderBRZ** [canove/whaticket#91]
Desculpe o questionamento, sendo que não se trata de algum bug ou aprimoramento.
Gostaria de saber como posso usar o backend para enviar mensagens para determinados números, por exemplo utilizar um php para enviar algo.

Gostaria de agradecer imensamente ao Cassio pelo projeto. Ajuda demais aqui no nosso ambiente. Parabéns e esperando pra te pagar um café. rs

**Comment by canove** [comment]
Boa tarde, @ThunderBRZ, beleza?

Atualmente, não existe uma rota para envio de mensagem direto para um contato, você só consegue enviar uma mensagem para um ticket, que por sua vez está atribuído a um contato. 

Então, na API atual o fluxo ficaria assim: 
- Iniciar a sessão para conseguir o token necessário para as próximas requisições
- Criar ou pesquisar o contato e guardar o contact ID
- Criar um ticket para esse contato e guardar o Ticket ID
- Enviar a mensagem para o Ticket ID

Como pode ver, a API do backend foi projetada para atender às necessidades do frontend, por isso não é tão simples enviar uma mensagem para um número qualquer. 

Se quiser eu posso escrever as instruções, das etapas acima, para que você possa desenvolver algo com o seu sistema PHP, mas acredito que o melhor caminho seja melhorar a API para possibilitar o envio de mensagem sem atribuição de ticket ou contato.

Ahn, adicionei ao read o link do [Buy me a coffee](https://www.buymeacoffee.com/canove).

Abraços!

**Comment by ThunderBRZ** [comment]
Boa tarde.

Não estou conseguindo te pagar um café... rs... pois o paypal não aceita transações de paypal BR para BR em moeda não corrente.

- O vendedor não aceita pagamentos em sua moeda. (Msg do Paypal)

**Comment by esteves67** [comment]
@canove Não estou conseguindo lhe pagar um café, como forma de agradecimento pelo desenvolvimento do Whaticket nos ajuda muito, ao tentar lhe pagar o café me apresenta o mesmo erro do colega assim:  
`O vendedor não aceita pagamentos em sua moeda. Volte para o site do vendedor e escolha outra forma de pagamento.`

**Comment by canove** [comment]
Opa, desculpem a demora! 

Adicionei outro serviço de cobrança no Buy Me a Coffee, peço que tentem novamente, agora deve funcionar.

Obrigado pelo apoio! 💕

**Comment by esteves67** [comment]
> Opa, desculpem a demora!
> 
> Adicionei outro serviço de cobrança no Buy Me a Coffee, peço que tentem novamente, agora deve funcionar.
> 
> Obrigado pelo apoio!

Não consegui :cry: , habilitei meu cartão pra usar no exterior mas mesmo assim não foi, tentei o modo de pagamento pelo Paypal e pelo Google Play (Stripe), pelo que vi o Stripe só deixa debitar valor em R$ em cartões brasileiro (You can only charge Brazilian cards in BRL)(https://stripe.com/docs/currencies) :sob:

**Comment by canove** [comment]
> > Opa, desculpem a demora!
> > Adicionei outro serviço de cobrança no Buy Me a Coffee, peço que tentem novamente, agora deve funcionar.
> > Obrigado pelo apoio!
> 
> Não consegui 😢 , habilitei meu cartão pra usar no exterior mas mesmo assim não foi, tentei o modo de pagamento pelo Paypal e pelo Google Play (Stripe), pelo que vi o Stripe só deixa debitar valor em R$ em cartões brasileiro (You can only charge Brazilian cards in BRL)(https://stripe.com/docs/currencies) 😭

Sim, acabei de testar aqui e realmente não funciona... assim que encontrar outro serviço que aceite BRL, eu posto aqui.

**Comment by esteves67** [comment]
> > > Opa, desculpem a demora!
> > > Adicionei outro serviço de cobrança no Buy Me a Coffee, peço que tentem novamente, agora deve funcionar.
> > > Obrigado pelo apoio!
> > 
> > 
> > Não consegui cry , habilitei meu cartão pra usar no exterior mas mesmo assim não foi, tentei o modo de pagamento pelo Paypal e pelo Google Play (Stripe), pelo que vi o Stripe só deixa debitar valor em R$ em cartões brasileiro (You can only charge Brazilian cards in BRL)(https://stripe.com/docs/currencies) sob
> 
> Sim, acabei de testar aqui e realmente não funciona... assim que encontrar outro serviço que aceite BRL, eu posto aqui.

Agora que vi que vc editou o comentário acima informando que não funciona, vou apagar então meu comentário pra não ficar poluindo essa Issue.

**Comment by canove** [comment]
Pessoal, criei um link de doação via Paypal, e configurei para receber em BRL, agora deve funcionar!

https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=VWW3BHW4AWHUY&item_name=Desenvolvimento+de+Software&currency_code=BRL

Mais uma vez, obrigado!😍

**Comment by esteves67** [comment]
> Pessoal, criei um link de doação via Paypal, e configurei para receber em BRL, agora deve funcionar!
> 
> https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=VWW3BHW4AWHUY&item_name=Desenvolvimento+de+Software&currency_code=BRL
> 
> Mais uma vez, obrigado!

Boa noite @canove! Não é grande coisa (R$ 30,00) mas agora consegui fazer a doação! :rocket: :smile: :heart:

**Comment by esteves67** [comment]
> Pessoal, criei um link de doação via Paypal, e configurei para receber em BRL, agora deve funcionar!
> 
> https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=VWW3BHW4AWHUY&item_name=Desenvolvimento+de+Software&currency_code=BRL
> 
> Mais uma vez, obrigado!

Boa noite @canove! Não é grande coisa (R$ 30,00), mas agora consegui fazer a doação! :rocket: :heart: 
Muito obrigado por ter desenvolvido e disponibilizado à todos nós o Whaticket!

**Comment by canove** [comment]
É grande coisa sim, ajuda muito!
Obrigado, abraço!!
