### ISSUE TITLE
Error npm run build

### ISSUE THREAD

**Issue by myfrizqi** [canove/whaticket#92]
Error Build Frontend : npm run build

> frontend@0.1.0 build /root/whaticket/frontend
> react-scripts build
> 
> sh: 1: react-scripts: Permission denied
> npm ERR! code ELIFECYCLE
> npm ERR! errno 126
> npm ERR! frontend@0.1.0 build: `react-scripts build`
> npm ERR! Exit status 126
> npm ERR!
> npm ERR! Failed at the frontend@0.1.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-12-12T12_57_15_658Z-debug.log

Error Build Backend: npm run build

> backend@1.0.0 build /root/watiket/backend
> tsc
> 
> src/app.ts:19:3 - error TS2769: No overload matches this call.
>   The last overload gave the following error.
>     Argument of type '(req: Request<never, never, never, never>, res: { statusCode?: number | undefined; setHeader(key: string, > value: string): any; end(): any; }, next: (err?: any) => any) => void' is not assignable to parameter of type > > 'RequestHandlerParams<ParamsDictionary, any, any, ParsedQs>'.
>       Type '(req: Request<never, never, never, never>, res: { statusCode?: number | undefined; setHeader(key: string, value: > string): any; end(): any; }, next: (err?: any) => any) => void' is not assignable to type 'RequestHandler<ParamsDictionary, any, any, > ParsedQs>'.
>         Types of parameters 'req' and 'req' are incompatible.
>           Type 'Request<ParamsDictionary, any, any, ParsedQs>' is not assignable to type 'Request<never, never, never, never>'.
>             Type 'ParamsDictionary' is not assignable to type 'never'.
> 
> 19   cors({
>      ~~~~~~
> 20     credentials: true,
>    ~~~~~~~~~~~~~~~~~~~~~~
> 21     origin: process.env.FRONTEND_URL
>    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 22   })
>    ~~~~
> 
>   node_modules/@types/express-serve-static-core/index.d.ts:883:85
>     883 export type ApplicationRequestHandler<T> = IRouterHandler<T> & IRouterMatcher<T> & ((...handlers: > RequestHandlerParams[]) => T);
>                                                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>    The last overload is declared here.
> 
> Found 1 error.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 2
> npm ERR! backend@1.0.0 build: `tsc`
> npm ERR! Exit status 2
> npm ERR!
> npm ERR! Failed at the backend@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-12-12T13_27_41_902Z-debug.log

**Comment by canove** [comment]
Hi @myfrizqi. Did you run "npm install" on both folders before build?

**Comment by myfrizqi** [comment]
I've run "npm install" in both folders before building.
It's solved now. I changed the code in the backend/dist/app.js script as below:
>  //import cors from “cors”;
and add this code:
> const cors = require('cors');

Thank you
