### ISSUE TITLE
Alguém já fez ele rodar na rede interna?

### ISSUE THREAD

**Issue by patriciosilvadev** [canove/whaticket#94]
Bom tarde a todos.

Estou tendo dificuldade em acessar o frontend via rede, abro o navegado em outro computador aparece a janela para efetuar login, mas não efetuar login de forma alguma, estou rodando o servidor com Windows 10.

Ele aparece um pop-ip em vermelho, no computador local ele funciona normalmente, só em outro terminal que não consigo acessar.

Alguém já passou por essa dificuldade?

**Comment by ThunderBRZ** [comment]
O ip declarado nas configurações são da rede local???

**Comment by patriciosilvadev** [comment]
> O ip declarado nas configurações são da rede local???

está como localhost

estou tentando acessar pelo endereço ip do meu computador e pelo nome.

Exemplo na foto

![image](https://user-images.githubusercontent.com/62783690/102397386-915b1880-3fbc-11eb-89dc-012e6a3c9d70.png)

**Comment by canove** [comment]
@patriciosilvadev, você precisa configurar os .env utilizando o endereço IP do computador que está hospedando a aplicação, ao invés de localhost.

**Comment by patriciosilvadev** [comment]
> @patriciosilvadev, você precisa configurar os .env utilizando o endereço IP do computador que está hospedando a aplicação, ao invés de localhost.

Opa, maravilha, deu certo aqui, agora vou estudar como inserir as questões de departamentos.

Muito obrigado pela atenção.
