### ISSUE TITLE
Step by step for installation

### ISSUE THREAD

**Issue by Leo9401** [canove/whaticket#97]
hello everyone, I'm a beginner, I would like a step by step on how to install and make my machine open 'whaticket'

- which system do I have to use?

- which folder do I have to download?

-which commands to use?

-which version of linux?

**Comment by canove** [comment]
Hi, @Leo9401. Did you try to follow the README tutorial?

**Comment by Leo9401** [comment]
yes.
which system should i use?

**Comment by canove** [comment]
Those instruction ware made using a Ubuntu 18.04. Did you face any error while following it?

**Comment by Leo9401** [comment]
I'm a Linux novice, so I needed something more detailed, like step by step screnshot.
Do you have any vpn for me to host for free?

yway, i will download linux 18.04 .



PS: sorry for my english mistakes

**Comment by Leo9401** [comment]
https://releases.ubuntu.com/18.04/
on this link do I download ubuntu?

Desktop image or Server install image?

**Comment by canove** [comment]
If you don't have enough knowledge, server image may be a little trick. You can use Desktop in this case. 

Also, Whaticket works on Windows too, if you are more familiar with it.

**Comment by Leo9401** [comment]
how can i do on windows?
which commands?
what programs to download?

**Comment by eduardo20302** [comment]
have some files for me to download and install Whaticket for windows?

**Comment by canove** [comment]
@Leo9401, @eduardo20302 

 Would be nice to have a single downloadable file to run and use Whaticket easily, but, unfortunately there isn't.

I'm afraid that both of you will need to learn a little about linux, nodejs, and docker to run it properly.

**Comment by swalayan-hasbuna** [comment]
> how can i do on windows?
> which commands?
> what programs to download?

i created a step by step installation for windows, it work for me..

**Comment by swalayan-hasbuna** [comment]
> how can i do on windows?
> which commands?
> what programs to download?

[windows.instalation.txt](https://github.com/canove/whaticket/files/6008767/windows.instalation.txt)
