### ISSUE TITLE
Whatsapp Connection Problem

### ISSUE THREAD

**Issue by eserjpeg** [canove/whaticket#98]
Thanks for everything...

We have a problem for WhaTicket:

If i login web.whatsapp.com with my phone or restart WhaTicket in NodeJS, WhaTicket's Connection refuse and asking qr code again.

**Comment by canove** [comment]
Hi, @eserjpeg.

You should not login in web.whatsapp with same number you're using in Whaticket. Doing this, results in a "conflict" and release you session data from backend, so  you'll need to read qrcode again.

It shouldn't be the case when restarting whaticket backend. Your session should be keeped and connected again after server came up. 

I tried to reproduce it here, but works normally.

Tell me if you need further help.
