### ISSUE TITLE
I prepared a Turkish translation

### ISSUE THREAD

**Issue by eserjpeg** [canove/whaticket#99]
https://codeshare.io/2KKQoE
Here it is!

Lang Code: tr

**Comment by eduardo20302** [comment]
where do i put this file?

**Comment by eserjpeg** [comment]
> where do i put this file?
whaticket/frontend/src/translate/languages/
Here.

U can tr.js -> en.js and edit code on second line tr: to -> en:

**Comment by canove** [comment]
Hi, @eserjpeg. Thanks for this! I'll merge it in next update.
